### ISSUE TITLE
Privacy Badger and Hola co-existence

### ISSUE THREAD

**Issue by ghost** [EFForg/privacybadgerfirefox#110]
When Privacy Badger (0.1.3) is turned on in FireFox (30) the Hola Unblocker (1.3.276) cannot function. Are they incompatible by the nature of their operation? Hola initialization gives messages resembling what it would find if it was behind a corporate VPN. Is this 'sort of' what Privacy Badger is doing?

Is there some work-around for this, other than disabling PB whenever I want to obfuscate my IP address?

**Comment by cooperq** [comment]
@liamtr is this still a problem for you? I have been unable to reproduce this.

**Comment by diracdeltas** [comment]
Uh, you should probably stop using Hola: http://motherboard.vice.com/read/your-tool-to-access-netflix-content-abroad-is-hijacking-your-internet-connection

**Comment by liamtr** [comment]
Hmmm thanks for the info, i was not aware they were doing that.

I noticed that hola tried to set upnp rules in my router but i keep upnp turned off for security reasons. I wonder if my connection was still vulnerable to be used given that? Then again if hola is running it could well tunnel connections in and out at the same time.

-------- Original message --------
