### ISSUE TITLE
Privacy Badger interferes with Self-Destructing Cookies add-on for Firefox

### ISSUE THREAD

**Issue by ChristopherM1** [EFForg/privacybadgerfirefox#167]
The Self-Destructing Cookies add-on uses Firefox' Site Preferences feature to store the user's preferences. Privacy Badger adds entries to the site preferences, inadvertently loosening the rules for Self-Destructing Cookies, which is a white box solution that is much more restrictive than Privacy Badger. As such does Privacy Badger break Self-Destructing Cookies. If this cannot be fixed, then I would suggest adding a very visible warning to users to not use multiple cookie handlers, or something.

**Comment by auxbuss** [comment]
It's been a while, so I just installed Privacy Badger again. This problem persists.

Regarding SDC's dev comments: I tested on a clean profile.

**Comment by cooperq** [comment]
This issue is due to what is happening in #206, fixing that will fix this.

**Comment by cooperq** [comment]
closed via #425

**Comment by ChristopherM1** [comment]
Confirmed fixed in PB v.1.0.1. Thank you very much for fixing this! I am happy to be able to use PrivacyBadger again. Thanks for all the hard work.
