### ISSUE TITLE
Images in iframes not displaying

### ISSUE THREAD

**Issue by ghost** [EFForg/privacybadgerfirefox#171]
I spent the better part of the last week trying to understand why images weren't displaying on one of my sites in Firefox (thanks for that - guess I don't get paid for that lost time then!!). After several days of researching I noticed that people whom had AdBLock installed were occassionally having a similar issue.

I don't have AdBlock installed but DO have Privacy Badger. So I opened it up whilst on the page with missing images and lo and behold Privacy Badger had blocked the images claiming they were 'tracking'.

This is completely wrong! The images AREN'T being used for tracking... I know because they are supplied to the iFrame on the page missing images from another website that I also control and I can clearly state - WE DO NOT TRACK OUR USERS IN ANY WAY (UNLESS THEY ARE LOGGED IN).

So I'm wondering why Privacy Badger is blocking perfectly valid NON-TRACKING images from my pages??

I'm dumping this plugin now and will advise my clients to do the same. We may come back to it in a couple of years when your algorithms work! In the meantime - I suggest being wary, as in my country I would have a valid reason for taking you to court for this! When you claim that you stop tracking, then that's what you should do FFS not block VALID CONTENT!! 

I'm seriously beginning to wonder about the coding skills of the modern generation... or even what is accepted as 'working'. This plugin does not do what it is supposed to and actively damages brands that the website represents - as it did mine. 

Next time...this will be a legal matter. You have been warned.

**Comment by h-c-c** [comment]
I beg your pardon, but that's not a good solution imho.  I've just run into this issue myself, while developing an intranet web portal...it's not on the Internet at all, and never will be.  Why would I want to tell you anything about it just to use Privacy Badger?  I think a better option is to give users more freedom with a whitelist feature that they can manage themselves.

**Comment by cooperq** [comment]
There is a whitelist feature you can manage yourself already! If you click on the privacy badger icon you can unblock any of the domains by moving them from red to yellow (block cookies only) or green (unblock).  I hope this helps! Soon we will have clearer documentation about how this works.
