### ISSUE TITLE
New users are frustrated by Privacy Badger's tracker settings on first install

### ISSUE THREAD

**Issue by diracdeltas** [EFForg/privacybadgerfirefox#179]
Related to #47.  Lately, our dismal reviews in the Mozilla Add-ons Store seem to mostly be from people who:

1. Install PBadger
2. See that all the trackers are set to green when they first visit webpages.
3. Conclude that PBadger has useless default settings and uninstall it, before they realize that PBadger doesn't block anything until the heuristic algorithm has seen enough of their browsing.

My theory is that most of our early users found PBadger through the EFF blog post or some other publication that explained heuristic blocking. Seems to not be the case anymore.

Two possible solutions:
* On first install, the first time the popup is displayed, show a bright red notification box that says, "Why isn't anything blocked yet?" Explain heuristic blocking when the user clicks on the box.
* Ship with a default list of things that are blocked. Ex: the disconnect.me list.

**Comment by cooperq** [comment]
I think that this issue could be solved by two things, having a better onboarding experence, as in #96 and porting over the changes @SomMeri made to the chrome version, showing a help message when nothing is blocked yet.

**Comment by cooperq** [comment]
This is dependent on #434 and #439 
Once we have those in I am going to close this.

**Comment by cooperq** [comment]
This is now fixed.
