### ISSUE TITLE
Google cookies going through after blocking

### ISSUE THREAD

**Issue by phly95** [EFForg/privacybadgerfirefox#189]
I disabled all cookies on firefox, except I found that google is using some glitch in the privacy badger add-on that allows google cookies to go through from youtube, and maybe other google sites
1. disallow all cookies
2. go to youtube
3. check cookie exceptions to see apis.google.com on the list which HAS NOT given permission to send cookies

Knowing about this issue means I will stop using privacy badger for the time being until I know this problem is fixed

**Comment by monperrus** [comment]
Still affected by this bug.

While trying to completely disable the Google cookie (www.google.com -> Block, google.com -> Block), it kept re-appearing in my cookie list.  

I had to uninstall PrivacyBadger to be able to disable the Google cookie.
