### ISSUE TITLE
Should be able to view list of all blocked sites and change settings

### ISSUE THREAD

**Issue by keybounce** [EFForg/privacybadgerfirefox#199]
Right now there is no way I can find to see the list of all red sites. Not just for this page; all of them. In other words, get the list of blocked sites.

A search turned up pull request #2, which was closed as 'not the right approach'. Even if that's correct, something would be useful.

**Comment by cooperq** [comment]
fixed in #371

**Comment by SwartzCr** [comment]
@keybounce you might enjoy trying our new stable version which has this change implemented: https://github.com/EFForg/privacybadgerfirefox/tree/stable
feel free to reach out for help if you need help installing it, otherwise it'll be in the main version soon :)

**Comment by keybounce** [comment]
I have no idea how to install firefox extensions except by installing them pre-assembled and ready to go.

**Comment by cooperq** [comment]
The new version will be out soon! You can wait for that :)
