### ISSUE TITLE
Enable full domain whitelisting

### ISSUE THREAD

**Issue by andreengels** [EFForg/privacybadgerfirefox#209]
I work on wikidata, the database for wikipedia. To do so, I have to have to be logged in on Wikipedia while working on tools.wmflabs.org. Privacy Badger considers this an external tracker. Problem is, every language of Wikipedia is considered a separate tracker. I'd like to whitelist wikipedia.org at once, rather than having to have en.wikipedia.org, de.wikipedia.org, ru.wikipedia.org and several dozen languages more separately each.

**Comment by cooperq** [comment]
This will be possible as of the 1.0 release in the options page.
