### ISSUE TITLE
Flash  crashes on Hulu with linux

### ISSUE THREAD

**Issue by GoldenStake** [EFForg/privacybadgerfirefox#214]
When I attemt to watch videos on Hulu, the flash plugin crashes with a segfault
    [188954.752804] plugin-containe[4982]: segfault at 8 ip 00007f09f2893e04 sp 00007fffb239e580 error 4 in libflashplayer.so[7f09f2367000+117f000]

I am running Ubuntu 14.04.1 LTS and Firefox 31.0

**Comment by cooperq** [comment]
This is fixed by privacybadgerchrome/85b0abecbc99fd968020d81468cac8d6fb5f6eb5

**Comment by cooperq** [comment]
85b0abecbc99fd968020d81468cac8d6fb5f6eb5
