### ISSUE TITLE
Badger broke my Add to Mastercook button

### ISSUE THREAD

**Issue by ghost** [EFForg/privacybadgerfirefox#215]
just wanted to let you know that Badger broke my Add to Mastercook button. I could not import any recipes from the web  when it was enabled. As soon as I disabled it in Firefox, the button worked again. You can try it yourself by going here- see below (  free to register)
Hope you can fix this, as I was really liking this app!
Thanks
jrosie

https://mastercook.com/register

 

and trying any recipe at myrecipes.com, etc.

**Comment by cooperq** [comment]
for now you can trigger mastercook.com by trying to add a recipie, then you can click the privacy badger icon and move the slider for mastercook.com to green. I am unwilling to add them to the cookieblock list because they actually have a pretty bad privacy policy!
