### ISSUE TITLE
Privacy Badger blocks correctly configured Piwik with DNT ON

### ISSUE THREAD

**Issue by oerdnj** [EFForg/privacybadgerfirefox#219]
We have own Piwik installation that honours DNT (Settings->Privacy: "You are currently respecting your users Privacy, Bravo!") and it's still getting blocked by Privacy Badger.

This can be seen f.e. on https://www.knot-dns.cz/

What can be done to help debug this issue? (e.g. can Privacy Badger generate a full debugging log with requests and results?)

**Comment by cooperq** [comment]
Hi @oerdnj is this still an issue for you?
