### ISSUE TITLE
Blocks Adobe Flash configuration page

### ISSUE THREAD

**Issue by skue** [EFForg/privacybadgerfirefox#233]
PB appears to block the stylesheet and Flash object (via wwwimages.adobe.com) on these pages:

http://www.macromedia.com/support/documentation/en/flashplayer/help/settings_manager04.html
http://www.macromedia.com/support/documentation/en/flashplayer/help/settings_manager07.html

This prevents us from inspecting the Flash plugin, changing settings, viewing LSOs, etc.

This is running PB 0.1.2 on FF 32.0.3

**Comment by cooperq** [comment]
fixed in privacybadgerchrome@a912d9279cb8fa9344085c72ae6b1c725a444b47
