### ISSUE TITLE
YouTube automatically resets its cookie permission in Firefox

### ISSUE THREAD

**Issue by tahaa7** [EFForg/privacybadgerfirefox#241]
I have noticed a strange bug. I have set a rule in Firefox to block cookies from youtube.com. However, when I visit youtube.com, YouTube automatically sets its cookie permission in Firefox back to "Allow first party only" (which is my default cookie policy in Firefox). After that I have to add the block rule again.

The bug is related to Privacy Badger, because upon disabling it, this issue no longer exists. I have noticed this only with YouTube.com so far, because that site is one of those whose cookies I explicitly want to block.

**Comment by BadgerBug** [comment]
I can confirm. I was just about to file bug ticket myself.
Steps to reproduce:
1) configure Firefox to block any cookies whatsoever from www.youtube.com
2) browse webs with embedded youtube conent (http://eternity.obsidian.net/media - worked for me 100%)
3) check permissions again, cookies from youtube will be allowed

**Comment by cooperq** [comment]
this is because of what is happening in #206 
I need to refactor privacy badger to not use domain exceptions for its cookie blocking behavior.
