### ISSUE TITLE
connection failure

### ISSUE THREAD

**Issue by dcastellanos44** [EFForg/privacybadgerfirefox#246]
Unable to download privacy badger for firefox for connection failure. Please help!

**Comment by cypherpunk** [comment]
I am getting exactly the same problem when I try to update or re-install latest version. Firefox 34 win7pro.

**Comment by cooperq** [comment]
This is a known issue with EFF's website, we are working on it.

**Comment by cooperq** [comment]
@dcastellanos44 are you still having this issue? Can you tell me what operating system you have, what web browser you have and what other extensions you have installed on that browser?

**Comment by dcastellanos44** [comment]
No, I just downloaded and successfully installed the add-on in fire fox, 
thanks.
On 2/24/2015 4:43 PM, Cooper Quintin wrote:
>
> @dcastellanos44 <https://github.com/dcastellanos44> are you still 
> having this issue? Can you tell me what operating system you have, 
> what web browser you have and what other extensions you have installed 
> on that browser?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/EFForg/privacybadgerfirefox/issues/246#issuecomment-75883065>.
>

-- 
“Las tumbas nos recuerdan la brevedad de la vida, y la resurrección nos garantiza la brevedad de la muerte”
   
  “While graveyards may remind one of the brevity of life, the resurrection ensures the brevity of death.”
