### ISSUE TITLE
Privacy Badger's toolbar button vanishes

### ISSUE THREAD

**Issue by Mokura** [EFForg/privacybadgerfirefox#253]
I installed PB yesterday on Firefox 33.1.1, and pretty much left it alone to do its tracking detection work.  Today, when I started Firefox, I've found that the toolbar button has vanished, not only from my toolbar, but from the Customization menu as well.  However, when I checked the list of extensions, PB was still installed.  Disabling and re-enabling PB did not resolve the issue.

**Comment by bigsky48** [comment]
When upgrading from Firefox 34 to 35 I "lost" the privacy badger toolbar.  I reloaded 34 and it reappeared.  When I try to install the new version in Firefox 35 from your Dec16 post, I received an error message saying "Firefox cannot modify the needed files".  Any idea of what to do?    Thanks.  Oh, Firebug is not installed.

**Comment by cooperq** [comment]
Try this fix and see if it helps: https://support.mozilla.org/en-US/questions/974165

**Comment by bigsky48** [comment]
It worked.  Thanks!

**Comment by lapisdecor** [comment]
Privacy Badger button not showing after firefox update on ubuntu 14.10. I have firefox 36.0.4. I'm using firebug. I have 2 other ubuntu computers (14.04) and one of them shows button, the other does not (same extensions on all).

**Comment by tsh69** [comment]
Since FF 50.x the problem is back. After each restart of FF PB's Icon in the toolbar is missing, needs manual replacement. Same problem with the icon of the addon Video DownloadHelper, if this is maybe an helpful information.
