### ISSUE TITLE
Privacy Badger Breaks the Amazon Wishlist Addon

### ISSUE THREAD

**Issue by dpTalia** [EFForg/privacybadgerfirefox#260]
I have the Amazon Wishlist Addon for Firefox. When I go to a shopping page it displays a little plus sign (i.e. it recognizes there is something to add) However, when I click the button nothing happens. When I disable Privacy Badger, clicking the button successfully adds the item to my wish list.

**Comment by cooperq** [comment]
Wontfix, this addon is necessarily tracking. However you can fix it yourself by clicking the privacy badger icon on a page after you have tried to use the wishlist addon. You can then move the slider for amazon domains from red to yellow.
