### ISSUE TITLE
Support LOAD_ANONYMOUS for sites on cookieblock list

### ISSUE THREAD

**Issue by monicachew** [EFForg/privacybadgerfirefox#263]
LOAD_ANONYMOUS is a flag that is more comprehensive than just blocking cookies. However, you would probably have to rearchitect several places in mozilla-central that open the channel, there's nothing built-in like ALLOW_FIRST_PARTY_ONLY that does this.

From https://mxr.mozilla.org/mozilla-central/source/netwerk/base/public/nsIRequest.idl#211
206     /**
207      * When set, this flag indicates that no user-specific data should be added
208      * to the request when opened. This means that things like authorization
209      * tokens or cookie headers should not be added.
210      */
211     const unsigned long LOAD_ANONYMOUS = 1 << 14;

**Comment by cooperq** [comment]
hmm, this might acutally be the way to fix #206 et. al.

**Comment by SwartzCr** [comment]
I don't know how I feel about the policy of closing 2.0 milestone issues

**Comment by cooperq** [comment]
I closed it because it was related to the cookieblocking thing, so I was
looking into it. After looking into it I decided it didn't make sense,
so I closed it. I probably should have left an explanation though.
