### ISSUE TITLE
Privacy Badger Blocks Extensions that Work Across Domains

### ISSUE THREAD

**Issue by kbquist** [EFForg/privacybadgerfirefox#269]
Privacy Badger is blocking PriceBlink, a popular browser extension that automatically compares prices when you're shopping online.  I'm one of the developers and am happy to discuss the specifics of how our extension works.  Tested in Firefox.  Have not tested in Chrome.

**Comment by SILVERSEYESONLYSIX99** [comment]
I'm always wiling to get sensible software for my daughter and I need to protect her from the dangers out there, so thank you for being that champion and I will return the favour to what is it you need on this site yours truly JAMES J. SILVER

**Comment by cooperq** [comment]
hi @kbquist,
As far as I can tell, your business model for priceblink is to retarget ads based on what the user is shopping for. Do I have that wrong?

**Comment by kbquist** [comment]
hi cooperq.  Sorry, I never saw your reply.  No, that's not our business model.  We don't do any ad retargeting.  What we do is show users price comparisons for the product they're viewing.  So when you're on a product page like this - https://www.amazon.com/dp/B010Q588D4/ PriceBlink will let you know where else you can find the item.

**Comment by naobigboy** [comment]
https://cdne-mobile.youjizz.com/videos/6/0/d/2/e/60d2e13925a7919f975969165026526e1472320845-640-360-900-h264.mp4?validfrom=1487874438&validto=1488047238&rate=184320&hash=fPWbfcKnA%2BVNOUtNgSpCbD7cGSE%3D
