### ISSUE TITLE
Privacy Badger prevents Kickstarter project page video widget from loading and working correctly

### ISSUE THREAD

**Issue by chrish42** [EFForg/privacybadgerfirefox#270]
When I visit a Kickstarter project page (e.g. https://www.kickstarter.com/projects/webeharebrained/shadowrun-hong-kong) with Privacy Badger enabled, I don't see the video widget for the project. The video widget seems to be / stay resized at about 40 pixels height, which makes it unusable. Uninstalling Privacy Badger, the video widget displays in full, with the image and play button.

**Comment by cooperq** [comment]
hi @chrish42 can you tell me which domains privacy badger has blocked on the kickstarter page? I suspect the problem might be cloudfront but I want to be sure.

**Comment by chrish42** [comment]
Something similar, yeah.. It's s3.amazonaws.com which is getting blocked completely (red), for some reason. Switching it to "block cookies" fixes the video widget.

**Comment by cooperq** [comment]
I have added s3 to the cookie block list.
