### ISSUE TITLE
IS this a bug?

### ISSUE THREAD

**Issue by jbacinti** [EFForg/privacybadgerfirefox#278]
All of a sudden, Privacy Badger blocks me from Facebook, especially
viewing videos.  I use Firefox and I must disable Privacy Badger for
Facebook to work. Any ideas?  I'm using V35 of Firefox.

**Comment by cooperq** [comment]
if you click on the privacy badger icon and unblock or cookieblock all of the facebook related domains does that fix the problem? You can unblock a domain by moving it's slider from red to yellow or green.

**Comment by jbacinti** [comment]
I'll try it next time a video is sent to me from Facebook.

PLEASE NOTE MY NEW EMAIL ADDRESS

John Augustin

Phone: 513-984-0425

Cell: 513-470-1603

jbacinti@gmail.com

**Comment by jbacinti** [comment]
Following your instructions below did not fix the problem. Do oyou have 
any other ideas?

PLEASE NOTE MY NEW EMAIL ADDRESS

John Augustin

Phone: 513-984-0425

Cell: 513-470-1603

jbacinti@gmail.com

**Comment by cooperq** [comment]
tell me which domains are blocked, when you try to view a video on facebook.

**Comment by cooperq** [comment]
make sure that you don't have youtube.com blocked.
