### ISSUE TITLE
Github image drag and drop broken

### ISSUE THREAD

**Issue by TransitScreen** [EFForg/privacybadgerfirefox#279]
Reproduce:

1. Drag image into text box on Github
2. Shows something like ![screen shot 2014-11-06 at 1 46 18 pm]
3. Upload never completes 

What should happen:

Upload completes, text changes to something like "![screen shot 2014-11-06 at 1 46 18 pm](https://cloud.githubusercontent.com/assets/"

**Comment by cooperq** [comment]
Can you tell me which domains privacy badger is blocking on github?

**Comment by caywood** [comment]
I'm not sure any if are listed, but the Privacy Badger button shows the number 1 right after page reload on Github.

**Comment by cooperq** [comment]
Click on the privacy badger icon and it will list domains it is blocking.

**Comment by caywood** [comment]
I tried that, the number 1 appeared then went away showing no domains




Regardless, the bug was reproducible.

**Comment by cooperq** [comment]
I am so far unable to reproduce this. It is also weird that this would be happening when privacy badger is not blocking any domains. Which version of privacy badger and which browser (and version) are you using? I assume the probelm goes away when you disable privacy bdager. 
Can you open up the developer console for your browser? Click the network tab and tell me about any domains where the request fails?
