### ISSUE TITLE
icon stays red all the time

### ISSUE THREAD

**Issue by gwt10** [EFForg/privacybadgerfirefox#280]
Even when I click on it and it says "Could not detect any tracking cookies".  The description at EFF says it's supposed to change from green to yellow to red depending on detection.  

If this is no long the case, then maybe the description should be modified to say it stays red all the time and if you want to see what's going on, you have to click on the icon and look at the status in PrivacyBadger's pop-up menu.

**Comment by cooperq** [comment]
This works as expected. Perhaps I need to update the documentation. It is not the icon that changes color but the sliders for each domain that privacy badger detects. You can see these sliders when you click on the icon if privacy badger has detected third party resources on that page.
