### ISSUE TITLE
Can I submit sites that aren't being displayed properly?

### ISSUE THREAD

**Issue by anonsubmitter** [EFForg/privacybadgerfirefox#281]
Can I submit sites that aren't being displayed properly and you'll add exceptions for those sites into Privacy Badger's next release or should I just stick to adding exceptions for these sites myself?

Edit: I see now from some of the closed issues that incompability reports for specific sites is accepted, so my question has been answered now.

**Comment by cooperq** [comment]
Indeed you can submit sites that aren't being displayed properly!
