### ISSUE TITLE
pokemonspecial.com is not being displayed properly

### ISSUE THREAD

**Issue by anonsubmitter** [EFForg/privacybadgerfirefox#284]
Example pages:
http://read.pokemonspecial.com/p/pokmon-sepcial.html
http://read.pokemonspecial.com/2014/06/chapter-001-vs-mew.html
http://zine.pokemonspecial.com/2014/05/Chapter-001.html
http://zine.pokemonspecial.com/2015/01/oras-chapter-001.html

Most of the pictures and layout on these pages are incorrectly blocked by Privacy Badger. Changing pipes.yahoo.com's blocking status from red to yellow fixes this. Please add this to the whitelist. Thanks!

**Comment by cooperq** [comment]
Thanks I will add pipes.yahoo.com to the cookie block list.
