### ISSUE TITLE
PB icon disappears in FF 36

### ISSUE THREAD

**Issue by andreasio** [EFForg/privacybadgerfirefox#286]
PB icon has disappeared from addons bar in FF36.

**Comment by cooperq** [comment]
do you have e10s turned on? If you click the customize button in the firefox menu do you see the privacy badger icon anywhere? Is it hidden behind the arrows that show up when you have too many addons?

**Comment by Klaaninka** [comment]
How do you turn on e10s? I have checked out the Customize button icons and it is not listed there. Also I have only 3 buttons showing.

**Comment by ianchanning** [comment]
I have the same problem too. Privacy Badger is shown as installed but there is no icon on the toolbar. The screenshot below is of the customize screen with all toolbars displayed. I'll start trying to disable other add-ons to see if there is a conflict.

![2015-02-27 01_12_09-customise firefox](https://cloud.githubusercontent.com/assets/233318/6404942/e788889a-be1d-11e4-8fd5-f794e2a25c8a.png)

**Comment by ianchanning** [comment]
I've disabled all other add-ons except for privacy badger and it still doesn't display. I tried uninstalling and re-installing too.

I'm on Windows 7 64-bit if that's relevant.

**Comment by ianchanning** [comment]
@Klaaninka e10s refers to the multiprocess version of Firefox 36 which was causing crashes in the nightly builds according to issue #208. This doesn't appear to be the same though as that was causing actual browser crashes.

**Comment by cooperq** [comment]
@ianchanning @andreasio what version of privacy badger are you running?

**Comment by cooperq** [comment]
@ianchanning there have been conflicts in the past with firebug. If you disable firebug and then disable and re-enable privacy badger does that fix the issue?

**Comment by ianchanning** [comment]
I tried disabling and removing firebug and then re-installing privacy 
badger but that didn't help.

**Comment by Klaaninka** [comment]
I am experiencing the "lost icon" problem too. I am running PB 0.1.4 and Windows 7 Professional. Any suggestions for getting it back. Is it even running (The add-on window shows that it is)?

**Comment by Klaaninka** [comment]
...also running Firefox 36

**Comment by cooperq** [comment]
@Klaaninka ah there is your problem, you are running an extrememly old version of privacy badger. I haevn't been able to update AMO in a while so we are hosting the latest version of privacy badger at EFF. you can download it from https://eff.org/pb 
@ianchanning let me know if that fixes your problem as well please.

**Comment by ianchanning** [comment]
@cooperq 0.1.4 is the version that is listed on https://addons.mozilla.org/en-US/firefox/addon/privacy-badger-firefox/

**Comment by ianchanning** [comment]
@cooperq That does fix it for me. Sorry, I should have mentioned the PB version - I'd just assumed that it was the latest.

**Comment by Klaaninka** [comment]
Thanks for your advice about getting the latest version of PB 0.2.5 from https://eff.org/pb. When I try to download it, I get this dialog: "The add-on could not be downloaded because of a connection failure on www.eff.org."
Any ideas?

**Comment by cooperq** [comment]
@Klaaninka do you have the Avast plugin installed? We have received reports that it can sometimes block the downloading of privacy badger.

**Comment by Klaaninka** [comment]
No Avast plugin. Bitdefender is my anti-virus, if that helps.

**Comment by cooperq** [comment]
Can you try disabling bitdefender and see if that fixes the problem?

**Comment by Klaaninka** [comment]
Thanks. I updated my operating system, rebooted into Safe Mode --there I was able to download the latest version and install it. The icon is back : )
