### ISSUE TITLE
Facebook Like button in 'Firefox Advance Cookie Manager' add-on's console isn't blocked.

### ISSUE THREAD

**Issue by cypherpunk** [EFForg/privacybadgerfirefox#291]
I just learned that the Firefox ShareMeNot add-on has been rolled into the Privacy Badger add-on.

I currently have both add-ons installed, but the Facebook Like button which appears on the Firefox 'Advance Cookie Manager' add-on does not appear to be blocked. The ShareMeNot add-on replaces social icons with its own icon on the webpage; I don't know what Privacy Badger does in order to indicate to the user that it is blocking social buttons. Again, I just learned that the ShareMeNot add-on has been rolled into EFF's Privacy Badger add-on.

**Comment by cooperq** [comment]
The share me not code only blocks like buttons that actually come from facebook. It is possible that advanced cookie manager has rolled their own facebook like button.
