### ISSUE TITLE
Can't sign petition.

### ISSUE THREAD

**Issue by Maxxxxxx** [EFForg/privacybadgerfirefox#292]
If I click on to the page from email and enter my zip, I can write my congressman.
With PB on, I only see "Loading...:.
With PB disabled, I got the letter that I wanted to sign.

I had disabled PB earlier and downloaded what I assume is the later beta version (?).
It seems that some of the 34 people who downloaded are having similar (you broke my website) complaints.  An hour ago, I composed a letter to you, then changed my mind - until this error.

Here: https://action.citizen.org/p/dia/action3/common/public/?action_KEY=12676

**Comment by cooperq** [comment]
When you click on the privacy badger icon what domains is privacy badger blocking? I suspect that it is blocking warehouse.salsalabs.com which may be needed for the page to work. Try dragging the slider for that to yellow or green and see if that fixes the problem. If so I will add it to the cookie block list.

**Comment by cooperq** [comment]
fixed in privacybadgerchrome@090d4760828821114f768ff1396ac24e1db4b7dd
