### ISSUE TITLE
Cannot disable via Add-ons Manager

### ISSUE THREAD

**Issue by anaran** [EFForg/privacybadgerfirefox#293]
Even though I have done so via the `Disable` button, even restarted Firefox (nightly, 38.0a1), I can still see

"GOT LOCATION CHANGE: myurl" progressListener.js:39

at works, also messages from utils.js.

**Comment by anaran** [comment]
Any news on this one?

**Comment by cooperq** [comment]
I suspect that this is a firefox bug. We shouldn't be able to do anything after the addon is disabled. I would report to mozilla.
