### ISSUE TITLE
Privacy Badger doesn't work on Firefox

### ISSUE THREAD

**Issue by moshpirit** [EFForg/privacybadgerfirefox#294]
I've just installed Privacy Badger on a Firefox 35.0.1 (Kubuntu 14.04, 64 bits) It has installed:
- Privacy Badger
- HTTPs everywhere
- Disconnect
- NoScript
- Adblock Edge
- Ubuntu Firefox Modifications
- Greasemonkey:
  - Diaspora AutoUpdater (Wai-Modus) 1.2.3

It show every cookie as green, even Facebook and Last.Fm ones.

**Comment by cooperq** [comment]
Privacy badger only blocks things that set a cookie, I suspect that your other blocking addons are blocking trackers like facebook and last.fm before privacy badger gets a chance too learn to block them.

**Comment by moshpirit** [comment]
I've disabled the rest of them and I still can't use it correctly. It's very weird because I use the same version of Firefox with all of these plugins excepting Ubuntu Firefox Modification and Adblock Edge, so I tried to disable them but the problem it's still there. (And yes, I rebooted the browser)

**Comment by cooperq** [comment]
Just give it some time, it learns over time what to block and if it is not blocking anything that means that the things are being blocked by your other addons!  I think the issue here is that you have so many addons that everything is being blocked before privacy badger gets a chance to see anything, so no worries, you are safe!

**Comment by moshpirit** [comment]
No, with e.g. last.fm, I can't see and navigate by the website without let some of these cookies track me, in this case, PB is not blocking anything and last.fm is tracking everything :(

**Comment by cooperq** [comment]
Okay I am a little confused about your problem I think. Are you saying that the problem is that you have to unblock certain trackers in privacy badger to get last.fm to work? Or are you saying privacy badger is not ever blocking anything?

**Comment by moshpirit** [comment]
In my browser I need to unblock some cookies to use comfortably last.fm but I suppose that it's the correct behaviour of PB. In the other hand in my friend's browser (with the extensions in the original note) doesn't block anything, even on Facebook, Twitter and Last.fm, so it allows all the cookies and that's the problem I'm reporting here.
Sorry if I didn't explain myself correctly.

**Comment by cooperq** [comment]
So privacy badger will never block first party cookies on a site. Facebook has to be able to set cookies on facebook.com to work. It will block facebook cookies on third party websites though. Can you send me a screenshot of privacy badger's settings on a website? Show me one where it is seeing but not blocking facebook?

**Comment by moshpirit** [comment]
Sure, I'll do it ASAIC, as I told you, this isn't my computer, I think I could do it this Saturday :)

**Comment by moshpirit** [comment]
Ok, I couldn't make the screenshot before but, with the last update it's solved! thanks! ;)
