### ISSUE TITLE
Images from picsee.net are blocked

### ISSUE THREAD

**Issue by anonsubmitter** [EFForg/privacybadgerfirefox#295]
Images from picsee.net are blocked. Changing picsee.net's blocking status from red to yellow will display the images.

Examples: https://www.google.com/#q=%5Bimg%5Dhttp:%2F%2Fpicsee.net+site:shaanig.com

**Comment by cooperq** [comment]
I'm not comfortable adding this too the white list since I can't find a privacy policy anywhere on their site. But I think this is a great case for why we need to improve the heuristic.

**Comment by anonsubmitter** [comment]
You could maybe ask them about their privacy policy via picsees@gmail.com or https://twitter.com/picsee_net
