### ISSUE TITLE
Privacy Badger prevents legitimate sh.st (short link generator) redirection

### ISSUE THREAD

**Issue by anonsubmitter** [EFForg/privacybadgerfirefox#296]
Go to one of these pages: https://www.google.com/#q=site:sh.st
Normally a countdown from five to zero would have begun in the upper right corner of the page and after that the user would be able to continue to the page the user wants to get to. At the moment Privacy Badger blocks that countdown. Changing "blocking status" for static.shorte.st from red to yellow fixes this.

**Comment by cooperq** [comment]
I'm not really comfortable adding this to the list either, for the same reasons as the last one you submitted. I think this is a great exapmle of a good domain for users to override on their own if they so choose.

**Comment by anonsubmitter** [comment]
Their privacy policy is here, in case that's what you were looking for: https://shorte.st/privacy
