### ISSUE TITLE
Privacy Badger blocks embedded tweets on kotaku.com

### ISSUE THREAD

**Issue by anonsubmitter** [EFForg/privacybadgerfirefox#299]
Privacy Badger blocks embedded tweets on kotaku.com. This can be fixed by changing "blocking status" from red to yellow for syndication.twitter.com.

Example: http://kotaku.com/nintendo-made-a-gamecube-controller-adapter-for-wii-u-1583342868

**Comment by cooperq** [comment]
Thanks, I will add syndication.twitter.com to the cookie block list.
