### ISSUE TITLE
"Trending" box on majorgeeks.com is blocked

### ISSUE THREAD

**Issue by anonsubmitter** [EFForg/privacybadgerfirefox#302]
The "Trending" box on http://www.majorgeeks.com/ is blocked by Privacy Badger. It is powered by AddThis, so changing blocking status from red to yellow for s7.addthis.com and q.addthis.com will fix this. Is it possible to only enable s7.addthis.com and q.addthis.com on majorgeeks.com and not any other sites?

**Comment by cooperq** [comment]
Unfortunately it is not currently possible the way that privacy badger is architected. I am also not interested in adding addthis to the cookie block list since they are a major tracker and they use browser fingerprinting.

**Comment by anonsubmitter** [comment]
Yeah, I suspected that.
