### ISSUE TITLE
Broken on latest nightly

### ISSUE THREAD

**Issue by titanous** [EFForg/privacybadgerfirefox#303]
I built 621062215d15f506bfa3c5ab98a8d8786968b37c (master) and am running nightly 38.0a1 (2015-02-19) (e10s off).

Privacy Badger doesn't block anything and the info popover just shows "Loading..."

**Comment by cypherpunk** [comment]
Same setup here. Add-on shows in the list, but all functionality is missing, and the icon has disappeared from my add-on bar.

**Comment by titanous** [comment]
@cooperq Any updates on this? I'd investigate but I know nothing about Firefox extensions.

**Comment by GRMrGecko** [comment]
I use Firefox Developer Edition, and it blocks things, I just can't get to the page to unlock anything. I can say unlock for this website, and I can say unblock all.

Here is my debug. I'll try checking out the source and see how PrivacyBadger with latest from github.
https://gist.github.com/GRMrGecko/0af050119d47d7c322b6

**Comment by GRMrGecko** [comment]
Same thing with the newest privacy badger and I cannot find out how to get it to log what console.log is giving so I cannot debug myself.

**Comment by cooperq** [comment]
@titanous @GRMrGecko can you build privacy badger from master and confirm that it now works on the latest nightly?

**Comment by titanous** [comment]
I've been running the patch from #323 for a few days now on Nightly with no issues. Thanks!

**Comment by shgysk8zer0** [comment]
I remember having seen something about Firefox having added a tracking-blocker of its own (though it is supposed to remain in perpetual alpha, never being enabled in a stable release), and I believe it was added in 38. Check `privacy.trackingprotection.enabled`.

I have no details or logs or anything to offer, and I see that there is a path where this is working, but I thought I might mention a possible conflict.

**Comment by pguth** [comment]
Privacy Badger just displays `Loading...` and seems to do nothing at all in FF 38.0a2.

![PB stuck loading](https://cloud.githubusercontent.com/assets/85259/6916482/ee59565c-d79c-11e4-914e-4f11c4f381b7.png)

**Comment by JJBocanegra** [comment]
I'm in the same situation that pguth but from more than a month now. I just unistalled it until a new version is released.
