### ISSUE TITLE
Privacy badger conflicts with Alientube

### ISSUE THREAD

**Issue by Davve37** [EFForg/privacybadgerfirefox#305]
I'm not 100% certain this is the case but I'm fairly certain. And it's probably not that much of a bug either but I was wondering if there's a work around for this. For those who might not know what Alientube is I'll tell you. It's an addon to firefox which replaces the youtube comments with comment form reddit where the video has been posted. No, the widget load but it never get's finished loading while privacy badger is activated. This is most inconvenient since I really like both addons. So, is there a fix to this?

**Comment by cooperq** [comment]
when alientube gets blocked you should be able to click the privacy badger icon and see that it is blocking an alientube.com domain, or something similar. Simply move that slider to yellow or green and it will be unblocked.
