### ISSUE TITLE
Non-free SHA1 implementation bundled

### ISSUE THREAD

**Issue by rathann** [EFForg/privacybadgerfirefox#306]
The SHA1 implementation bundled with Privacy Badger comes from http://www.webtoolkit.info/javascript-sha1.html . It seems to be licensed under CC-BY 2.0 UK with additional restrictions http://www.webtoolkit.info/license1 and hence is not considered free software (https://lists.fedoraproject.org/pipermail/legal/2014-October/002507.html). Please replace this non-free code with a free implementation, for example this MIT-licensed one: https://raw.githubusercontent.com/chrisveness/crypto/master/sha1.js (http://www.movable-type.co.uk/scripts/sha1.html).

**Comment by cooperq** [comment]
@rathann would you consider making a pull request with a commit replacing the sha1 library?

**Comment by jsha** [comment]
FYI there is a Firefox API you can use to call the native SHA1: https://github.com/EFForg/https-everywhere/blob/691be3b4bcb6540258ba895a037866ab48a87cca/src/components/ssl-observatory.js#L295 (example is MD5 but same is possible for SHA1).
