### ISSUE TITLE
Mozilla Addons page is out of date

### ISSUE THREAD

**Issue by avbop** [EFForg/privacybadgerfirefox#309]
The [Mozilla Addons page][1] is out of date (v0.1.4 < v0.2.5).

I'm running a small computer lab and using Firefox Sync to ease setup of Firefox on each machine. I installed the new version of Privacy Badger directly from the EFF website on the first machine I set up, but when I set up sync on the other machines Firefox installed the older version.

[1]: https://addons.mozilla.org/en-US/firefox/addon/privacy-badger-firefox/

**Comment by cooperq** [comment]
Bummer, that may be a bug in the way firefox works. Either way I definitely plan to update AMO but it is not an easy process unfortunately. I am working on it though!

**Comment by irvin** [comment]
Perhaps someone can help on updating AMO. You can gain privilege to people by clicking "[Manage Authors & License](https://addons.mozilla.org/en-US/developers/addon/privacy-badger-firefox/ownership)" and filling email, then he can help you doing the updating stuff.

**Comment by agilob** [comment]
PB is no longer available on AMO. Was it rejected?

**Comment by cooperq** [comment]
I removed the old version which was incompatible with the current version of firefox. The new version still has not been approved by the AMO moderators, so unfortunately it stiill will not be on AMO. You can still download it from https://eff.org/privacybadger though, which is the preferred method!

**Comment by jsha** [comment]
FYI HTTPS Everywhere now appears on AMO if you link directly to it (https://addons.mozilla.org/en-US/firefox/addon/https-everywhere/), but not if you search for it, which I assume is because it's uploaded but not yet moderator approved. I believe the visibility rules in that regard may have changed recently? Weird that PB doesn't also appear in pre-moderated state.

**Comment by cooperq** [comment]
Ah well it is not directly linkable because it was rejected again. Uploading another new version now.

**Comment by irvin** [comment]
![2015-04-30 13 53 08](https://cloud.githubusercontent.com/assets/165936/7407079/44af9006-ef40-11e4-9f21-402bbc6736f3.png)
We can mark the highest compatible version of Firefox for an exist addon, before new version passed review. We don't need to remove the old version resulting this missing addon problem

**Comment by cooperq** [comment]
All my old versions are disabled by mozilla now so we just have to wait until this one is approved. Meanwhile it can be found here: https://addons.mozilla.org/en-US/firefox/addon/privacy-badger-firefox/ but you still can't search for it until it gets reviewed.
