### ISSUE TITLE
Firefox finds much less trackers than Chrome

### ISSUE THREAD

**Issue by cemsbr** [EFForg/privacybadgerfirefox#310]
http://www.nytimes.com/pages/technology/index.html has 7 trackers in Firefox and 19 in Chromium.

**Comment by cemsbr** [comment]
It happens in many other domains, like aws.amazon.com: 4 in Firefox vs 6 in Chromium.

**Comment by senden9** [comment]
I got 19 Trackers on this Page with Firefox.

**Comment by cemsbr** [comment]
I stopped using the privacy badger, but I have just done the same test and I got 15 in Firefox and 16 in Chromium. The difference is not relevant anymore.

**Comment by cooperq** [comment]
This is probably because you do less browsing with one browser or the other, or one has had privacy badger installed longer than the other.
