### ISSUE TITLE
"Could not detect any tracking cookies" on every website

### ISSUE THREAD

**Issue by cypherpunk** [EFForg/privacybadgerfirefox#311]
When I visit any website and click the Privacy Badger button, I am told that PB "Could not detect any tracking cookies". This can't be true for every website I visit, including facebook and twitter.

**Comment by cooperq** [comment]
Are you running any other extensions? Particularly adblocking ones? Also what version of privacy badger and firefox?

**Comment by cypherpunk** [comment]
I am also running HTTPS Everywhere, that is it. PB version 0.2.5 and Firefox version 36. Because I've never used the counter, I'm not sure when exactly it started not detecting anything but it was definitely working last year.

**Comment by Snapy** [comment]
I had a similar issuewith a fresh install. It was always showing a "Loading..." message where there should have been trackers. Disabling and re-enabling all preferences did the trick. Hopes this helps.

**Comment by KommX** [comment]
I have the same problem.

**Comment by cooperq** [comment]
@Snapy which preferences did you disable?
@KommX what browser version, privacy badger version, and other extensions?

**Comment by Snapy** [comment]
@cooperq I disabled (and re-enabled) all of them one by one. Hope this helps.

**Comment by KommX** [comment]
I don't have this problem anymore. But I don't know what changed.

**Comment by billmurphy5th** [comment]
I just ran into the "Loading..." issue with a fresh install of privacy badger.  Manually disabling it and re-enabling it fixed the issue, it seems to be working fine now.  I tried disabling and re-enabling the preferences first but that didn't work for me.  I'm using Firefox 36.0.4, OpenSUSE Tumbleweed, and privacy badger 0.2.5.  My other extensions are Clearly 10.2.1.7, Evernote Web Clipper 5.9.1, HTTPS Everywhere 5.0.1, Lastpass 3.1.1, openSUSE Firefox Extensions 1.0.2, and Reddit Enhancement Suite 4.5.4

**Comment by BobAlice000** [comment]
This. On every website it cannot detect any trackers. I know there are because it blocked them before. Either the auto-update caused a borken version to be loaded or this is a previously un-triggered bug. The only new thing I did was - for a single site, I utilized, for the first time, disable for this page. 

After I did that, PB was hosed across the board. All sites reporting "no trackers" . Not only is there no way to re-enable "no tracking" for the site I enabled it on, (feature request I guess (perhaps this is just another aspect if PB having broken just then and there IS a way to do so??)  but from then on, yeah, everything is reporting no trackers. 

This PB is best in class for blocking trackers. Just for the record I would gladly pay like 5 or 10 bucks for it. I know open source free as in beer and what not but a NON-PAYPAL donation link along side it might goa  long way to funding dev cycles needed to sustain it, which is something I want to see....my2 cents.

**Comment by cooperq** [comment]
@BobAlice000 and anyone else still having this problem, can you try it with the latest version of privacy badger - 0.2.6? You can get it here: https://www.eff.org/privacybadger  
Please let me know if that fixes the problem. 

Also @BobAlice000 do you have E10S turned on or anything like that?

**Comment by billmurphy5th** [comment]
A fresh install of 0.2.6 looks like it's correctly blocking trackers on install.  Thanks for the great work!

**Comment by cypherpunk** [comment]
I am not OP, but the problem has happened to me twice.  Both times were after Firefox automatically upgraded itself, most recently to Firefox 37.0.1.  This time, trackers reappeared after disabling and enabling either Automatic Blocking or Social Widget Replacement.  I did not notice the trackers being listed until after re-enabling Social Widget Replacement, but it may have happened before then.  I closed the Addons tab after each change in state of each single checkbox, but I don't know if that would have mattered.

However, they had turned green despite not having touched the sliders.  I thought there might still be something wrong, so I reinstalled PB 0.2.6 over my 0.2.6 without closing Firefox.  Ads continued to appear since the sliders were green, so I restarted Firefox hoping that would re-enable the old slider settings.  Trackers were green after restarting but changed to red and yellow after a few site visits, so I guess the data was reset.

The first time this happened when an earlier version of Firefox updated, I think I only toggled each of the checkbox options and restarted Firefox before I noticed the sliders again.

I had the following extensions loaded when FF updated and tracker sliders disappeared: Privacy Badger 0.2.6, about:addons-memory 10, BetterPrivacy 1.68, Copy Pure Text 2.0.5, Firebug 2.0.9, FxIF 0.4.8.1, HTTPS-Everywhere 5.0.1, Image Search Options 2.0.2, NoScript 2.6.9.21, Passive Cache 1.3b, Self-Destructing Cookies 0.4.7

By the way, E10S is on by default in Firefox 37.0.1

As for now, I guess I won't know if the bug was fixed until Firefox updates again.

**Comment by cypherpunk** [comment]
Hello I have the same problem. At first it works fine but after visiting certain websites the problem occurs. Afterwards it doesn't detect trackers on any website.

**Comment by SwartzCr** [comment]
It's likely that privacy badger is encountering an error when trying to save its heuristic data
If this happens again could you look at the console for the app (either by inspecting one of the dropdown windows, or looking at the 'backgroundpage.js' scope) and share what you see there?
That would be immensely helpful

**Comment by BobAlice000** [comment]
Just saw this now.
 Fixed,- yes.
E10S on? - no.

let me know if I can be of any further assistance.

 
On Thursday, April 2, 2015 2:10 PM, Cooper Quintin [Masked] 
<FWD_u2Ma7DRx@opayq.com> wrote:
 
> BobAlice000 <https://github.com/BobAlice000> do you have E10S 
> turned on or anything like that?
> 
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/EFForg/privacybadgerfirefox/issues/311#issuecomment-89045417>.[ALFK09Ej2OjBU5sIJNsSU68QQr8iyjovks5n7afZgaJpZM4Dnpne.gif]
-- 
Take back your privacy. Switch to www.StartMail.com

**Comment by cooperq** [comment]
Glad to hear that it is fixed! I think it was simply a problem of having an out of date version.
