### ISSUE TITLE
FF36.0 - Moving PB icon to menu will cause menu to disappear when opened

### ISSUE THREAD

**Issue by thrnz** [EFForg/privacybadgerfirefox#312]
In FireFox 36.0, when the PrivacyBadger icon has been moved to the menu, the menu will disappear almost immediately after being opened. Clicking the menu button a second time will then only show the bottom most menu buttons. Moving the icon back to the toolbar returns the menu behaviour to normal. I have noticed this behaviour on three separate machines.

**Comment by cooperq** [comment]
duplicate of #277
