### ISSUE TITLE
PB breaks virustotal.com

### ISSUE THREAD

**Issue by KommX** [EFForg/privacybadgerfirefox#313]
PB 2014.9.16 under Chrome Version 42.0.2311.11 dev (64-bit) on Ubuntu 14.10 breaks virustotal.com.

But I couldn't reproduce on my windows machine, because there PB doesn't list the host it finds under Ubuntu at all.

![screenshot from 2015-03-03 09 04 28](https://cloud.githubusercontent.com/assets/7859245/6458539/d657db42-c184-11e4-9dc8-e261f27b9cd2.png)

**Comment by cooperq** [comment]
I've added appspot.com to the cookieblock list to fix this issue. As a workaround for now you can click the privacy badger icon and drag the appspot slier from red to yellow or green.
