### ISSUE TITLE
ToggleButton is not defined

### ISSUE THREAD

**Issue by ermingol** [EFForg/privacybadgerfirefox#314]
![screenshot from 2015-03-03 18 32 46](https://cloud.githubusercontent.com/assets/11158653/6468195/bdcb2dd2-c1d3-11e4-826b-7b672cf77b86.png)
I have a fresh profile in Firefox on Ubuntu 14.04 LTS (Firefox 36.0 and "Mozilla Firefox for Ubuntu canonical - 1.0") and get no Privacy Badger icon when installing the addon in Firefox. In the console I get the following error message

console.error: privacybadgerfirefox: 
  Message: ReferenceError: ToggleButton is not defined
  Stack:
    @resource://jid1-mnnxcxisbpnsxq-at-jetpack/privacybadgerfirefox/lib/ui.js:114:3
CuddlefishLoader/options<.load@resource://gre/modules/commonjs/sdk/loader/cuddlefish.js:129:18
@resource://jid1-mnnxcxisbpnsxq-at-jetpack/privacybadgerfirefox/lib/contentPolicy.js:15:25
CuddlefishLoader/options<.load@resource://gre/modules/commonjs/sdk/loader/cuddlefish.js:129:18
@resource://jid1-mnnxcxisbpnsxq-at-jetpack/privacybadgerfirefox/lib/main.js:8:23
CuddlefishLoader/options<.load@resource://gre/modules/commonjs/sdk/loader/cuddlefish.js:129:18
run@resource://gre/modules/commonjs/sdk/addon/runner.js:145:19
startup/</<@resource://gre/modules/commonjs/sdk/addon/runner.js:86:7
Handler.prototype.process@resource://gre/modules/Promise-backend.js:870:23
this.PromiseWalker.walkerLoop@resource://gre/modules/Promise-backend.js:749:7
this.PromiseWalker.scheduleWalkerLoop/<@resource://gre/modules/Promise-backend.js:691:37

**Comment by cooperq** [comment]
Please make sure that you have the latest version of the addon installed
from https://eff.org/pb

**Comment by ermingol** [comment]
I have installed it now. What is good is that I now get the badger icon. What is bad is that it does not detect any trackers even on sites I know are full of them (like www.di.se or www.aftonbladet.se). :-(

/John

--
John Olsson
Ericsson AB
BSC/BSS System Management
----------------------------------------
Tel: +46 (0)10 7114 666
Mobile: +46 (0)730 43 53 44
----------------------------------------
Sent from Moxier Mail
(http://www.moxier.com)


----- Original Message -----

**Comment by cypherpunk** [comment]
I am having a similar issue. PB is not detecting any trackers on websites that are full of them e.g. Facebook and Twitter.

**Comment by ermingol** [comment]
Yesterday I found that restarting Firefox (actually cold starting the computer) got Privacy Badger to work again as expected. Now it detects trackers and adds a counter of how many it blocked to the icon. :-)


----- Original Message -----

**Comment by cooperq** [comment]
Great, I am going to close this issue then.
