### ISSUE TITLE
 Going to Walmart  site crashes Firefox browser

### ISSUE THREAD

**Issue by Pemican** [EFForg/privacybadgerfirefox#318]
The few times I have gone to a Walmart's page, Firefox freezes up horribly and have to restart. Don't know what to do because cannot access the badger tab to adjust  sliders because just going to a Walmart page  freezes browser  so badly .  anyone else having this problem?

**Comment by cooperq** [comment]
I am unable to reproduce this issue. Please be sure you are using the latest version of privacy badger from https://www.eff.org/pb
Also please try disabling any other browser extensions to make sure they are not responsible.
