### ISSUE TITLE
Mailchimp "View in browser" newsletter

### ISSUE THREAD

**Issue by aguatye** [EFForg/privacybadgerfirefox#321]
Just working on a Mailchimp newsletter template and when it is viewed in Firefox - all the images hosted by Mailchimp are not showing, after changing the disable for this page setting in privacybadgerfirefox - the images then showed... 

I'm guessing that privacybadgerfirefox blocked the tracking image from mailchimp, but then blocked all the other images hosted on the same server! 

Is there a way around this?

**Comment by cooperq** [comment]
You can click the privacy badger icon and move the slider for mailchimp from red to yellow or green. That will unblock mailchimp.
