### ISSUE TITLE
Falsely reporting Google Tracker present on Blur (abine - Do NOt Track Me) user's personal email pages

### ISSUE THREAD

**Issue by BobAlice000** [EFForg/privacybadgerfirefox#325]
Have Blur Account. When logged into  Blur as a user and using any of the private screens which only I have access to of my account, Privacy Badger reports there is one tracker present and it belongs to www.google.com

Contacted Blur. Was reassured by hands-on engineer  that this was false- no such tracker is present. This, and the presence of such a tracker, if it were known to Blur,  would be a massive violation of the stated privacy policies of Blur , makes it much more likely that Privacy badger is reporting falsely. Either that of Privacy Badger is detecting something Blur is unaware of and needs to be aware of. 

If you can look into why this might be alerting to a Google tracker - it doesn't say cookie, just "tracker" - we could figure out what is going on. Blur is looking into at this time also. 

FF 3.6.04 
Win 7 64
Privacy Badger downloaded mid March 2015. No versioning information presented by Privacy Badger.

Contact me if you need any more information.

Thank you.

**Comment by cooperq** [comment]
From my observation blur makes requests to the following third parties:
fonts.googleapis.com
fonts.gstatic.com
bootstrapcdn.com
google.com
amazonaws.com

The google.com requests definitely get all of your google.com cookies,
which includes tracking cookies. The other requests do not appear to be
sending any cookies, so all they will get is your IP address and the
fact that you visited dnt.abine.com. I think that the engineer you
talked to is mistaken. Privacy Badger is working as expected, google is
setting tracking cookies when you visit dnt.abine.com.

**Comment by BobAlice000** [comment]
Can I ask you about the methodology you used to determine this information?  Thank you!

**Comment by BobAlice000** [comment]
Hey cooperq,

 Thanks for the reply. Can I ask about the methodology you used to 
determine this?

Sincerely,
 Bob
On Monday, March 23, 2015 2:17 PM, Cooper Quintin [Masked] 
<FWD_NYxWU3eq@opayq.com> wrote:
 
> 
> 
> From my observation blur makes requests to the following third 
> parties:
> fonts.googleapis.com
> fonts.gstatic.com
> bootstrapcdn.com
> google.com
> amazonaws.com
> 
> The google.com requests definitely get all of your google.com 
> cookies,
> which includes tracking cookies. The other requests do not appear to 
> be
> sending any cookies, so all they will get is your IP address and the
> fact that you visited dnt.abine.com. I think that the engineer you
> talked to is mistaken. Privacy Badger is working as expected, google 
> is
> setting tracking cookies when you visit dnt.abine.com.
> 
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/EFForg/privacybadgerfirefox/issues/325#issuecomment-85201319>.[ALFK0191V36qu3jwuNzvDnEnbgGQY1xiks5n4HpPgaJpZM4DzVpV.gif]
-- 
Take back your privacy. Switch to www.StartMail.com

**Comment by cooperq** [comment]
My methodology was to look at the network requests when this page was loaded using the chrome developer console.

**Comment by BobAlice000** [comment]
Thanks cooperq. I am a total neophyte and you showed me something useful.
