### ISSUE TITLE
Change website to inform that pb does not work on firefox for android.

### ISSUE THREAD

**Issue by suidobashi** [EFForg/privacybadgerfirefox#326]
Hi,

Trying to install from the button on https://www.eff.org/privacybadger using Firefox 36.0.4 on a Nexus 7 running Android 5.0.2, the add-on downloads but then fails with a message "Privacy Badger could not be installed because it is not compatible with Firefox 36.0.4".

**Comment by cooperq** [comment]
Privacy Badger does not currently support firefox for android. We should update the website to reflect this. Android support is being tracked in #271

**Comment by cooperq** [comment]
Fixed.
