### ISSUE TITLE
jQuery getJSON silently fails with PB active

### ISSUE THREAD

**Issue by magnusmanske** [EFForg/privacybadgerfirefox#328]
Observed in FF 33-37 on Mac. $.getJSON does not execute, nor do fail() etc. trigger.

Example URL:
https://tools.wmflabs.org/autolist/?language=en&project=wikipedia&category=&depth=12&wdq=claim%5B106%5D%20and%20noclaim%5B106%3A(tree%5B13516667%5D%5B%5D%5B31%2C279%5D)%5D&mode=undefined&statementlist=&run=Run&label_contains=&label_contains_not=&chunk_size=10000

The list of "Q" items should load labels as soon as one scrolls the list (not the page!). But the label loading does not happen. Deactivate PB, all works fine.

**Comment by cooperq** [comment]
It seems like this was happnening because wikidata was being blocked by privacy badger. I have added wikidata.org to the greylist. As a temporary workaround you can move the slider for wikidata.org from red to green in privacy badger.
