### ISSUE TITLE
No way to enable for a site after diabling

### ISSUE THREAD

**Issue by BobAlice000** [EFForg/privacybadgerfirefox#331]
Disabled blcking trackers for one site in order to get by registration process.Now I have no way to enable blocking trackers for this site anymore. There is no option to enable blocking again.

**Comment by cooperq** [comment]
Clicking the privacy badger icon should re-enable blocking again for a given site. Also please make sure that you are running the latest version of privacy badger from https://eff.org/privacybadger

**Comment by SwartzCr** [comment]
closing this issue, feel free to comment if you're still having problems
