### ISSUE TITLE
PB breaks eventbrite.com

### ISSUE THREAD

**Issue by chrish42** [EFForg/privacybadgerfirefox#336]
PB ends up blocking everything from ebmedia.eventbrite.com. This breaks the rendering of EventBrite. Switching PB to block cookies only for ebmedia makes the EventBrite website render properly again.

**Comment by cooperq** [comment]
This definitely sounds like a bug, *.eventbrite.com should never be blocked on eventbrite.com. Can you send me a screenshot of the page with the privacy badger menu open?

**Comment by chrish42** [comment]
What's happening is that if you're not in the US and are logged-in, 
Eventbrite redirects you to www.eventbrite.YOUR-COUNTRY'S-TLD. But the 
web page still uses and loads resources from ebmedia.eventbrite.com.

**Comment by chrish42** [comment]
![capture d ecran 2015-04-22 a 20 58 32](https://cloud.githubusercontent.com/assets/632858/7288613/766c1880-e932-11e4-8270-3395eda29972.png)

**Comment by cooperq** [comment]
Okay I will add ebmedia.eventbrite.com to the cookie block list which should fix this problem. You can fix it right now by dragging the slider for ebmedia.eventbrite.com to yellow or green.
