### ISSUE TITLE
PB could use more efficient uBlock instead of AdBlock as a base

### ISSUE THREAD

**Issue by chrish42** [EFForg/privacybadgerfirefox#337]
I think I remember reading that PB uses the AdBlock code to do the actual blocking. I've switched from AdBlock to the new uBlock because the latter is much more efficient in terms of CPU and memory. It'd be nice if PB could switch to uBlock's more efficient way of blocking http requests, etc. Not sure how much work that involves, though.

**Comment by xur86x** [comment]
This is a good idea. From what I know, AdGuard is also pretty efficient, but I'm not sure if it compares to uBlock. Both are open-source.

**Comment by cooperq** [comment]
firefox doesn't use ABP as a base (just some utility libraries), chrome does but I would rather remove a third party dependency entirely than try to replace ABP with µblock or anything else.
