### ISSUE TITLE
Privacy Badger Chrome forgets settings after a few weeks - cannot enable tracking again

### ISSUE THREAD

**Issue by poppyuser** [EFForg/privacybadgerfirefox#338]
I installed Privacy Badger and loved it for a few weeks. I blocked cookies or sites just fine.

But after a few weeks I noticed it stopped working. All tracking would show as green. Clicking on yellow or red would not work (would not be remembered).

I ended up having to remove the plugin and reinstall.
It worked again perfectly but only for a few weeks. Today again I see everything is green. it will not 'remember' the settings if I change anything to yellow or red.

**Comment by PiRSquared17** [comment]
Hi, please move this bug report to https://github.com/EFForg/privacybadgerchrome unless it applies to Privacy Badger Firefox too. Thanks for reporting it.

**Comment by poppyuser** [comment]
This issue was moved to EFForg/privacybadgerchrome#370
