### ISSUE TITLE
Flattr is blocked too aggressively

### ISSUE THREAD

**Issue by blobgo** [EFForg/privacybadgerfirefox#339]
In the [2-Klicks tool of heise] (http://www.heise.de/ct/artikel/2-Klicks-fuer-mehr-Datenschutz-1333879.html) (German site) which is for example used [here] (https://netzpolitik.org/2015/bundesregierung-geheime-nebenabrede-zur-vorratsdatenspeicherung-ist-nicht-geheim-nur-nicht-oeffentlich/) (German site) Privacy Badger is blocking Flattr to aggressively.
All other services (Twitter, Google+ and co) are (after enabling) only cookie blocked, while Flattr is blocked completely.

Here is a screenshot. The marked part
![flattrblocking](https://cloud.githubusercontent.com/assets/12105354/7441094/82b2ab7e-f0d8-11e4-8b3f-6159e237e7bf.png)

**Comment by cooperq** [comment]
thanks for bringing this to our attention. I have added flattr to the cookieblock list.
