### ISSUE TITLE
Cannot change preferences with Firefox

### ISSUE THREAD

**Issue by tkoenig1** [EFForg/privacybadgerfirefox#341]
When opening the list of tracked sites, I cannot grab the sliders and change the preferences.

This is with Firefox 37.0.2 under Linux/x86_64 and version 0.2.6.1.

**Comment by cooperq** [comment]
Indeed dragging the sliders seems to be broken! However as a workaround for now, clicking in the black box behind the slider will move it to the desired place.

**Comment by cooperq** [comment]
fixed in #364
