### ISSUE TITLE
Unable to checkout with merchants who use cardinalcommerce

### ISSUE THREAD

**Issue by chris00001** [EFForg/privacybadgerfirefox#343]
I'm glad to have Privacy Badger installed, but am noticing a problem, and only recently figured out what is causing it. I was running into an issue with Newegg where I could not checkout-or at least you wouldn't get a confirmation page. Today I noticed the same thing with Tigerdirect. The problem has something to do with cardinalcommerce which is basically a fraud prevention verification service. When a user checks out with a credit card that has 3d secure support merchants direct users to cardinalcommerce behind the scenes and are presented with what I believe is there banks website. I refuse to get a card which supports this so I haven't had to do it, but even users without such cards are forced through this portal (it appears to just redirect back to the merchants site if 3d secure is not supported by the credit card). However that doesn't happen with privacy badger installed. 

I'm not sure how this might be solved, but I thought I'd bring it to the developers attention.

**Comment by cooperq** [comment]
can you give me the exact domain that is being blocked? Or a screenshot of the privacy badger menu on the page that is being broken?

**Comment by chris00001** [comment]
Interesting. So I went to checkout at a site that used cardinalcommerce and I didn't run into a problem. I first made a purchase using firefox + privacy badger (where privacy badger had the domain excluded from being blocked) and I saw the xxx.cardinalcommerce.com (which redirects back to the merchant so you hardly see it). In any event in order to test this under vanilla conditions where privacy badger wasn't blocking I renamed my .mozilla/firefox configuration folder, started firefox, and installed the latest privacy badger.  This time however I didn't see the cardinalcommerce domain and didn't get stuck (that is where I don't get redirected back to the merchants site- which then would normally show an invoice). So ultimately I'm not sure if it doesn't do this every time or if something was fixed. 

I suspect it's this sub-domain specifically that is the problem (I know its short, the domain, cardinalcommerce.com is definitely part of it):

0eaf.cardinalcommerce.com

As I don't see a way to look through the list of domains on the permitted list it makes it a bit more difficult to just look up what domain I added to the authorized list.

**Comment by cooperq** [comment]
fixed in privacybadgerchrome@5d9f08998f2c951c99863105eb69a13b3e01f182

**Comment by chris00001** [comment]
Awesome!

I just want to give a big thank you for fixing this. The work your doing is extremely valuable.

**Comment by cooperq** [comment]
Thank you! Bug reports are valuable too! I can't fix things without dedicated users letting me know :)
