### ISSUE TITLE
move away from github / gitorious

### ISSUE THREAD

**Issue by chris00001** [EFForg/privacybadgerfirefox#344]
What's wrong with GitHub?

The company is hostile users and there freedoms and privacy. GitHub itself is proprietary software. Tim, the CEO, reasons it's for business. Tim really likes to talk about freedom, but makes the following claims about the GPLv2/3: The GPL is not focused on freedom. It's too long. Too many restrictions. -- Tom Preston-Werner OSCON2013

Continuing on "Notice that everything we keep closed has specific business value that could be compromised by giving it away to our competitors". -- Tom Preston-Werner's blog

GitHub simply uses Free Software for its own benefit, releasing source code under a free license only when suited to it's business goals; they are quite happy to violate the rights of their users, for profit. 

The opinions expressed by Tom Preston-Werner of GitHub are incompatible with the users and developers of privacy badger. Users and developers are strongly encouraged not to use GitHub, for any of their projects.

Please don't use gitorious either. The company has completely sold out its users to a company whose main business model is proprietary software. Gitorious is now owned by GitLab. GitLab is essentially the same as GitHub; there is a free (libre) version of GitLab, but this is bait-and-switch for their so-called enterprise version which is proprietary software.  The GitLab site itself also runs on a proprietary version of GitLab. GitLab has the same rotten attitude as GitHub when it comes to free software. 

Where should privacy badger move to?

We should host our own repository: http://git-scm.com/doc

You can use a front end like: gitweb http://git-scm.com/book/en/v2/Git-on-the-Server-GitWeb

For code review, you can use an IRC channel, mailing lists and other methods that allow mass collaboration. 

Also Jason Self, a well known free software advocate, has made some suggestions here as well:

https://jxself.org/goodbye-gitorious.shtml

**Comment by cooperq** [comment]
The problem with this is that all of our issue queue and contributors are already on github. Moving this project off of github would kill a lot of momentum and be a lot of work that I am not willing to take on.
