### ISSUE TITLE
The PlayStation store (store.playstation.com) does not load when PB is enabled.

### ISSUE THREAD

**Issue by fxmsk** [EFForg/privacybadgerfirefox#348]
Issue:
The PlayStation store becomes stuck on the initial loading screen when Privacy Badger is enabled. Only tested on latest and previews OSX (10.10.3) and Firefox (38.0.1) builds so far.

Steps to reproduce:
1. Install Privacy Badger on Firefox browser.
2. Go to https://store.playstation.com or https://store.sonyentertainmentnetwork.com
3. Disable Privacy Badger, quit and reopen the browser, then try the links again.

Result:
The page loads the initial PlayStation graphic and "Loading..." text, but does not transition to storefront when PB is enabled. Site loads normally when Privacy Badger is disabled.

Notes:
* Other add-ons such as NoScript, Disconnect.me, HTTPS-Everywhere, and uBlock do not interfere with loading the site. Only PB causes the issue.
* Enabling / Disabling options within the Privacy Badger settings ("Automatic blocking enabled", "Social widget replacement enabled") have no effect on making the site load.
* This issue has been present on previous versions of OSX and Firefox.
* The site formerly loaded normally with previous versions of PB enabled.

Configuration:
MacBookPro8,2; Intel Core i7; 2 GHz; Mac 10.10.3; Firefox 38.0.1
Privacy Badger 0.2.6

![screen shot 2015-05-15 at 1 54 56 pm](https://cloud.githubusercontent.com/assets/12454687/7646653/063ec1f4-fb0a-11e4-975e-8f4fb91b9070.png)

**Comment by fxmsk** [comment]
Well, I just educated myself on how Privacy Badger actually works. Site loads when overriding the automatic blocking settings (by changing the red slider to green). So I guess it's working as intended?

**Comment by cooperq** [comment]
@fxmsk correct! Which slider did you end up moving to green to get the store to load?

**Comment by fxmsk** [comment]
I had to allow both:

auth.api.sonyentertainmentnetwork.com
cdn-a.sonyentertainmentnetwork.com

**Comment by cooperq** [comment]
thanks! I have added these both to the cookie block list, this will fix the problem for future privacy badger users.
