### ISSUE TITLE
Privacy Badger breaks stylesheet for Python's Pip Doc

### ISSUE THREAD

**Issue by chrish42** [EFForg/privacybadgerfirefox#351]
Accessing the pip doc webpage (https://pip.pypa.io/en/latest/user_guide.html) with Privacy Badger enabled results in a site rendered without CSS. This is because Privacy Badger blocks media.readthedocs.org completely. Changing that to "block cookies only" get the site rendering correctly again.

**Comment by cooperq** [comment]
Ah yes, this appears to happen if you have an account with readthedocs and then visit docs for multiple projects (on multiple domains). This probably wont ever happen for most people but I have added the site to the whitelist anyway.
