### ISSUE TITLE
update FAQ to explain how Privacy Badger interacts with other extensions

### ISSUE THREAD

**Issue by cypherpunk** [EFForg/privacybadgerfirefox#356]
The FAQ page (https://www.eff.org/privacybadger) does not mention how it interacts with other Firefox extensions.  (I'm particularly interested in how it behaves with the Ghostery extension.)

I'd recommend placing the answer to this question directly after the FAQ entitled "How is Privacy Badger different to Disconnect, Adblock Plus, Ghostery, and other blocking extensions?"

Not having a direct answer to this question means I didn't try Privacy Badger because I'm familiar with my existing setup and I know it works - although I share the EFF's concerns ("business models that we weren't entirely comfortable with").

**Comment by cooperq** [comment]
added
