### ISSUE TITLE
Yahoo search blocked at Ecosia

### ISSUE THREAD

**Issue by blobgo** [EFForg/privacybadgerfirefox#363]
The search from [Ecosia] (https://www.ecosia.org) isn't working as Yahoo is completely blocked there.
The problem is that Ecosia [gets there search results from Yahoo](https://www.ecosia.org/faq#200), so it's not that good that Privacy Badger blocks it's search results.

**Comment by cooperq** [comment]
Thanks for bringing this to our attention. I have fixed it in privacybadgerchrome@25a19c1a70004aa0cd3ed58e07fd5d4b6031fa6e
