### ISSUE TITLE
Breaks CSS on The Pirate Bay

### ISSUE THREAD

**Issue by nyuszika7h** [EFForg/privacybadgerfirefox#368]
Privacy Badger blocks `piratebay.org`, which breaks the CSS on The Pirate Bay.

**Comment by cooperq** [comment]
this is weird, afaict piratebay.org doesn't set any cookies. I'm curious how you got a cookie attached to that domain. Can you find the cookie for piratebay.org and tell me what the value is? Also you, @amandabee

**Comment by nyuszika7h** [comment]
It blocks the connection, it's not about cookies.

**Comment by cooperq** [comment]
yes, I understand. But I am wondering what would cause it to block thepiratebay.org in the first place. Privacy Badger should only block a third party domain when it is setting cookies. Can you tell me if there are any cookies set for thepiratebay.org on the pirate bay website?

**Comment by nyuszika7h** [comment]
```
__cfduid=debd35bc4f54e09fb5c498fd3e204350c1435183511; expires=Thu, 23-Jun-16 22:05:11 GMT; path=/; domain=.piratebay.org; HttpOnly
```

**Comment by cooperq** [comment]
interesting, piratebay.org doesn't try to set a cookie for me, but it might be because you have logged in or something. Either way I will add piratebay.org to the cookie block list.

**Comment by nyuszika7h** [comment]
For the record, I wasn't logged in (I don't even have an account). That's a CloudFlare cookie that's used on every site using CF. Related: #472

**Comment by cooperq** [comment]
I guess we should add thepiratebay.org to the cookie block list, but I agree this does point at the larger need to do something about cloudflare.

**Comment by nyuszika7h** [comment]
I thought you already added piratebay.org. I don't think you need to add **the**piratebay.org, there isn't a request made to that as far as I can see, that just redirects to one of their alternative domains.

(I commented because something reminded me of the issue – TPB didn't suddenly break again, I have a local override anyway.)

**Comment by cooperq** [comment]
Ah, so I did! Thanks for reminding me :smile: 
I guess this issue is covered by #472 then.

**Comment by nyuszika7h** [comment]
(Well, I don't know where Privacy Badger gets its list from, but only the Chrome repo's cookie block list seems to be actively updated.)

**Comment by cooperq** [comment]
privacy badger downloads the list from eff.org 
I use the chrome one as the canonical cookie block list, but firefox and chrome use the same on from eff.
