### ISSUE TITLE
http://gfycat.com/ seems to use tracking cookies, what can I do about that?

### ISSUE THREAD

**Issue by Konstamokh** [EFForg/privacybadgerfirefox#373]
I know this is not the right place for this and you can close it if you mind. I thought making them aware of it by writing an email would be the right thing to do, but I can't find a way to contact them on the site.

**Comment by SwartzCr** [comment]
that is a shame, though as you mentioned there's not much that we can be doing about it. Hopefully Privacy Badger is blocking their cookies as intended, and if you run into problems where the content is getting blocked of course you can manually move their slider to yellow, allowing requests but not allowing cookies.
If you do manage to get in touch with them, you should encourage them to honor EFFs DNT policy which would have privacy badger allow their requests and make sure that they are legally bound to handle the data they collect responsibly
