### ISSUE TITLE
Field reporting button sends multiple times

### ISSUE THREAD

**Issue by SwartzCr** [EFForg/privacybadgerfirefox#379]
after an error has been sent subsequent error reports send the number of times that it has been clicked over all
so on the first report it makes 1 request, on the second it makes 3(?!), on the third it makes 4, etc.
I have no idea what this is, but it might be possible to fix this by setting a lock that gets released on a status report back from the server

**Comment by cooperq** [comment]
I had the same problem with the options link click handler. I can't
remember how I solved it now, but I suspect its the exact same thing. I
will look into it.

**Comment by SwartzCr** [comment]
this might also be why the overlay is only triggering every other time you open the pop-up
