### ISSUE TITLE
Blocks CSS on Yelp

### ISSUE THREAD

**Issue by amandabee** [EFForg/privacybadgerfirefox#386]
(and [Pirate Bay](https://github.com/EFForg/privacybadgerfirefox/issues/368) but you know about that) 

It would be handy if there as some information about what is happening under the hood. If, as a user, I could see (for instance) what was blocked from s3-media4.fl.yelpcdn.com and why.

**Comment by cooperq** [comment]
thanks @amandabee I will add yelpcdn.com to the cookieblock list. I agree that it would be nice to add some way for the user to see what has been blocked from a domain and why that domain has been blocked, but I'm not really sure where to put this in the UI. I feel like the popup already has about everything it can handle and is pretty crowded. Maybe in the options page?

**Comment by amandabee** [comment]
The way I'd expect to get more info is from clicking through on "Blocked piratebay.org" 

![piratebay](https://cloud.githubusercontent.com/assets/150791/8360525/1f55d47e-1b22-11e5-96cf-1d71a6fbf576.png)

**Comment by cooperq** [comment]
Hmm, that seems like a reasonable place to put it, I think we should make that suggestion a seperate issue though. For now I have added both piratebay.org and yelpcdn.com to the cookieblock list. To fix it immediately you can drag the slider for priatebay.org and yelpcdn.com from red to yellow.
