### ISSUE TITLE
Broken Youtube generating annotations and CC for new uploaded video

### ISSUE THREAD

**Issue by Learn-Digital-Audio** [EFForg/privacybadgerfirefox#387]
I am 99% certain that when trying to add CC and annotations to my new Youtube video Privacy Badger stopped it working.

Upload a video, go to add annotations, import the text and then publish. Youtube keeps saying come back in a few mins.. it never works, even the next day. Go to annotation and you get a blank screen where the video is and you can't add any.

Had to switch off Badger, delete cookies called 'youtube' and Youtube still broken for CC and annotations. Had to finish the job on Chrome.

I have disabled the badger for now. Would be great if there was a news section for this plugin, is it going to be finished and released soon?! It is almost great, please hurry and release it properly! :+1:

**Comment by cooperq** [comment]
Seems like we need to unblock googlevideo.com

**Comment by cooperq** [comment]
I have added googlevideo.com to the cookieblock list which should fix this problem. Thanks for using privacy badger! For now you can re-enable privacy badger and on the video edit page click the privacy badger icon and move the sliders for all googlevideo.com domains from red to yellow or green.
