### ISSUE TITLE
Not blocking d.adxcore.com nor l.adxcore.com ?

### ISSUE THREAD

**Issue by antistress** [EFForg/privacybadgerfirefox#396]
For example on http://uplea.com/dl/EDD6C54DD6AAC09 (click on "free download" if needed), privacybadger is not blocking d.adxcore.com nor l.adxcore.com (note that blocking the 1st one leads to block the 2nd one) whereas I'm pretty sure they are 3rd party trackers

Thanks

(label should be site-bug but I don't know how to set it)

**Comment by cooperq** [comment]
This is probably because privacy badger hasn't seen adxcore on multiple first party domains yet, so it's not sure whether it's a tracker or not. Once adxcore.com has been seen tracking on at least 3 first party domains, privacy badger will block it.
