### ISSUE TITLE
Styling for error report popup

### ISSUE THREAD

**Issue by cooperq** [EFForg/privacybadgerfirefox#399]
It's pretty basic and ugly right now, we should style it and also give some indicator of success and a fade out when the user hits the submit button. We should also answer this open question:
Do users expect to recieve communication since we are encouraging them to post a message?

**Comment by SwartzCr** [comment]
what would you like to see in this styling?

**Comment by cooperq** [comment]
General cleanup and polishing of the popup, it's pretty rough right now. Fix grammar errors, center it, make it look prettier / less scary, etc.
