### ISSUE TITLE
non-trackers are getting blocked if loaded multiple times

### ISSUE THREAD

**Issue by SwartzCr** [EFForg/privacybadgerfirefox#412]
follow these instructions:
Can be tested by visiting the following four domains, after which act.eff.org should be added to the DNT list. 
https://act.eff.org (get teh cookie)
https://standagainstspying.org/
https://fight215.org/
https://jsfiddle.net/j6a4phr4/

Note that anon-stats.eff.org isn't marked as a tracker
refresh fight215 or stand against spying a few times and notice that all domains get blocked

**Comment by cooperq** [comment]
works as expected
