### ISSUE TITLE
Options menu doesn't take up full screen height

### ISSUE THREAD

**Issue by SwartzCr** [EFForg/privacybadgerfirefox#431]
It'd be really nice if it was taller, then we could see more sliders!

**Comment by SwartzCr** [comment]
maybe @Hainish wants to take a crack at this?

**Comment by cooperq** [comment]
So the problem with this is that there is no way (afaict) to say 'take up 100% of screen height', we can only do absolute pixel widths, so we have to go with the smallest screen we think someone might conceivably run this on. And I presume you mean the popup menu, yes?

**Comment by cooperq** [comment]
Oh, or do you mean the list of sliders in the options page, which also doesn't take up the full screen height and can be fixed!

**Comment by SwartzCr** [comment]
Yup, that one!
It's just funny seeing a whole page with the displayed part being like half the screen height.
Maybe @taravancil would be up for taking a crack at this? It should be a simple CSS thing with the code that makes that options page bounding box
