### ISSUE TITLE
pop-up refresh is kinda slow

### ISSUE THREAD

**Issue by SwartzCr** [EFForg/privacybadgerfirefox#432]
Since Firefox renders the popup as a page that it re-edits every time you open it, instead of say making it from scratch, for a brief moment you see the old settings, either from a different page or from the same one but an old version of it.
This is a little confusing, essecially the first time you open it and you see a lot of elements that should be hidden, or when you change settings and then can't see them displayed.
Maybe move the refresh call higher somewhere or clear the popup on close? not sure if this is actionable, and probably not a 1.0 thing
(maybe a good volunteer task!)

**Comment by cooperq** [comment]
I agree, I think this is pretty bad UI right now and definitely needs to be fixed. I think this is pretty high importance, as well.
