### ISSUE TITLE
Nudge the user to view the onboarding comic

### ISSUE THREAD

**Issue by cooperq** [EFForg/privacybadgerfirefox#434]
There is still a danger that users will skip the onboarding slideshow (even though it looks super awesome!) and will just go right into it. 
We should put a window in the popup that users only see the first time they open it, the window should encourage the user to read the privacy badger onboarding comic and make sure they understand how it works. After that the user should not see the popup again.  This can probably be accomplished with a flag in local storage. Adding to chrome as well.

**Comment by SwartzCr** [comment]
same as : https://github.com/EFForg/privacybadgerchrome/issues/487
This is an overlay that displays once the first time PB is run, and maybe the overlay should continue to pop-up until the user has actually looked at the onboarding comic. Perhaps some localStorage setting is in order

**Comment by cooperq** [comment]
Probably shouldn't come up again, I think triggering the thing once is fine, We don't want to force the user to read it if they don't want.

**Comment by cooperq** [comment]
closed by @taravancil via #451
