### ISSUE TITLE
once you allow some tracker, there is no way to block it again

### ISSUE THREAD

**Issue by nekromoff** [EFForg/privacybadgerfirefox#436]
since before the page reported e.g. 9 trackers and now it reports only 6.
and does not show the others, so once enabled to green, there is now way to change to red as they disappear.

**Comment by nekromoff** [comment]
It must have been some glitch, because on reload Badger show correctly all the external JS trackers. Closing.

**Comment by cooperq** [comment]
I think this issue is also fixed by #425
