### ISSUE TITLE
Make sure that manually moving the slider to orange position doesn't mean that PB will be short-circuited for the future for that domain

### ISSUE THREAD

**Issue by antistress** [EFForg/privacybadgerfirefox#443]
Hi,

If I'm not wrong, when user manually moves the slider, it 1°) changes the setting and 2°) means that PB will not bother anymore with that domain unless the user uses the arrow to reset the setting ?

We can indeed assume that if the user changes the setting to red or green, he knows what he does.

But if he changes it to orange, it may mean that he's waiting to better evaluate the situation. Therefore PB should keep on investigate that domain in this situation and report the user.

Thanks

**Comment by cooperq** [comment]
I don't think there is a good way to do this in the UI, and I also feel like we should trust that the user is making the decision that they want and not try to second guess them. There are a lot of good reasons to move something to cookie blocked instead of 'blocked' or 'allowed'.
