### ISSUE TITLE
Using Privacy badger in firefox with auto update on but still only have version 0.2.6

### ISSUE THREAD

**Issue by cypherpunk** [EFForg/privacybadgerfirefox#447]
I currently am using privacy badger version 0.2.6 in firefox version 39.  The privacy badger addon is set to auto update but I still have version 0.2.6 (it has never updated to the new version mentioned).  I even went to your website and downloaded the firefox version from there and it was still version 0.2.6.  Where is this newer version and why does your website still have the old version?

**Comment by cooperq** [comment]
version 0.2.6 is the latest version until 1.0 comes out later this week. We temporarily released 0.99 which is a prerelease of 1.0 but only to a random 5% of users to try to get some bug reports. 
Your copy of privacy badger will auto update later this week when we release 1.0

**Comment by LimboSlam** [comment]
@cooperq, will Privacy Badger stay compatible with Pale Moon (an open source web browser forked off from the Firefox/Mozilla code) once the new stable version is release? If not could you please as an exception for us, a simple change to the chrome.manifest or bootstrap.js to add/change the hard-coded GUID could be the solution here, if you don't plan to support us? 

-Our GUID is: {8de7fcbb-c55c-4fbe-bfc5-fc555c87dbc4}
-Firefox compatible UA string is: Mozilla/5.0 (Windows NT 6.1; rv:25.6) Gecko/20150723 Firefox/31.9 PaleMoon/25.6.0
-Pale Moon UA string is: Mozilla/5.0 (Windows NT 6.1; rv:25.6) Gecko/20150723 PaleMoon/25.6.0

For more info on this specific issue, please read this: https://forum.palemoon.org/viewtopic.php?f=24&t=8740.

**Comment by riiga** [comment]
I just got the 1.0 release in Pale Moon but the Privacy Badger icon that use to be in the lower right corner has disappeared. :-(

**Comment by SwartzCr** [comment]
Hi @LimboSlam,
whay do you think prevents the 1.0 version of privacy badger from working in Pale Moon? And what is preventing you from forlking it from stable and maintaining a version with those two fixes? I'm curious, and would like to help, but it sounds like a manageable project for a fork if it's just these minor differences.

**Comment by LimboSlam** [comment]
@SwartzCr, I'm not that good in coding/programing so I wouldn't be the right guy here. I'm more of the messenger boy, so I'll see if one of our add-on team devs can fix this issue, they should as they have forked HTTPS Everywhere. This was just a friendly question and so I will respect your decision here.  :)
