### ISSUE TITLE
PB must be signed

### ISSUE THREAD

**Issue by CircleCode** [EFForg/privacybadgerfirefox#456]
in nightly (and coming firefox versions), unsigned addons can no more be installed or enabled.
So please sign PB in order to allow us to keep using it (see https://support.mozilla.org/en-US/kb/add-on-signing-in-firefox)

**Comment by rugk** [comment]
See https://github.com/EFForg/privacybadgerfirefox/issues/358

**Comment by CircleCode** [comment]
sorry for the dupe
