### ISSUE TITLE
messy UX in new version

### ISSUE THREAD

**Issue by nekromoff** [EFForg/privacybadgerfirefox#457]
![1](https://cloud.githubusercontent.com/assets/8550349/9108301/58ebe486-3c2d-11e5-8bf4-ede4380029ee.png)
Is it possible to return old interface instead of the new messy one? This is a definite step down in the terms of UX.

PS: And why the hell two scrollbars??

**Comment by rugk** [comment]
Two scroll bars is really a bit strange. I think it should be only one scroll bar. And here in Firefox 39 on Windows 7 it also only displays one (the small one to scroll through the entries. Just not that I've already clicked on the orange message on the top, so it disappeared - maybe that's what is causing the second scroll bar.
And please also note that while folding out the UI for a second (while it's loading I assume) it displays the big scrollbar too.

**Comment by nekromoff** [comment]
There is another issue (although less apparent from static screenshot). The overlapping of elements / somehow hidden at the top:
![bug](https://cloud.githubusercontent.com/assets/8550349/9111350/9d6907b0-3c46-11e5-9a3c-6411a129c653.png)

The second scrollbar appears when hovering over tracker green/orange/red status bar or randomly over bottom button.

This is latest Firefox, Linux/Ubuntu.

**Comment by rugk** [comment]
In my case it looks quite well. No overlapping and all buttons are in the correct line:
![privacybadger_panel](https://cloud.githubusercontent.com/assets/11966684/9111968/c7c18e92-3c4b-11e5-9f1c-7d52cce0294d.png)

(Only the scrollbar seems to be a bit too long at the top, because the "scroll up"-button isn't displayed.)

**Comment by cypherpunk** [comment]
You are the lucky ones, at least you have slider functionality, where in my case (FF39) :

I’m stuck entirely. Badger is working his job, but entire interface is frozen loading is never finished:

[img]http://picload.org/image/ipcpwdc/privacybadger06.08.2015-02.png[/img]

My case described in more detail  : https://tinyurl.com/nt2vs4s

**Comment by nekromoff** [comment]
my question also is why has the working and clean (from design point of view) UI been changed to such a mess of information overload?

**Comment by jdorenbush** [comment]
I'm seeing lots of interface issues on my computer too. 
- Double scrollbars (Slight increase in the window height would eliminate outer scrollbar.)
- Fixed position of slider icons (Fixing the above issue would resolve this. The white bar with the 3 icons has a "fixed" position so when you slide the outer scrollbar the white bar remains in the same position but the rest of the content moves.) 
- The info bubble that pops up when you hover over individual sliders should be removed. It displays redundant information and covers up the entire row directly below the slider that's being hovered.
- The text field, textarea, and 2 buttons on the "Whitelisted Domains" settings page could use some styling improvement, see screenshot below:
![screenshot](https://cloud.githubusercontent.com/assets/7949554/9132055/78baab6c-3ca5-11e5-9460-fa6da1b85d8f.png)

Ubuntu 14.04 -- Firefox 40.0 -- Privacy Badger 1.0.0

**Comment by jfml** [comment]
Same issue with FF 39.0.3 on OSX 10.9.5

**Comment by nyuszika7h** [comment]
I have the same issue too (Firefox 42.0a1 on Windows 10). Also, I have noticed two things:

* The "Learn how Privacy Badger protects your privacy" bar does not disappear after I click it. Maybe this is because I have browsing history disabled?
* The settings page is really laggy, making the whole browser lag, especially when switching tabs.

**Comment by jfml** [comment]
@nyuszika7h Yeah, that bar might be (at least part of) it. Without that bar the content should be small enough to fit into the window and one of the scrollbars would go away, I think.  Shouldn't that bar have a Dismiss/X-Button?

**Comment by cooperq** [comment]
This should be fixed by the newest version 1.0.1, please update your addons and try again.

**Comment by jfml** [comment]
@cooperq Works for me on OSX / FF40.0! Thanks so much!

**Comment by nekromoff** [comment]
seems to be fixed ubuntu 14.04/ff 40

**Comment by jdorenbush** [comment]
@cooperq I can confirm that this is fixed for me. Ubuntu 14.04 / Firefox 41.0b1
