### ISSUE TITLE
No practical way to disable trackers

### ISSUE THREAD

**Issue by BobAlice000** [EFForg/privacybadgerfirefox#470]
So having installed the new Privacy BAdger today on the very latest Firefox  I am presented with the fact that 300 trackers are tracking me. 

Almost all of these are given full reign over tracking me by default by Badger for some unknown reason. 

In order to turn them off, I have to interact with a slider widget for each one individually. 

Sliding the slider widget causes the page the widgets and trackers are on to become inoperable for about 5-6 seconds. 

You do the math. 300 * 5 seconds = 1500 seconds = 25 minutes of sitting there turning all these trackers off-  using your own interface! 

There is no way to turn them all off- my goal- (why?) and there is no way to do them quickly because of some sort of time out or slow server hit or perhaps this is just a javascript library problem. 

You turn one off and you have to wait the 5 seconds before you can turn another one off. It's like an anti-interface interface. 

Whatever it is, the net effect is users of Privacy Badger cannot practically turn off the trackers.

If that result is not the intended goal of the interface, then you're going to have to rework how the user is able to turn off the trackers.

**Comment by SwartzCr** [comment]
Hi @BobAlice000 
have you looked through the comic on the first run page? (click the ? in the pop-up to get to it)
Privacy Badger will only block a third party once it notices it on multiple sites. With a little more browsing those sliders should start moving to red and yellow. If you would like to create rules for whole sets of domains, you can set rules for specific origins (like google.com as opposed to apps.google.com) via the options page, simply click the gear on the pop-up to get there!
