### ISSUE TITLE
Privicy badger options page sliders. 

### ISSUE THREAD

**Issue by cypherpunk** [EFForg/privacybadgerfirefox#473]
Has detected over 300 tracker domains.

they are all green on the slider.

You expect all users to MANUALLY slide every single one to the red when it hangs or pauses the browser every time?

ridiculous. PLEASE add a slide all function to choose one setting or a select all or anything that is more optimal than MANUALLY SELECTING OVER 300 SLIDER CHOICES.

Please add a block all by default or something?

good product, poor implementation unfortunately.

**Comment by SwartzCr** [comment]
hi @cypherpunk 
have you looked through the comic on the first run page? (click the ? in the pop-up to get to it)
Privacy Badger will only block a third party once it notices it on multiple sites. With a little more browsing those sliders should start moving to red and yellow. If you would like to create rules for whole sets of domains, you can set rules for specific origins (like google.com as opposed to apps.google.com) via the options page, simply click the gear on the pop-up to get there!
