### ISSUE TITLE
Wikia images are blocked

### ISSUE THREAD

**Issue by nyuszika7h** [EFForg/privacybadgerfirefox#475]
Here's a list of domains which are completely blocked by default on Wikia in Privacy Badger 1.0.0:

- slot1.images.wikia.nocookie.net
- slot1.images1.wikia.nocookie.net
- slot1.images2.wikia.nocookie.net
- slot1.images3.wikia.nocookie.net
- slot1.images4.wikia.nocookie.net
- vignette1.wikia.nocookie.net
- vignette2.wikia.nocookie.net

There's also `img2.wikia.nocookie.net`, but I'm not 100% sure if that was blocked, maybe only cookie-blocked.

It seems pretty strange that PB is blocking requests to `nocookie.net`.

**Edit:** Maybe this is caused by the ETag?

**Comment by SwartzCr** [comment]
hmm maybe we should add wikia.nocookie.net to the greylist

**Comment by cooperq** [comment]
It is incredibly strange that nocookie.net would get blocked. Unless they are messing with localStorage or doing thngs that look like canvas fingerprinting.

**Comment by aaronharding** [comment]
So do you recommend unblocking wikia.nocookie.net? Or at least just blocking cookies?

**Comment by cooperq** [comment]
unblocking nocookie.net should be fine. I think that this may have happened due to our overblocking bug. nocookie.net will not get blocked ever under normal circumstances. moving all nocookie.net domains to green should be fine.
