### ISSUE TITLE
Does not work for me

### ISSUE THREAD

**Issue by cypherpunk** [EFForg/privacybadgerfirefox#476]
Firefox: 33.0.2
OS: Windows XP 32-Bit

All what i see ist "Loading..."
The 3 buttons does not seems to work. It a .log or something available to find out whats wrong?
![Uploading prbadgaer.PNG…]()

**Comment by jimfr** [comment]
This is a duplicate of #458 (as was my post :) )

**Comment by cypherpunk** [comment]
ooops...i didnt see.

thx!

**Comment by cypherpunk** [comment]
i want close the issue now for duplicate reasons.
