### ISSUE TITLE
Privavy Badger blocks BBC.com images.   

### ISSUE THREAD

**Issue by ZapVolt** [EFForg/privacybadgerfirefox#480]
Blocked 4 trackers on this site. All images on BBC home screen below the top set of images were immediately erased. Clicking the remaining image frames still takes me to the connected story. Deactivated Badger for the site and restarting Firefox using the Badger Icon... made no differences. Went into Firefox and disabled Privacy Badger under extensions.  Restarted BBC.COM and my images came back.  Re-enabled Privacy Badger and reset tracker settings for BBC.COM and images remained on.

**Comment by SwartzCr** [comment]
Oh, this is probably happening because BBC.com gets resources from BBC.co.uk, which is a different domain. Can you let us know which third party domains Privacy Badger was blocking? Maybe we can add them to the graylist

**Comment by thrnz** [comment]
It's an issue on bbc.co.uk as well as bbc.com - privacybadger seems to be blocking *.bbci.co.uk

**Comment by SwartzCr** [comment]
Thanks for the headsup bbci.co.uk should be added to the cookieblock list I think!

**Comment by SwartzCr** [comment]
addressing this here: https://github.com/EFForg/privacybadgerchrome/pull/573

**Comment by SwartzCr** [comment]
merged!
