### ISSUE TITLE
privacy badger is not compatible with Firefox 39.0

### ISSUE THREAD

**Issue by gonebiking** [EFForg/privacybadgerfirefox#481]
I get the message “privacy badger is not compatible with Firefox 39.0“ when I try to install it on Android. I disabled all other add-ons and restarted Firefox. Didn't help.

**Comment by gonebiking** [comment]
Today update to Firefox 40.0, same error with newer version number.

**Comment by CollectorOfBolts** [comment]
I am also experiencing this issue.

**Comment by cuviper** [comment]
See #271 for porting to Android, and #326 to document it as currently unsupported.

**Comment by cooperq** [comment]
Exactly what @cuviper said. We do not support firefox on android, yet.
