### ISSUE TITLE
netdna-ssl.com blocked, breaks many sites

### ISSUE THREAD

**Issue by nyuszika7h** [EFForg/privacybadgerfirefox#484]
For example on 85ideas.com. The one in particular being blocked there is cdn-na1432064595.netdna-ssl.com.

**Comment by SwartzCr** [comment]
it looks like we're already allowing netdna-cdn, I'll add netdna-ssl

**Comment by SwartzCr** [comment]
fixed here: https://github.com/EFForg/privacybadgerchrome/pull/580
