### ISSUE TITLE
UI frozen if localStorage disabled

### ISSUE THREAD

**Issue by billux** [EFForg/privacybadgerfirefox#486]
Hi,

I've installed PrivacyBadger 1.0 .0 on Firefox 39/Debian wheezy, but I've got a frozen UI exactly as reported in the issue #458.
In the developer's console, the following exception is reported:

    TypeError: this.localStorage is null
    Trace de la pile :
    init@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/loader/sandbox.js -> resource://jid1-mnnxcxisbpnsxq-at-jetpack/privacybadger/data/popup.js:43:7
    @resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/loader/sandbox.js -> resource://jid1-mnnxcxisbpnsxq-at-jetpack/privacybadger/data/popup.js:468:3
    onEvent@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/loader/sandbox.js -> resource://gre/modules/commonjs/sdk/content/content-worker.js:45:22
    onEvent@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/loader/sandbox.js -> resource://gre/modules/commonjs/sdk/content/content-worker.js:45:22
    onChromeEvent@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/loader/sandbox.js -> resource://gre/modules/commonjs/sdk/content/content-worker.js:91:16
     timers.js:43

I have localStorage disabled in my settings (dom.storage.enabled set to false in about:config). If I re-enable it, everything works fine.

Is possible to fix PB so it can run with locaStorage disabled on browser?

**Comment by cooperq** [comment]
We probably can't do anything about this without a ton of work and refactoring, so not any time soon. I think the best we could do is have a warning for the user.

**Comment by cooperq** [comment]
Actually it turns out this was the same issue as many other issues. I have fixed it as of 1.0.1
