### ISSUE TITLE
Privacy Badger unsafe to use in Firefox 40.0

### ISSUE THREAD

**Issue by Bluecheckers** [EFForg/privacybadgerfirefox#489]
Privacy Badger is an unsigned Firefox extension.
Firefox 40.0 users should remove Privacy Badger due to the security risk.

**Comment by cypherpunk** [comment]
It's not unsafe per se, it's just unsigned.  Firefox 40 is set up to warn about unsigned extensions and many current add-ons aren't signed yet.  Signing won't be enforced until Firefox 41.  It would be a good idea for Privacy Badger to start signing before then.  http://www.ghacks.net/2015/06/19/how-to-disable-the-firefox-40-add-on-signing-requirement/

**Comment by cooperq** [comment]
What @cypherpunk said. See #358 for our discussion on this.
