### ISSUE TITLE
"Firefox is'nt responding" error when I slide the slider

### ISSUE THREAD

**Issue by bkrucarci** [EFForg/privacybadgerfirefox#491]
Yes, the title explains all.
I am looking my settings in PrivacyBadger. I see domains under left corner.
I want to block some of them that I know ad servers. I slide the slider to left and suddenly "Firefox is not responding" appears. It happens everytime. I tested on my mom PC too. It is happening.
Can you please improve this? Because Chromium has not such a problem.

Thanks

**Comment by SwartzCr** [comment]
interesting, can you open up the browser console (ctrl+shift+j) and tell me if you see any errors (lines that are red) when you do this?

**Comment by bkrucarci** [comment]
I want to give more feedback.
I just uninstalled Firefox 32bit and installed Firefox 64bit beta.
Firefox does not show the "not responding" message but it is hanging a little..
There is no error in this page (ctrl+shift+j)

You can ask me more about it, do not hesitate. I want to help. You can remote my laptop on Teamviewer if you want.

**Comment by bkrucarci** [comment]
here is what I saw on Firefox 32bit (ctrl+shift+j)
screenshot : http://i.imgur.com/uJZQaRA.png

**Comment by cooperq** [comment]
Thanks @bkrucarci, we will look into this and try to fix the issue for 32 bit browsers.
