### ISSUE TITLE
New Browser opens with the following page

### ISSUE THREAD

**Issue by Billabonga** [EFForg/privacybadgerfirefox#494]
http://www.aeriagames.com

found on movie4k.to

**Comment by cooperq** [comment]
I'm sorry, I don't understand what the issue is here. Can you explain in a bit more detail?

**Comment by Billabonga** [comment]
Hi, when I opened movie4k.to and clicked on a new section (tv shows) a 
second browser page opened as attached to my previous note

**Comment by cooperq** [comment]
Privacy Badger isn't a popup blocker., firefox should actually be doing this job. But if it is not working you might consider installing another extension to do popup blocking.
