### ISSUE TITLE
AlternativeTo.net functions blocked

### ISSUE THREAD

**Issue by anonsubmitter** [EFForg/privacybadgerfirefox#498]
All of the problems mentioned below only exist when Privacy Badger is enabled.

Sample page: https://alternativeto.net/software/privacy-badger/
* Clicking the monkey wrench icon on software pages does not bring up the overlay with actions ("Edit Information", "Report a problem" and "Suggest alternatives").
* Clicking the "More info" link or the blue "MORE INFORMATION" button does not expand the description to display the full description.
* If Privacy Badger is disabled, "More info" / "MORE INFORMATION" is clicked, the description is expanded and Privacy Badger is enabled again the description does not collapse if the blue "LESS INFORMATION" button is clicked.

In [the forum](https://alternativeto.net/discussions/) the "Edit" button on one's own forum posts disappears, making them impossible to edit.

**Comment by anonsubmitter** [comment]
It seems like changing cdn.jsdelivr.net from being completely blocked (red) to just blocking cookies from the domain (yellow) fixes this.

**Comment by jawz101** [comment]
You're going around submitting a ton of these tickets essentially unblocking tracking cookies.
https://github.com/anonsubmitter
