### ISSUE TITLE
Site issue: twitch.tv

### ISSUE THREAD

**Issue by thrnz** [EFForg/privacybadgerfirefox#499]
PB seems to have marked several domains that are used by twitch.tv as trackers. As a result, streams no longer play on twitch.tv, nor when embedded in other sites (such as speedrunslive.com).

I need to manually allow ttvnw.net justin.tv and jtvnw.net subdomains to get it working.

On a tangent, is it possible to manually greylist (ie. set to 'yellow') a site+subdomains? It can get quite tedious having to manually set subdomains one at a time - especially when they change frequently (ie. CDN type stuff).

**Comment by SwartzCr** [comment]
yes it is possible to whitelist parent domains!
Just go to the options page (the gear icon) and the subdomain should appear on the list of domains, set it to yellow or green and it should propogate to all subdomains

**Comment by SwartzCr** [comment]
additionally it sounds like we should add ttvnw.net justin.tv and jtvnw.net to the cookieblocklist

**Comment by SwartzCr** [comment]
I've opened a pr for the fixes in chrome (#569) which may seem weird, but the lists are shared between extensions

**Comment by SwartzCr** [comment]
okay new PR: https://github.com/EFForg/privacybadgerchrome/compare/master...issue_499

**Comment by SwartzCr** [comment]
domains have been added to the list
