### ISSUE TITLE
Problem with UI - not showing information

### ISSUE THREAD

**Issue by habiloid** [EFForg/privacybadgerfirefox#500]
Hi
I only ever get a "Loading..." along with some non-functioning buttons when I try to access the sliders UI.

I am using Privacy Badger 1.0.0 in Iceweasel 40.0 on Parabola Linux

![iceweasel](https://cloud.githubusercontent.com/assets/13556621/9271548/b6d20026-4272-11e5-80e5-40b6a87c3c17.png)

Thanks

**Comment by cooperq** [comment]
Please make sure you have version 1.0.1 installed from either addons.mozilla.org or eff.org/privacybadger
