### ISSUE TITLE
riseup.net visit gets PrivacyBadger blocking the browser

### ISSUE THREAD

**Issue by cypherpunk** [EFForg/privacybadgerfirefox#506]
Visiting the riseup.net site and specifically the simple page https://lists.riseup.net/www/info/pcamt will make the Iceweasel browser (aka Firefox) excessively slow, to the point there is no more means to use it.

Disabling PrivacyBadger quickly after the page has loaded releases the resources and the browser gets running properly again. If one waits too much after the page opened, there is no more way to even disable PrivacyBadger, due to the slowness of the interface. 

Even reporting the bug via the PrivacyBadger is no more reachable! (Reason why I report it via github.)

=> Sorry guys, but now I really have to kick PrivacyBadger out of my computer. Good luck for next versions.

Iceweasel 38.2.0 (and previous) from Debian mainstream.
PrivacyBadger 1.0.1 (15/08/2015)

**Comment by SwartzCr** [comment]
I'm using debian mainstream, and I notice no slowdown on iceweasel 38.2.0 with PB 1.0.1, also no slowdown in firefox 39, or with an old version of iceweasel (31)
It sounds like some connection in PB is getting blocked!
I'm going to close this issue, but if you can try it again and let us know if any errors show up in the browser console (ctrl+shift+j) feel free to re-open it
