### ISSUE TITLE
cdn.discourse.org blocked in Discourse forums

### ISSUE THREAD

**Issue by rugk** [EFForg/privacybadgerfirefox#511]
E.g. on https://community.letsencrypt.org cdn.discourse.org is blocked:
![discussblocked](https://cloud.githubusercontent.com/assets/11966684/9290145/2728c308-4388-11e5-8672-761d929f05f1.png)

This causes the complete site to display only a white piece.

**Comment by SwartzCr** [comment]
being addressed here: https://github.com/EFForg/privacybadgerchrome/pull/572

**Comment by SwartzCr** [comment]
merged
