### ISSUE TITLE
UI suggestion:  Move "Click to deactivate PB..." button to top of dropdown menu

### ISSUE THREAD

**Issue by jimfr** [EFForg/privacybadgerfirefox#513]
One of the most common things I do is deactivate PB for a given site.  It would be nice if the button to do so was always in the same place in the dropdown menu.  Moving it above the sliders would accomplish this. The "Report Broken Site" button could go with the "deactivate" button, or remain at the bottom, as it seems it is less frequently used.

**Comment by SwartzCr** [comment]
visual space is already a very contested resource
I think this would go against our UI best practices, so I'm not in favor of this change
I understand the concern, but I think this would lead to a lot of strain in people using privacy badger normally, and trying to introspect the third parties on any given site.
I'm going to close this, you or @cooperq can re-open it if you can think of a reasonable way to fit them in without pushing other content off of the screen

**Comment by jimfr** [comment]
As you will... but it's only one line, and, since PB is brand new, much of the time I'm deactivating it on sites, as PB is over-aggressive, so it would be nice to have it in the same place each time, instead of having to hunt for it.

One thing that might work (and there is room), is to put the Deactivate command as a circular button to the left of the Question Mark round button.  The icon could be a badger with a red circle around it and a cross through it.
