### ISSUE TITLE
PB should check the .well-known/dnt JSON resource

### ISSUE THREAD

**Issue by michael-oneill** [EFForg/privacybadgerfirefox#518]
A big problem with simply checking for the sha1 hash of dnt-policy.txt comes up when the policy is updated. Different versions of PB exist in the wild, not everyone updates promptly, and the downloaded hashes will not always match an updated policy.
This will delay new policy amendments because it would only be safe to place them in a domain's .well-known resource when a significant of proportion of installed PBs have been updated.
In addition to the dnt-policy.txt check PB could check that the "compliance" property of the W3C recommended Tracking Status Resource exists (JSON resource at {domain}/.well-known/dnt) . If this property string compares with https://www.eff.org/.well-known/dnt-policy.txt (which BTW needs updating), then assume compliance. This would allow EFF to post up the latest version of the policy and servers could immediately refer to it.
I think the bandwidth requirement on EFF would be very low (it would be cached), and if that is still a problem another trusted location could be used. There may be a legal problem for some companies to point to a document that may change without them being aware, but then they can post an old version in dnt-policy.txt. Most companies would rely on the EFF keeping their version current and to publicise any amendments.

**Comment by cooperq** [comment]
Privacy badger already downloads a new list of acceptable dnt policy hashes from eff.org regularly. So this is already done!
