### ISSUE TITLE
When Privacy Badger icon is hidden inside Firefox's hamburg menu it's necessary to click twice on the menu to open it

### ISSUE THREAD

**Issue by brwolfgang** [EFForg/privacybadgerfirefox#522]
Hi there,
I'm running Firefox 40.0.2 and noticed that when I place the Privacy Badger icon inside the hamburg menu (the one with three horizontal lines like the screenshot below) I have to click twice on the menu icon to open it.
![2015-08-17_220252](https://cloud.githubusercontent.com/assets/3627736/9320775/c2c81fda-452b-11e5-82ef-c64a6c04b394.png)
The first time I click the menu it just get highlighted, when I click again it opens. If I place the PB icon outside the menu it works just fine on the first try.

**Comment by rugk** [comment]
I can confirm this issue with Firefox 40.0.2 on Windows 7:
![privacybadger_twiceclick](https://cloud.githubusercontent.com/assets/11966684/9326128/e8243fd6-4597-11e5-8e46-e66217b87752.gif)

**Comment by cooperq** [comment]
I am not able to reproduce this issue, but it also feels a little like a firefox issue. Our extension shouldn't be able to effect the behavior of the menu icon.

**Comment by brwolfgang** [comment]
So let's wait for a Firefox update and see what happens

**Comment by brwolfgang** [comment]
I've filled a bug on Bugzilla here: https://bugzilla.mozilla.org/show_bug.cgi?id=1196275

**Comment by SwartzCr** [comment]
can any of you confirm if it's possible to re-order these addons? maybe by dragging PB directly to the browser bar? That might solve this issue

**Comment by xXFlorianXx** [comment]
Doesn't seem to be PB specific. I had the same result with the extension "Video DownloadHelper". I've added a comment on Bugzilla.

**Comment by brwolfgang** [comment]
Turns out it's a known Firefox bug (check here https://bugzilla.mozilla.org/show_bug.cgi?id=1029937). 
Closing this =)
