### ISSUE TITLE
Cannot block  uds.googleusercontent.com !

### ISSUE THREAD

**Issue by butrus** [EFForg/privacybadgerfirefox#529]
Hi!

I'm using Privacy Badger on Firefox and while browsing http://reviewjolla.blogspot.de Privacy Bagder shows a couple of websites in the section "The following domains don't appear to be tracking you" which I don't trust and want them to be blocked. One of them is uds.googleusercontent.com. But if I set this website to "yeallow" or "red" it reappears next time (after reload of the page) as "green".

(Now I blocked the whole *.googleusercontent.com on my resolving DNS but anyway it seems that Google tries to disable PB somehow!)

**Comment by SwartzCr** [comment]
this is an issue with the popup I think, I bet if you were to look in your options page you'd see them appear correctly as set to block
I'm going to close this issue in favor of #492, please feel free to follow the conversation there
