### ISSUE TITLE
"The following domains don't appear to be tracking you" doesn't appear in Firefox at all

### ISSUE THREAD

**Issue by Garve** [EFForg/privacybadgerfirefox#535]
Hi!

I know that many sites should display "The following domains don't appear to be tracking you", but it's not the case in Firefox for me. In Chromium it works like this and the domains there never get blocked. But in Firefox everything is considered a potential tracker for me.

Fedora 22
Firefox 40.0.2
Privacy Badger v1.0.1

**Comment by cooperq** [comment]
Do you have third party cookie blocking turned on?

**Comment by Garve** [comment]
Yes I have. I turned it off for testing, now  can see the message, thank you! But why would I accept third party cookies in the first place? Do you recommend never accepting them, or accepting them? Anyway, it's not a bug of PB then. :)
