### ISSUE TITLE
Add-on not signed

### ISSUE THREAD

**Issue by jimfr** [EFForg/privacybadgerfirefox#542]
In FireFox 40.0.2, the add-ons page shows an issue with the signing of Privacy Badger (see image).  The add-on still functions.

![firefox privacy badger signed](https://cloud.githubusercontent.com/assets/5986716/9411518/2d1f55ae-47db-11e5-8e24-bf9799002de0.PNG)

**Comment by rugk** [comment]
duplicate of https://github.com/EFForg/privacybadgerfirefox/issues/358
