### ISSUE TITLE
GameSpot video player blocked

### ISSUE THREAD

**Issue by anonsubmitter** [EFForg/privacybadgerfirefox#544]
Sample: http://www.gamespot.com/videos/now-playing-mad-max/2300-6426597/

Privacy Badger is blocking GameSpot's video player. Disabling Privacy Badger will make the video player appear, but I haven't managed to figure out which tracker needs to be unblocked.

Sort of related: https://github.com/EFForg/https-everywhere/issues/2637

**Comment by jawz101** [comment]
You're going around submitting a ton of these tickets essentially unblocking tracking cookies.
https://github.com/anonsubmitter
