### ISSUE TITLE
PB blocks a call to "127.0.0.1"

### ISSUE THREAD

**Issue by danstowell** [EFForg/privacybadgerfirefox#546]
Hi - OpenStreetMap.org includes a "remote control" shortcut which mappers can use to invoke map editing software. The exact URL called for me just now was

http://127.0.0.1:8111/load_and_zoom?left=-1.6405390335083008&top=53.33117801248183&right=-1.5716744827270508&bottom=53.319392302635364

It seems to me that 127.0.0.1 and other forms of localhost should not be blocked at all by PB, since of course they're local, they're not a third party. I wonder if the PB designers agree?

This issue is similar to #347 and #477... but no-one seems to have discussed the idea that PB blocking localhost content seems weird in general...

**Comment by rcutmore** [comment]
This should be fixed now with pull request #700.
