### ISSUE TITLE
Privacy Badger requires DOM storage to operate

### ISSUE THREAD

**Issue by SwartzCr** [EFForg/privacybadgerfirefox#549]
It seems like this might not be enabled by default in Firefox 40, and requires going into about:config to enable.
From an AMO review (https://addons.mozilla.org/en-US/firefox/addon/privacy-badger-firefox/reviews/735890/reply):
"The only way I can get PB. to load ( it continually stays in the loading phase ) is to enable dom. storage in 'about; config. ' I'm running Firefox 40.0 . Maybe I could roll back to an earlier version of Privacy Badger. Do you see a work around for this issue ?"
We should address this in the next release if possible

**Comment by cooperq** [comment]
this is already fixed. see #496
