### ISSUE TITLE
Privacy Badger appears broken if user is blocking all third party cookies

### ISSUE THREAD

**Issue by SwartzCr** [EFForg/privacybadgerfirefox#550]
From AMO:
"That raises one point. Privacy Badger operates on third-party cookies. So if your Firefox profile blocks all third-party cookies, then the P'Badger panel simply reads "Loading..." and goes no further. Enabling third-party cookies to at a minimum accept them "From visited" site enables P'Badger to begin working. But at that point you're depending on Privacy Badger to block third-party cookies."
(https://addons.mozilla.org/en-US/firefox/addon/privacy-badger-firefox/reviews/733502/)
Maybe PB should fail more gracefully, and show a different message

**Comment by cooperq** [comment]
this should be fixed now. this was actually the #486 local storage disabled bug.
