### ISSUE TITLE
PB Firefox seeing cookies where there aren't

### ISSUE THREAD

**Issue by SwartzCr** [EFForg/privacybadgerfirefox#551]
there's a bunch of issues being opened by people claiming privacy badger is blocking things that either seem like they shouldn't be setting cookies, or appear not to be in chrome:
#548 #545 #546 (chrome 566) and a bunch of other blocked CDNs
Maybe this is a good thing to write a unit test for asap and see if we can fix this if it's an existent issue

**Comment by cooperq** [comment]
I am beginning to suspect that this is also the cause of #516

**Comment by cooperq** [comment]
Okay I am fixing this bug in https://github.com/EFForg/privacybadgerfirefox/tree/issue_516
The main bugs are fixed, but currently I am investigating an issue where if the user has cookies turned off privacy badger never blocks anything!

**Comment by cooperq** [comment]
Current thinking for the above comment is that because we are blocking all cookies they aren't getting set by javascript either, should look into javascript cookies and how they affect heuristic reporting.
