### ISSUE TITLE
latest version

### ISSUE THREAD

**Issue by MichaelTiebesl** [EFForg/privacybadgerfirefox#553]
How can I see what version I use or install from: https://www.eff.org/privacybadger?
Is it correct that the version from the add-on page: https://addons.mozilla.org/nl/firefox/extensions/ is an outdated version? 

Thanks

**Comment by cooperq** [comment]
The version in addons.mozilla.org is the latest version. You can see the version of privacy badger by clicking on your firefox menu -> addons and then click the `more` link next to the privacy badger listing.

**Comment by MichaelTiebesl** [comment]
My question was how to see what version is available from the website (https://www.eff.org/privacybadger).

I only can see it once I have downloaded it and installed it in Firefox.
Btw, addons.mozilla has version 1.01 and from the website has version 1.02, once installed in Firefox.

**Comment by cooperq** [comment]
yep. had to bump up the version so amo would sign it, literally no difference between the two
