### ISSUE TITLE
not cookieblocking subdomains of items on cookieblock list. 

### ISSUE THREAD

**Issue by nyuszika7h** [EFForg/privacybadgerfirefox#554]
I noticed this on Wikia.

**Comment by cooperq** [comment]
Weird, this actually shouldn't be getting blocked since googleapis.com is on our cookieblock list. This may be more evidence for cookie block lists not working correctly in firefox. Can you send me the url where you see this?

**Comment by nyuszika7h** [comment]
http://kcundercover.wikia.com/wiki/Episode_Guide

**Comment by cooperq** [comment]
Confirmed reproducible!!!
I will write a test and figure out how to fix this.

**Comment by nyuszika7h** [comment]
If you change the title to that, may as well close as duplicate of #516.

**Comment by cooperq** [comment]
Indeed.
