### ISSUE TITLE
"Marketplace" overlay blocked on barnesandnoble.com

### ISSUE THREAD

**Issue by anonsubmitter** [EFForg/privacybadgerfirefox#555]
Sample: http://www.barnesandnoble.com/w/five-on-a-treasure-island-enid-blyton/1003629355?ean=9781927558379

Click on the white "8 New & Used from
$4.00" button to the right. Normally an overlay would have popped up containing listings from third party sellers, but now it is blocked by Privacy Badger. Changing cdns.gigya.com from being completely blocked (red) to just blocking cookies from the domain (yellow) fixes this.

**Comment by jawz101** [comment]
I understand what you're saying but what you suggest to fix is what you'd do if you want to use them. If they do not honor Do Not Track then that's what you'd have to do but it's a commenting system based on a tracking mechanism. The whole concept is to make a tracker into a feature... which isn't great. I just allow it temporarily if I am compelled to read or write comments but it's not as if I want it to follow me around everywhere Disqus is.

https://en.wikipedia.org/wiki/Disqus#Criticism_and_privacy_concerns

You're going around submitting a ton of these tickets essentially unblocking tracking cookies.
https://github.com/anonsubmitter
