### ISSUE TITLE
Google Maps blocked on zipmap.net

### ISSUE THREAD

**Issue by anonsubmitter** [EFForg/privacybadgerfirefox#556]
Sample: http://www.zipmap.net/California/Los_Angeles_County.htm

Google Maps is blocked on zipmaps.net. Changing maps.googleapis.com from being completely blocked (red) to just blocking cookies from the domain (yellow) fixes this.

**Comment by jawz101** [comment]
You're going around submitting a ton of these tickets essentially unblocking tracking cookies.
https://github.com/anonsubmitter
