### ISSUE TITLE
Privacy Badger prevents being logged in on ask pages of tumblr blogs with custom domains

### ISSUE THREAD

**Issue by anonsubmitter** [EFForg/privacybadgerfirefox#557]
Sample: http://kingofthedorks.co.vu/ask

Privacy Badger prevents being logged in on ask pages of tumblr blogs with custom domains. Changing www.tumblr.com from having it's cookies blocked (yellow) to completely allowing the domain (green) fixes this.
I think this is caused by the blog not being a .tumblr.com domain and I don't think it has anything to do with this: http://blogging.nitecruzr.net/2015/02/free-domain-registration-by-covu.html

**Comment by jawz101** [comment]
You're going around submitting a ton of these tickets essentially unblocking tracking cookies.
https://github.com/anonsubmitter
