### ISSUE TITLE
Embedded images from s3.amazonaws.com blocked

### ISSUE THREAD

**Issue by anonsubmitter** [EFForg/privacybadgerfirefox#558]
Samples:
http://theoatmeal.com/
http://oatmeal.tumblr.com/post/2910950328/dear-tumblr
http://oatmeal.tumblr.com/post/2916375890/thank-you-tumblr

Embedded images from s3.amazonaws.com are being blocked by Privacy Badger. Changing s3.amazonaws.com from being completely blocked (red) to just blocking cookies from the domain (yellow) fixes this.

**Comment by jawz101** [comment]
You're going around submitting a ton of these tickets essentially unblocking tracking cookies.
https://github.com/anonsubmitter
