### ISSUE TITLE
Most of DeviantArt.com is completely blocked by Privacy Badger

### ISSUE THREAD

**Issue by anonsubmitter** [EFForg/privacybadgerfirefox#566]
Layout, images, emoticons and age verification for mature content are blocked on deviantart.com by Privacy Badger, rendering the site largely unusable.

Samples:
http://jeftoon01.deviantart.com/gallery/11344500/Twisted-Princess
http://kasami-sensei.deviantart.com/gallery/44925634/Twisted-Disney
http://kasami-sensei.deviantart.com/gallery/48483058/The-Walking-Disney-Pixar-and-Dreamworks
http://onwingsofblue.deviantart.com/favourites/39999326/Emotes-pixeled-stuff-and-icons
http://jeftoon01.deviantart.com/art/Twisted-Princess-Blue-Fairy-331481256

Changing these from being completely blocked (red) to just blocking cookies from the domain (yellow) fixes this:

a.deviantart.com
e.deviantart.com
img00.deviantart.com
img01.deviantart.com
img02.deviantart.com
img03.deviantart.com
img04.deviantart.com
img05.deviantart.com
img06.deviantart.com
img07.deviantart.com
img08.deviantart.com
img09.deviantart.com
img10.deviantart.com
img11.deviantart.com
img12.deviantart.com
img13.deviantart.com
img14.deviantart.com
img15.deviantart.com
orig00.deviantart.com
orig01.deviantart.com
orig02.deviantart.com
orig03.deviantart.com
orig04.deviantart.com
orig05.deviantart.com
orig06.deviantart.com
orig07.deviantart.com
orig08.deviantart.com
orig09.deviantart.com
orig10.deviantart.com
orig11.deviantart.com
orig12.deviantart.com
orig13.deviantart.com
orig14.deviantart.com
orig15.deviantart.com
pre00.deviantart.com
pre01.deviantart.com
pre02.deviantart.com
pre03.deviantart.com
pre04.deviantart.com
pre05.deviantart.com
pre06.deviantart.com
pre07.deviantart.com
pre08.deviantart.com
pre09.deviantart.com
pre10.deviantart.com
pre11.deviantart.com
pre12.deviantart.com
pre13.deviantart.com
pre14.deviantart.com
pre15.deviantart.com
st.deviantart.com
t00.devianatart.com
t01.devianatart.com
t02.devianatart.com
t03.devianatart.com
t04.devianatart.com
t05.devianatart.com
t06.devianatart.com
t07.devianatart.com
t08.devianatart.com
t09.devianatart.com
t10.devianatart.com
t11.devianatart.com
t12.devianatart.com
t13.devianatart.com
t14.devianatart.com
t15.devianatart.com

**Comment by imd** [comment]
This bug still happens to me. I suggest re-opening it.
