### ISSUE TITLE
Use a less distracting icon for the tracker count

### ISSUE THREAD

**Issue by allo-** [EFForg/privacybadgerfirefox#567]
The green tracker count icon is very distracting in the day to day browsing, so i even disabled it for now:

- It's bright green/red and has too much contrast, so it distracts from the website / other elements in the browser.
- the count badge (not the icon itself) is a bit bigger than the addon toolbar, so it crosses the border, which makes it distracting, too.

So it would be good to put the number a bit lower and use some darker colors. For example uBlock uses nice colors with a darkred for the icon and a white on darkgrey for the count.
But the count badge crosses the browser-UI border there, too.

**Comment by cooperq** [comment]
We can't move where the number is and someone already submitted a pull request to change the colors.

**Comment by allo-** [comment]
Okay, thanks.
I already though the number may be an firefox api, as it looks on quite a few addons that way.
