### ISSUE TITLE
Icon Disappears and Addon May Not Work with FFesr and Java Update

### ISSUE THREAD

**Issue by DoctorX101** [EFForg/privacybadgerfirefox#570]
Mac OS 10.8.5
FireFox 31.8.0esr--why? Because update breaks a particular page.

Received alert that Java needs to update. I did this. The update to 31.8.0esr broke Photobucket. Great! 

So I updated to the latest 38.2.1esr. Privacy Badger (PB) icon disappeared from Toolbar. I checked the Toolbar modification, and the PB icon does not appear. Checking my extensions, PB is still there.

So I re-downloaded it. It appears in Toobar--yay!--but does not seem to work. Clicking only showed "cannot find tracking cookies" on pages that normally show the "sliders." For example, Photobucket shows "15 potential trackers" but on this update PB lost that--could not find trackers.

So I restarted FF . . . and the PB icon disappears again from the Toolbar.

I tested this all on a clone so if you need screen shots of anything I can include them.

The particular page broken by FF updates is not critical. So I could happily update to the latest FFesr--even the "normal" FF--and all of that but not if I lose PrivacyBadger >.< Life would become empty and meaningless.

**Comment by cooperq** [comment]
A java update should not break privacy badger since privacy badger doesn't touch java in any way. Can you tell me what version of firefox and what version of privacy badger you have and also send me a screenshot of the broken popup?

**Comment by DoctorX101** [comment]
Thanks so much. I will do the following booted from my clone:

1. Re-update to the latest ESR which is FF 38.2.1--Java already updated--and check it and screen shot.
2. Try updating to the latest FF which is 40.0.3--I avoided updated because that series broke a particular page which is now basically broken and see if THAT causes a Privacy Badger problem. If it does, I will screen shot all of that as well.

Stay tuned! *Makes Popcorn*

**Comment by DoctorX101** [comment]
Hmmm . . . screenshots not actually loading. Let me try here:

![Uploading 31.8.0.ESR Working.jpg…]()
