### ISSUE TITLE
Should I stop reporting site bugs?

### ISSUE THREAD

**Issue by anonsubmitter** [EFForg/privacybadgerfirefox#571]
It seems that not everyone is happy with me reporting site bugs (#560). Originally I thought that this guy was a maintainer of Privacy Badger and that this was a sort of official request for me to stop reporting site bugs. Now I realize that if he was a maintainer he would have been able to close the issues I opened. So, what I'm asking is do the developers of Privacy Badger still want me to report site bugs or do you agree with this other guy? I currently have eight site bugs to report.

**Comment by cooperq** [comment]
Please do not stop reporting site bugs. The primary maintainers of privacy badger are me and @SwartzCr. We may not add everything you submit to the cookie block list but we definitely look at all of them. It is helpful! Do not be discouraged!

**Comment by anonsubmitter** [comment]
Ok, I've reported all of them and I will report future site bugs when they appear.
