### ISSUE TITLE
Embedded video on Flowlab.io blocked by Privacy Badger

### ISSUE THREAD

**Issue by anonsubmitter** [EFForg/privacybadgerfirefox#575]
The embedded video on http://flowlab.io/ is being blocked by Privacy Badger.

Changing graph.facebook.com from being completely blocked (red) to just blocking cookies from the domain (yellow) fixes this.

**Comment by cypherpunk** [comment]
Just tried this and it is blocked for me too.

Thinking about this a bit more, if 'graph.facebook.com' fixes the issue, it would seem this isn't a problem with PB but rather a problem with the flowlab.io site's implementation (unless the video really is hosted at graph.facebook.com).

**Comment by anonsubmitter** [comment]
Yup, hence the label "site-bug".
