### ISSUE TITLE
Privacy Badger blocks fonts on GameSpot

### ISSUE THREAD

**Issue by anonsubmitter** [EFForg/privacybadgerfirefox#588]
Privacy Badger blocks fonts on GameSpot articles. I have been unable to pinpoint what should be unblocked to fix this.
Sample: http://www.gamespot.com/articles/moonrise-is-the-pokemon-mmo-we-ve-been-waiting-for/1100-6424869/

**Comment by SwartzCr** [comment]
I can't reproduce this, would you mind taking a screenshot of all the domains that PB has blocked?

**Comment by SwartzCr** [comment]
(also that game looks cool)

**Comment by anonsubmitter** [comment]
The fonts are replaced with other fonts when Privacy Badger is enabled. That's what I meant when I said that Privacy Badger blocks fonts. Yeah, I can take a before and after screenshot when I get home.

**Comment by anonsubmitter** [comment]
Hmm. It seems like the fonts are no longer being blocked by Privacy Badger.
