### ISSUE TITLE
PB fails to install on Firefox/Mac

### ISSUE THREAD

**Issue by cypherpunk** [EFForg/privacybadgerfirefox#590]
Installing PB from Firefox performs the download, and that's about it.  When the download concludes, the feedback panel appears as so.

![downloadscreen](https://cloud.githubusercontent.com/assets/97223/9684129/c1321c02-52d2-11e5-97c2-b86485f2b9fa.png)

The install button never becomes active.

Install attempts from eff.org and from other paths within the Firefox browser meet similar fates.  The add-on downloads but will not install.

**Comment by cooperq** [comment]
Do you happen to have the avast AV plugin installed in firefox? That has been known to prevent the installation of privacy badger. Have you tried installing from addons.mozilla.org?

**Comment by fiskr** [comment]
It's worth mentioning I haven't had an issue installing it on Firefox on my Mac.

**Comment by cooperq** [comment]
Closing this issue until I get a response.
