### ISSUE TITLE
Unblocked domain still blocked on certain other sites

### ISSUE THREAD

**Issue by anonsubmitter** [EFForg/privacybadgerfirefox#591]
I had unblocked cdn.jsdelivr.net so that it would only have its cookies blocked (yellow status) when it was causing problems with alternativeto.net (#498). However, cdn.jsdelivr.net was still fully blocked (red status) on [javascript-minifier.com](http://javascript-minifier.com/), [img-resize.com](http://img-resize.com/) and [jpgoptimiser.com](http://jpgoptimiser.com/). It was unblocked on [pngcrush.com](http://pngcrush.com/) though.

**Comment by anonsubmitter** [comment]
It seems like Privacy Badger has reset s3.amazonaws.com
I set Privacy Badger to only block cookies from the domain (yellow status), but Privacy Badger reset it to being fully blocked (red status).

**Comment by anonsubmitter** [comment]
Privacy Badger has also reset a.disquscdn.com which I had changed from red to yellow status.

**Comment by anonsubmitter** [comment]
Privacy Badger has reset video.media.yql.yahoo.com which I had changed from red to yellow status.

**Comment by cooperq** [comment]
This might be because of the fact that we changed privacy badger's plugin id to comply with AMO signing requirements. Let me know if it happens again with one of the domains that you have set since filing this bug.
