### ISSUE TITLE
Please add Ghostery style "click to play" for e.g. disqus

### ISSUE THREAD

**Issue by ArmoredDragon** [EFForg/privacybadgerfirefox#594]
Love the addon so far, namely how it avoids breaking the web. One thing that ghostery does that I wish privacy badger did however is the "click to play" feature for certain tracker content, especially for things like Disqus where sometimes I want to open it and participate, but would rather not have it tracking at all times unless I manually play with the settings.

Having it work "on demand" however would work great.

**Comment by cooperq** [comment]
This should already work. I added disquscdn to the yellowlist as well.
