### ISSUE TITLE
Privacy Badger blocks KeeFox

### ISSUE THREAD

**Issue by brainpower** [EFForg/privacybadgerfirefox#596]
KeeFox uses WebSockets to communicate with a server listening on 127.0.0.1.
After some time KeeFox was unable to connect to this server.

I traced it to Privacy Badger, which actually blocked 127.0.0.1 !
After manually allowing 127.0.0.1 KeeFox started to work normally again.

I've whitlistet localhost for now, but this was quite difficult to track this down and
I cant see how it's sensible to block localhost as tracker.
Anyone tracking himself: it's his own problem...

**Comment by cooperq** [comment]
Agreed privacy badger should not ever block localhost.

**Comment by fiskr** [comment]
I would be interesting in solving this issue. 

I'm trying to figure out the best way to do that - perhaps to add localhost to local storage.domainExceptionSites when installed? 

This would add flexibility for the edge case when someone would _want_ to block localhost.

**Comment by cooperq** [comment]
So adding it to storage.domainExceptionSites will disable it when localhost is the first party, which is maybe not what @brainpower is describing. I think the situation is that localhost was getting blocked as a *third party* domain, which probably shouldn't happen ever. I think the solution to this would be to check if the domain is localhost, and ignore it if so, in contentpolicy.js

**Comment by fiskr** [comment]
Ah, one could just check the location in isBlockableRequest then?
I can make a pull request to fix this if you'd like.

**Comment by cooperq** [comment]
Yea I think we should just check for localhost and 127.0.0.1 in isBlockableRequest
