### ISSUE TITLE
streaming blocked

### ISSUE THREAD

**Issue by technonot** [EFForg/privacybadgerfirefox#603]
I cannot stream 560WGAN (a talk radio station) when Privacy Badger is enabled.  I cannot find a list for "exceptions" for blocked sites.  Can you fix this 'bug'?

**Comment by cooperq** [comment]
You can unblock sites by clicking the privacy badger icon and moving the sliders from red to yellow or green. Or you can disable privacy badger entirely on a given site by clicking 'disable privacy badger for this site'

**Comment by technonot** [comment]
Thank you!!

From Eileen's iPhone
