### ISSUE TITLE
Privacy Badger breaks IMDb

### ISSUE THREAD

**Issue by anonsubmitter** [EFForg/privacybadgerfirefox#606]
Visit an IMDb movie page via a blankrefer.com redirection link, like this one:
http://blankrefer.com/?http://www.imdb.com/title/tt1392190/
Privacy Badger will now block ia.media-imdb.com (layout) and sg.media-imdb.com (search results preview), which will break the site. Changing these two from being completely blocked (red) to just blocking cookies from the domains (yellow) fixes this.

**Comment by anonsubmitter** [comment]
i.media-imdb.com is being blocked on these kinds of pages and it's messing up the layout-
Samples:
http://www.imdb.com/falltv/galleries/moonbeam-city-rm2138762752
http://www.imdb.com/title/tt4158110/board/threads/
http://www.imdb.com/title/tt4158110/board/nest/247641732
http://www.imdb.com/video/imdb/vi57913369

imdb-video.media-imdb.com is being blocked and it prevents videos from loading.
Sample: http://www.imdb.com/video/imdb/vi57913369

Changing i.media-imdb.com and imdb-video.media-imdb.com being completely blocked (red) to just blocking cookies from the domains (yellow) fixes this.

**Comment by cooperq** [comment]
This is the same as #611, in my browser media-imdb.com does not appear to be tracking. I am beginning to think that these are not site bugs, but some deeper bug with your privacy badger setup.

**Comment by anonsubmitter** [comment]
Should I stop reporting site bugs until this is solved? I could maybe just save URLs of new fake site bugs in a .txt file or Google document and re-evaluate them after the bug has been isolated and fixed.

**Comment by cypherpunk** [comment]
As another data point, imdb isn't being blocked here too:

![imdb-sliders](https://cloud.githubusercontent.com/assets/97223/10013896/67fdbdbe-610d-11e5-8d30-eb88c914e8b7.png)

**Comment by cooperq** [comment]
I think that this is fixed by the last update. Closing for now.
