### ISSUE TITLE
Facebook comments blocked on third party sites

### ISSUE THREAD

**Issue by anonsubmitter** [EFForg/privacybadgerfirefox#608]
I know that Facebook is a major tracker, but before Privacy Badger used to be able to display Facebook comment fields on third party sites while still being able to block the tracking as long as the user didn't interact with the comment field. Now Privacy Badger blocks connect.facebook.net, which in turn blocks Facebook comments on third party sites. Changing connect.facebook.net from being completely blocked (red) to just blocking cookies from the domains (yellow) fixes this, but maybe that doesn't prevent tracking by Facebook.

Sample: http://sourcefed.com/oxford-dictionaries-adds-some-dumb-new-words/

**Comment by cooperq** [comment]
I mean, facebook is almost certainly tracking you. I suspect that most of our users would rather not be tracked on facebook than view facebook comments. I am inclined to not add this domain to the yellow list and let users decide on their own if comments are important enough to let facebook track them. I am willing to hear counter arguments, but FWIW connect.facebook.com is already on easyprivacy. I would rather encourage facebook to respect DNT.

**Comment by anonsubmitter** [comment]
Yeah, I am aware of that and if the choice is between Facebook not tracking me and me reading "OMG!!!" and "lol" comments on news articles I rather choose the former. However, didn't Privacy Badger use to be able to block Facebook tracking while still displaying Facebook comments?

**Comment by cooperq** [comment]
I mean, sure, blocking cookies might be enough to block facebook tracking, or it might not, facebook might be embedding 1x1px tracking images. Perhaps before facebook wasn't being blocked but I feel like not yellowlisting facebook is the right choice here. People can override that on a case by case basis if they so choose.

**Comment by anonsubmitter** [comment]
Ok, sounds wise.
