### ISSUE TITLE
Layout and images blocked on Swedish websites for educational courses

### ISSUE THREAD

**Issue by anonsubmitter** [EFForg/privacybadgerfirefox#611]
Layout and images are blocked on these Swedish websites for educational courses:
http://www.distansutbildningar.se/
http://www.hogskoleguiden.se/
http://www.komvuxutbildningar.se/
http://www.kurser.se/
http://www.studentum.se/

Changing these domains from being completely blocked (red) to just blocking cookies from the domains (yellow) fixes this:
d1gns46gm3ntni.cloudfront.net (fixes images)
cdn-static.emg-services.net (fixes layout)
img.emg-services.net (fixes images)

**Comment by cooperq** [comment]
It is strange that these were ever blocked for you. When I test it these show up as not tracking. 
This has also happened to me a couple of other times with things that you have submitted, I am beginning to wonder if you have a strange setup that is causing some false positives.  So lets learn more about your setup. 
What version of firefox are you running? What OS? What other extensions do you have installed? 
Can you create a brand new firefox profile and go visit once again the above mentioned sites with privacy badger installed? Do they still get marked as tracking for you?  
I'm also curious about how you are finding all of these broken sites, you seem to find a wide and diverse array of sites that are not working, which is great! I'm curious about your methodology, are you automating the crawling of sites to find broken ones, or do you just have very diverse browsing habits?

**Comment by anonsubmitter** [comment]
Windows 7
Mozilla Firefox 40.
Only accepting cookies from sites on exception list.
WebRTC disabled (very recent setting)

Add-ons:
BetterPrivacy
Copy As Plain Text
FireShot
Google search link fix
HTTPS Everywhere
Privacy Badger
Self-Destructing Cookies
TabFlick (very recently installed)
uBlock Origin (I can list which filters I use if you want.)


*WORK IN PROGRESS*

**Comment by cooperq** [comment]
creating a fresh profile with firefox portable is fine. There is no need to delete your current profile. You can run firefox with the profile manager like so: `firefox -ProfileManager`

**Comment by cooperq** [comment]
hi @anonsubmitter I am going to close all of your old site bugs since I think they are fixed by the new version of privacy badger. Please re-open or comment on any that are still not fixed by a fresh install of privacy badger.
