### ISSUE TITLE
Unable to install on Firefox for Android

### ISSUE THREAD

**Issue by DaGhostman** [EFForg/privacybadgerfirefox#612]
Unfortunately I am not able to install it on the latest *stable* Firefox for Android (40.0.3) after downloading FF displays a message saying "Unable to install, add-on not compatible with Firefox 40.0.3"

**Comment by cooperq** [comment]
where did you download it from?

**Comment by cooperq** [comment]
Oops sorry I didn't read the bug report close enough! Currently privacy badger is not compatible with firefox for android. See  #271  for more info.
