### ISSUE TITLE
Ukrainian localization

### ISSUE THREAD

**Issue by stenox** [EFForg/privacybadgerfirefox#615]
I'd like to add Ukrainian localization to the Firefox add-on.
Actually, I've already translated the locale file and created PR, but it failed tests.
Please, close that PR and follow me to the right dirrection :)

Thanks!

**Comment by stenox** [comment]
PR Ukrainian localization closed.

**Comment by cooperq** [comment]
Actually the tests were failing not due to your pull request but due to mistake on our end. Please reopen your pull request nad I will re run the tests.
