### ISSUE TITLE
Typo on first run tour

### ISSUE THREAD

**Issue by mlissner** [EFForg/privacybadgerfirefox#618]
If you page to the last step, you'll hit text that looks like:

![screenshot from 2015-09-18 10 57 18](https://cloud.githubusercontent.com/assets/236970/9966908/4cab6e60-5df4-11e5-879b-510e28be5948.png)

Comma is in the wrong place.

**Comment by cooperq** [comment]
Thanks! We are aware of the issue and have already fixed it. It will be updated in the next release!
