### ISSUE TITLE
Unclear README instructions

### ISSUE THREAD

**Issue by fiskr** [EFForg/privacybadgerfirefox#621]
The instructions in the README to setup are:
1. Initialize the Add-on SDK submodule in addon-sdk. `git submodule update --init`
2. Activate the Add-on SDK environment. `cd addon-sdk; . bin/activate; cd ..;`
3. Once the SDK is activated, run `cfx run` to launch a clean Firefox profile with Privacy Badger installed. Run `cfx test` to run tests. `cfx xpi` creates a package (.xpi file) that you can install by loading into Firefox.

This first step doesn't make sense to me - when I run it from the repo it does nothing it seems.
The second step is incoherent-  there is no addon-sdk directory in the repo, and I can't imagine what `. bin/activate` does - though I would guess it is meant to be `./bin/activate`, I assume as a script under the addon-sdk directory.

What am I missing here? Are the instructions wrong, or am I?

**Comment by cooperq** [comment]
Sorry the README is out of date! I will fix it right now.

**Comment by fiskr** [comment]
Perfect - the instructions worked for me, I am able to see my local changes now.

Thanks so much!
