### ISSUE TITLE
Only 5 potential trackers on http://www.gizmodo.co.uk ?

### ISSUE THREAD

**Issue by Golddouble** [EFForg/privacybadgerfirefox#625]
I use Firefox 40.0 with Privacy Badger 1.0.1 (this is the newest version according to https://addons.mozilla.org/de/firefox/addon/privacy-badger-firefox/?src=search# )

I have used Privacy Badger during some weeks and have a list with 356 potential tracking domains so far.

What I have found: 
When I go to the site http://www.gizmodo.co.uk/ Privacy Badger detects 5 potential trackers on this page. All in red or orange:
![5](https://cloud.githubusercontent.com/assets/13977359/10135401/e173efbc-65ed-11e5-9d5e-45f409510444.png)

When I make a new profile in Firefox and install there Privacy Badger 1.0.1 and then go to http://www.gizmodo.co.uk/: Now Privacy Badger detects 30 potential trackers on this page. All green of course:
![30](https://cloud.githubusercontent.com/assets/13977359/10135407/ee329adc-65ed-11e5-818b-3b05b3f33fdc.png)

What I had expected: 
My expectation was, that Privacy Badger detects in both profiles the same number of potential trackers with the difference that in my new profile are all potential trackers green and in my old profile I have green, red and orange trackers.

Is this behaviour normal? Or is there something wrong with my profile?

**Comment by daleeidd** [comment]
PB will only block a tracker once it starts to track you on more than one website – this is how it defines what a tracker is (it may be more complicated). This has not occurred yet on your new profile so it has allowed everything. On your main profile it is blocking Google Tag Manager and Services which normally load other assets, in this case all the other trackers. That is why you are not seeing them in your main profile, Google Tag Manager and Services hasn't had a chance to even load them as it has been blocked itself.

**Comment by Golddouble** [comment]
"That is why you are not seeing them in your main profile, Google Tag Manager and Services hasn't had a chance to even load them as it has been blocked itself."

Oh I see. Thank you for clarification.

**Comment by cooperq** [comment]
what @daleeidd said is correct.
