### ISSUE TITLE
Add yellowlist update preferences

### ISSUE THREAD

**Issue by cypherpunk** [EFForg/privacybadgerfirefox#630]
My suggestion is to add 2 prefs in options:
"Disable auto list update" - for whose, who override (don't use) yellowlist.
"Disable auto list update on startup" - could be useful for people, who open/close their browser very often.

**Comment by jawz101** [comment]
I don't understand.  The list doesn't update unless, say, a new version came out with new exceptions.  I'd just close this one and leave your disable yellowlist request open.

**Comment by cooperq** [comment]
Actually the list gets updated when your browser starts and then again every 24 hours from eff.org 
I am against the "disable auto update list" for the same reasons as I am against the "block all" button. I don't want to give people ways to shoot themselves in the foot.

**Comment by cypherpunk** [comment]
What is the point in list update when browser starts?
Isn't once per day is enough like firefox and addons.mozilla.org do?
Also if user will disable auto list update, he'll still get a new list when new addon version is released.
