### ISSUE TITLE
Cover hidden Elements with cosmetic Filters?

### ISSUE THREAD

**Issue by Golddouble** [EFForg/privacybadgerfirefox#631]
There are some AdBlockers that have a function like "Parse and enforce cosmetic filters." 

Question: 
Does Privacy Badger also cover the restrained components with cosmetic filters?
If yes, my suggestion would be to implement the possibility to deactivate this behaviour.

**Comment by cooperq** [comment]
We do not currently add any cosmetic filters, if we do in the future I would definitely make it optional behavior.
