### ISSUE TITLE
Feature Request: Import / Export of privacy badger settings

### ISSUE THREAD

**Issue by Golddouble** [EFForg/privacybadgerfirefox#632]
I already have a Firefox-Profile with a tracker history of 400 Trackers.

Now I make a new profile in Firefox. Then I install Privacy Badger. Now I would like to have the same settings and "Tracker history" as in the other Profile.
1. Question:
   How can I copy this information from ma first profile?

Guess: Is it enough to only copy the file "store.json" from my old profile to my new profile:
\AppData\Roaming\Mozilla\Firefox\Profiles\w59orosd.Privacy Badger\jetpack\jid1-MnnxcxisBPnSXQ@jetpack\simple-storage ?
1. Question:
   When I want to reset Privacy Badger, is it enough to only replace the current "store.json" through a stored "store.json" which I have obtained after a new installation in a new profile?

**Comment by cooperq** [comment]
you can actually just copy the entire \AppData\Roaming\Mozilla\Firefox\Profiles\w59orosd.Privacy Badger\jetpack\jid1-MnnxcxisBPnSXQ@jetpack\ directory.
To clear storage you could do that, but I should really just add a clear storage button. See #10 

I think we should actually come up with an easier way to export and import you rsettings.

**Comment by andru** [comment]
I've recently switched from Chrome to Vivaldi, and I'd like to bring my PrivacyBadger settings with me. Where are the settings stored for Google Chrome?

**Comment by cooperq** [comment]
@andru you can find your settings in %CHROME CONFIG DIRECTORY%/Default/Local Extension Settings/pkehgijcmpdhfbdbbnkijodmdjhbjlgp

The next version of privacy badger which is being released on the 13th of december will have the ability to import and export settings.
