### ISSUE TITLE
Feature Request: Wildcard for whitelisted domains

### ISSUE THREAD

**Issue by cypherpunk** [EFForg/privacybadgerfirefox#635]
Example: add yandex.ru domain to whitelist - privacy badger still enabled(activated) for www.yandex.ru, maps.yandex.ru, and so on...

**Comment by ILMostro** [comment]
YES! Please.

**Comment by cooperq** [comment]
This feature is in chrome. Just needs to be ported to firefox by someone.

**Comment by ILMostro** [comment]
To clarify: Did the last push resolve this issue for Firefox users or is this Issue closed for another reason?

**Comment by cooperq** [comment]
The list push resolved this issue for firefox uesrs. Fix will be out in the next release.
