### ISSUE TITLE
outbluff the blocking-mechanism which blocks the tracking domains

### ISSUE THREAD

**Issue by Golddouble** [EFForg/privacybadgerfirefox#636]
I heard that there is a prefetching technique in browsers, which allows the browser to establish connections to remote servers, even if the resource from these servers are meant to be blocked.

Question 1: Is this true?
Question 2: Does Privacy Badger care on this in the way that it does disable the prefetching technique?

**Comment by cooperq** [comment]
we are able to block things in prefetch and we do.
