### ISSUE TITLE
Breaks Google Maps tiles

### ISSUE THREAD

**Issue by jsha** [EFForg/privacybadgerfirefox#638]
Steps to reproduce:

Visit 
https://www.google.com/search?q=farley%27s+oakland#q=farley%27s+oakland&rflfq=1&rlha=0&tbm=lcl
![screenshot from 2015-10-05 18 06 08](https://cloud.githubusercontent.com/assets/220205/10297727/caf05d5e-6b8b-11e5-86fd-d5cd149303f1.png)

**Comment by cooperq** [comment]
I suspect that this is due to a bug whre privacy badger was overzealously blocking things, which is fixed as of 1.0.3
You can fix it now by moving all googleapis.com domains to 'cookieblocked'

**Comment by cypherpunk** [comment]
@cooperq 

Is there any detail on changes to the heuristic to combat this overzealous blocking. Would hate to find currently blocked google-related domains (or other organisation's) suddenly unblocked without my input.
