### ISSUE TITLE
Import/Export slider configuration

### ISSUE THREAD

**Issue by joydragon** [EFForg/privacybadgerfirefox#642]
Is there a way to import/export slider configurations? To sync other browsers and/or distribute "secure" configurations?

Thanks

**Comment by cypherpunk** [comment]
@joydragon, you can read @cooperq discussing one way of doing this manually [here](https://github.com/EFForg/privacybadgerfirefox/issues/632#issuecomment-145150331) in a comment to issue #632.

Not "secure" nor syncable but, it may help you for now.

**Comment by cooperq** [comment]
I'm going to call this a duplicate of #632 but I do take it as another request, and I will make it a priority!
