### ISSUE TITLE
version 1.0.3 displays no icon in firefox nightly 20151009, doesn't seem to work

### ISSUE THREAD

**Issue by zipnemud** [EFForg/privacybadgerfirefox#644]
The latest update to privacy badger, version 1.0.3, has meant that it stops working in firefox nightly of 20151009.  It is like the problem reported in ' Icon not showing up in Firefox toolbar #619'.  I don't think that privacy badger is even functioning.  

I see this request there, "Can you also click the menu -> developer -> browser console and tell me if there are any privacy badger related errors in there?".  There are no privacy badger related errors there in my case.  The only symptom I see is the missing icon, so I am not attaching a screen shot.  

The update to privacy badger functions just fine in version 41 of firefox, the latest production version.

This is happening on fedora 21, x86_64.

**Comment by zipnemud** [comment]
The previous version, 1.0.2 worked fine in both firefox production and nightly.  That's why I suspect privacy badger instead of nightly for this.  But nightly changes so rapidly and extensively, that it *could* be from a change in nightly.

**Comment by cooperq** [comment]
@zipnemud can you check if you have multiprocess firefox (E10S) enabled?

**Comment by zipnemud** [comment]
It was disabled.  But there was no change in behavior when I enabled it.  I'm in today's nightly as I type this, and privacy badger is not working, regardless whether I enable multi-process or not.

**Comment by cooperq** [comment]
Okay, I will look into this, thanks!

**Comment by zipnemud** [comment]
Thanks a lot.  Is it possible to downgrade to pb 1.0.2?  Would there be a security risk if I downgraded?  Or, to put it another way, was pb 1.0.3 a security release?

**Comment by phillipsjk** [comment]
Looks like https://www.eff.org/files/privacy-badger-latest.xpi installs 1.0.2 at the time of this writing.

I then went into the add-ons manager to disable version 1.0.3 to avoid any possible conflicts.

It looks like PB is working for me again now (Iceweasel 31.8.0)

**Comment by zipnemud** [comment]
Thanks for looking into this.  I tried going there, but both firefox 41 and nightly tell me that they prevented a site from asking me to install software on my computer.  I tried changing preferences by putting the eff.org site in the exceptions file, and it got a little further.  When I click on the install link at https://www.eff.org/privacybadger it downloads the file, and then tells me it couldn't be installed because of a connection failure.  A lot like the Avast error on that page.

I grabbed the file, but I'm not sure how to install it.    Nothing under .mozilla with that name to replace.  Is it possible that with the new signing scheme for add-ons in firefox, it isn't being allowed because it isn't signed by mozilla?

**Comment by phillipsjk** [comment]
I got the same message, but clicked the "allow" button.

**Comment by zipnemud** [comment]
That's how I got the download to work, but once the download finished, there was only the message about connection failure, without a button.

**Comment by cooperq** [comment]
with 1.0.3 are there any errors that show up in the browser console?

**Comment by cooperq** [comment]
I just tested 1.0.3 in nightly with Multiprocess turned off and it worked like a charm. Are you still having this issue? @zipnemud

**Comment by mlissner** [comment]
Just came to report this bug. I have no icon in Firefox Nightly on Ubuntu Linux. Not in the toolbar, not in the "Customize Nightly" interface. No messages in the dev console that I've seen. Maybe it's working and the icon is missing? Who knows?

**Comment by cooperq** [comment]
mlissner, can you please tell me which version numbers you have and also tell me if disabling multiprocess firefox fixes the problem?

**Comment by mlissner** [comment]
Sure:

 - Disabling multi-process had no affect.
 - I have version 1.0.3 of Privacy Badger

**Comment by cooperq** [comment]
what version of nightly do you have?

**Comment by mlissner** [comment]
Oh, I didn't think you needed that b/c it's nightly: `44.0a1 (2015-10-18)`

**Comment by cooperq** [comment]
please update to the latest version of nightly. I just double checked on my computer and everything seems to be working fine.

**Comment by mlissner** [comment]
I'm sorry, I honestly don't know how at this point. I have [the PPA][1] installed, but `dpkg -l firefox-trunk` informs me that the version in the repo is only at 44:
```
↪ dpkg -l firefox-trunk
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name                                                           Version                              Architecture                         Description
+++-==============================================================-====================================-====================================-=================================================================================================================================
ii  firefox-trunk                                                  44.0~a1~hg20151017r268173-0ubuntu1~u amd64                                Safe and easy web browser from Mozilla
```

At some point this was working, but I have no idea why it isn't updating, and adding and removing the PPA didn't do it, updating my sources didn't do it...I have no idea anymore. Sorry.

[1]: https://launchpad.net/~ubuntu-mozilla-daily/+archive/ubuntu/ppa?field.series_filter=vivid

**Comment by cooperq** [comment]
Closing this issue for now, I suspect that the problem is with an old version of nightly and not with privacy badger.

**Comment by zipnemud** [comment]
Sorry for the missed response earlier.  My email provider was collateral damage for a few days in a DDOS attack for extortion purposes against their service provider.  Just came back.

You're right.  Privacy badger is working again in the latest version of firefox nightly.  It couldn't have been that it was stale, since I have a local hg repository, and update it daily.  But whatever the reason, I turned it on again after your email, and away it went.  Thank you for being so responsive.

**Comment by cooperq** [comment]
Glad to hear it! Thanks for submitting a bug report!

**Comment by mlissner** [comment]
On my end, I finally figured out that the PPA that most people use to run Firefox Nightly hasn't had a working build in about a month. That's why I am stuck on an old version. I suspect a LOT of people don't realize this is currently happening.
