### ISSUE TITLE
Dashboard does not show up when I click the icon

### ISSUE THREAD

**Issue by jim-rees** [EFForg/privacybadgerfirefox#645]
FF 41 on linux. When I click on the PB icon in the toolbar, my title bar flashes but nothing else happens and I do not get the dashboard. I have the same problem with ublock, but it provides a "show dashboard" button on its "add-ons" tab. In PB I don't know of any way to open the dashboard other than to click on the icon.

**Comment by cooperq** [comment]
Can you please open the developer console by clicking the Firefox menu and then "Developer"->"Browser console" and search for privacybadger and tell me if there are any errors that occour when you try to open the icon?

**Comment by jim-rees** [comment]
No, nothing shows up in Browser Console at all.

I wonder if some of my config settings are preventing the dashboard from opening, for example I've got "browser.link.open_newwindow.restriction=0". I'll try resetting some things and disabling other extensions. Regardless, it would be nice if PB had a "open dashboard" button on its "add-ons" tab.

**Comment by cooperq** [comment]
We probably wont add that because it would require messing around with XUL which is about to be disabled for extension developers. Please try changing the setting and let me know if that fixes it.

**Comment by jim-rees** [comment]
I've been unable to figure out what's causing this on my end. But since µblock does the same thing it's apparently not a bug in PB, so I'm going to close this.
