### ISSUE TITLE
it is uninstalled automatically, tracker profiles gone

### ISSUE THREAD

**Issue by mabkenar** [EFForg/privacybadgerfirefox#654]
This happened to me a few times, last time it was a week ago. But I don't know how to reproduce it.
I use privacy badger on a laptop and a desktop that are synced together via Firefox sync (both running Ubuntu 14.04). I also have a Fennec browser on Android which is synced with the other two, but with no PrivacyBadger installed on it.
I suddenly notice that Privacy Badger is removed from my list of installed Firefox add-ons on both laptop and desktop. The toolbar button is of course also gone. The only way I can bring it back is to install it again via https://www.eff.org/privacybadger. But when I do, all trackers previously detected are gone: I get a vanilla profile, and all the trackers that I have manually blocked are active again.

**Comment by cooperq** [comment]
I believe that this is an issue with Firefox sync and is outside of our control. Sorry!
