### ISSUE TITLE
Version 1.0.3 unsigned warnings from Firefox 41.0.2

### ISSUE THREAD

**Issue by Flupsy** [EFForg/privacybadgerfirefox#656]
I noticed today that Firefox 41.0.2 (on Windows 10) is telling me that Privacy Badger 1.0.3 is unsigned on the `about:plugins` page.

When I remove it and try to download it again, I get the unsigned warning from Firefox:

![badger-unsigned](https://cloud.githubusercontent.com/assets/1742755/10631203/40488186-77d4-11e5-8000-14408c41d37b.png)

**Comment by cypherpunk** [comment]
Firefox 41.0.2
Privacy Badger 1.0.3 (auto-updated from 1.0.2 which was originally installed from eff.org)
Windows 7 32-bit

I have the same issue but mine only started after Privacy Badger was auto-updated in Firefox. The previous version 1.0.2 had no warnings.

This is what the Add-ons list in Firefox says about PB 1.0.3:

![privacy-badger-warning](https://cloud.githubusercontent.com/assets/97223/10654755/31b92480-7866-11e5-918e-c1f38bb0a8d6.png)

**Comment by ardrigh** [comment]
This extension is unsigned, so the Firefox now warns of any extension that is not signed.

EFF HTTPS Everywhere developers are aware of this change.
It has been updated for Firefox signing, as per the changelog: https://www.eff.org/files/Changelog.txt

    Firefox 5.1.0
      * Signed by AMO so it won't get a warning in Firefox

This extension simply needs the same signing update as HTTPS Everywhere.

**Comment by cypherpunk** [comment]
@ardrigh 
Both @Flupsy  and myself are aware that the 1.0.3 extension is unsigned. And that Firefox now issues a warning in this case. Just informing the developers that this issue exists in the 1.0.3 release from eff.org.

**Comment by cooperq** [comment]
this issue should be fixed now, I believe we mistakenly uploaded a broken copy of privacy badger, please confirm.

**Comment by ardrigh** [comment]
I got an update from the website, the version now shows as 1.0.2
Is that intended?

The warning about being unsigned has gone.

**Comment by Learn-Digital-Audio** [comment]
I am using latest Privacy Badger 1.0.3 and latest Firefox 42.0 and it still says it could not be verified. Hope this gets fixed ASAP as it will put users off and make them uninstall right away. Cheers.

**Comment by cooperq** [comment]
Please try clicking the check for updates button in the firefox addons page and see if that fixes this issue?

**Comment by Learn-Digital-Audio** [comment]
no updates found...

**Comment by cooperq** [comment]
okay please try one other thing, I think that you may have gotten a broken release we accidentally uploaded. Please remove privacy badger and install it again from https://eff.org/privacybadger
This should fix the issue.

**Comment by ardrigh** [comment]
I removed the extension from Firefox, closed it, then re-opened and installed the extension from the website.

Now shows as 1.0.3 and the warning has gone. Thanks!

**Comment by cooperq** [comment]
Great! @Learn-Digital-Audio this should fix the issue for you as well. 
As for the icon being gone that will be fixed in the next release.

**Comment by Learn-Digital-Audio** [comment]
it worked, but no icon sucks, i love the badger image!

why do i need to use the home page and not the mozilla addons page? how come there are 2 separate download sites with different file versions? i found that the mozilla one was out of date in the past. if i were linking this software for a friend i would always send them to the official mozilla site.

**Comment by cooperq** [comment]
Either one is fine, they will both normally have the same version, the reason we self host as well as use AMO is that self hosting allows us to sign the package with our own key, that way we can vouch for the integrity of the package. The other downside to AMO hosting is that mozilla occasionally takes an unreasonably long time to approve of a package. The reason we use AMO anyway is because some people only find packages via AMO.
