### ISSUE TITLE
firstRun.html not displaying properly

### ISSUE THREAD

**Issue by Flupsy** [EFForg/privacybadgerfirefox#657]
After I install 1.0.3 (ignoring the unsigned warning in #656), the `firstRun.html` page looks like this:

![badger-first-run](https://cloud.githubusercontent.com/assets/1742755/10631374/80921634-77d5-11e5-8cfd-5abb63833707.png)

Firefox 41.0.2 on Windows 10; Adblock Plus and HTTPS-Everywhere also installed.

**Comment by cypherpunk** [comment]
Firefox 41.0.2
Privacy Badger 1.0.3 (auto-updated from 1.0.2 which was originally installed from eff.org)
Windows 7 32-bit

I get this as well. Seems to be an issue with the version 1.0.3 from eff.org only AFAICT.

**Comment by rugk** [comment]
Can confirm this (with v1.0.3).

When choosing the stylesheet options in the dev console it also shows me an error that a particular CSS file could not be loaded:
![style](https://cloud.githubusercontent.com/assets/11966684/10689840/2efe3668-797e-11e5-9d9d-dfdae221b016.PNG)

**Comment by cooperq** [comment]
this issue should be fixed now, I believe we mistakenly uploaded a broken copy of privacy badger, please confirm.

**Comment by cooperq** [comment]
if this is not fixed please uninstall and reinstall privacy badger to fix the issue.
