### ISSUE TITLE
Overblocked domain

### ISSUE THREAD

**Issue by sketboy12** [EFForg/privacybadgerfirefox#659]
Hello,

I would like to report what I believe to be some overblocked domains I found out browsing.
Here are the concerned domains : 
img.xooimage.com
imgX.xooimage.com , where X is a positive integer
Unless I am mistaken, these domains are the ones who provide most of the pictures on internet forums hosted by xooit. Privacy Badger tends to completely block these domains (red switch) whereas they are needed to correctly display the webpage. Thus maybe they should be yellow listed (I noticed no display malfunctions with yellow switch applied).

Have a good day,
I really enjoy Privacy Badger, thank you in advance, keep up the good work !

sketboy12
Win8.1, Firefox 41.0.2

**Comment by cypherpunk** [comment]
I doubt PB can be accused of overblocking.

Some websites may be built in such a way that blocking online tracking breaks the site. This is inconvenient for users of the site and the website owners are hoping that the inconvenience would be enough to get users to abandon attempts to block online tracking (or at least whitelist the offending website). I just use a different website...

I can't say definitely that these specific domains are tracking (or have ever tracked or might start tracking) users using cookies, javscript or other methods but, it pays to remember that:

> If it looks like a duck, swims like a duck, and quacks like a duck, then it probably is a duck.
> -- James Whitcomb Riley

Anyway, you can simply adjust the sliders  for the listed domains to YELLOW yourself.

**Comment by SwartzCr** [comment]
without a privacy policy from xooimage.com we'd be reluctant to add it to the yellowlist list. Instead you should go into the privacy badger options (click that gear icon) and set xooimage.com to yellow.
This is different than changing it on any one site since it will yellowlist the whole domain, rather than just a specific subdomain.
Feel free to re-open this issue if you still run into trouble, but I think that should work for you :)

**Comment by cypherpunk** [comment]
@SwartzCr 
Is there a list of domains that are yellow-listed (or indeed white/green-listed) by default somewhere?

The idea that all a publisher needs to do to be eligible for yellow-listing is to include a privacy policy file on their website is worrying. The DNT fiasco taught everyone that publishers cannot be trusted to do what they promise or claim until and unless
- their compliance can be monitored and
- non-compliance results in a penalty (e.g. resumption of blocking in PB)
