### ISSUE TITLE
No icon for PB in Firefox extensions manager

### ISSUE THREAD

**Issue by antistress** [EFForg/privacybadgerfirefox#661]
Using PB 1.0.3 on Firefox 43.0a2, there's no icon for PB in Firefox extensions manager.
Same on anotehr system, with Firefox ESR and PB 1.0.3

See : http://img11.hostingpics.net/pics/953672firefoxaddonsmanager.png

Thanks

**Comment by cooperq** [comment]
Thank you, we hope to fix this in the next release.
