### ISSUE TITLE
Privacy Badger doesn't work under a Fedora Linux compiled Nightly. 

### ISSUE THREAD

**Issue by TheJohnTalent** [EFForg/privacybadgerfirefox#662]
If you compile it simply does not work.

**Comment by cooperq** [comment]
Can you give more details please? In what way does it not work? Are there any errors present in the development console? Do you have multiprocess firefox enabled? If you download a precompiled version of nightly does it display the same issues?

**Comment by TheJohnTalent** [comment]
I copied from a working non-compiled binary package firefox.
no errors when I had access to it under 'Nightly' but it simply didn't raise any potential problem siteson *any* sites. Now it simply doesn't show up in my right side icon list after trying to uninstall and reinstallPB.
 
So try a migration from a working binary package firefox to a typical plain vanilla compiled nightlyunder Linux. 
I'm not sure hot to check for multiprocess firefox.
Again, precompiled packed firefox works wonderfully!
John
 


     On Monday, November 2, 2015 8:00 PM, Cooper Quintin <notifications@github.com> wrote:
   

 Can you give more details please? In what way does it not work? Are there any errors present in the development console? Do you have multiprocess firefox enabled? If you download a precompiled version of nightly does it display the same issues?—

**Comment by cooperq** [comment]
do other addons work in your compiled version, just not privacy badger?
to disable multiprocess firefox click on the Firefox menu -> preferences and then uncheck the box that says "Enable Multiprocess firefox nightly"

**Comment by TheJohnTalent** [comment]
I have no use for add ons so I don't know.I unchecked multprocess. reinstalled PB 'successfully' but still no icon.I'm sure this is easy to reduplicate on your side.


     On Thursday, November 5, 2015 4:29 PM, Cooper Quintin <notifications@github.com> wrote:
   

 do other addons work in your compiled version, just not privacy badger?
to disable multiprocess firefox click on the Firefox menu -> preferences and then uncheck the box that says "Enable Multiprocess firefox nightly"—

**Comment by TheJohnTalent** [comment]
I may or may not have said it, but I also copied my .mozilladirectory from an old setup that was Binary but was also possiblya Nightly *after* I had Privacy Badger working on either setup(I forget which).
At that time of starting the latest 'Nightly' it never worked from then on.
 


     On Thursday, November 5, 2015 5:40 PM, john Lutz <lutz.john@yahoo.com> wrote:
   

 I have no use for add ons so I don't know.I unchecked multprocess. reinstalled PB 'successfully' but still no icon.I'm sure this is easy to reduplicate on your side.


     On Thursday, November 5, 2015 4:29 PM, Cooper Quintin <notifications@github.com> wrote:
   

 do other addons work in your compiled version, just not privacy badger?
to disable multiprocess firefox click on the Firefox menu -> preferences and then uncheck the box that says "Enable Multiprocess firefox nightly"—

**Comment by TheJohnTalent** [comment]
Okay, I started Firefox binary that came with Fedora and Privacy Badgerworked perfectly! I still can't use it with Nightly after having tried it afterwards.(This is the same exact .mozilla setup and user, just Compiled with all defaults).Permissions somewhere perhaps?
I start Compiled from '/home/john/Downloads/2015/computer/ffirefox/mozilla-central/obj-x86_64-unknown-linux-gnu/dist/bin/firefox' 


     On Thursday, November 5, 2015 8:07 PM, john Lutz <lutz.john@yahoo.com> wrote:
   

 I may or may not have said it, but I also copied my .mozilladirectory from an old setup that was Binary but was also possiblya Nightly *after* I had Privacy Badger working on either setup(I forget which).
At that time of starting the latest 'Nightly' it never worked from then on.
 


     On Thursday, November 5, 2015 5:40 PM, john Lutz <lutz.john@yahoo.com> wrote:
   

 I have no use for add ons so I don't know.I unchecked multprocess. reinstalled PB 'successfully' but still no icon.I'm sure this is easy to reduplicate on your side.


     On Thursday, November 5, 2015 4:29 PM, Cooper Quintin <notifications@github.com> wrote:
   

 do other addons work in your compiled version, just not privacy badger?
to disable multiprocess firefox click on the Firefox menu -> preferences and then uncheck the box that says "Enable Multiprocess firefox nightly"—

**Comment by cooperq** [comment]
Yea, it's hard to say why the compiled version isn't working, but I suspect that it is an issue with the compilation process and not with privacy badger. If you could test some other addons with your compiled version of firefox and see if those work it might be helpful, but I don't think I am going to be able to debug this one. Sorry.

**Comment by TheJohnTalent** [comment]
please give me some save addon names to test. I don't trust em. People I support use themand it screws up Firefox altogether.
 


     On Friday, November 6, 2015 2:12 PM, Cooper Quintin <notifications@github.com> wrote:
   

 Yea, it's hard to say why the compiled version isn't working, but I suspect that it is an issue with the compilation process and not with privacy badger. If you could test some other addons with your compiled version of firefox and see if those work it might be helpful, but I don't think I am going to be able to debug this one. Sorry. —

**Comment by cooperq** [comment]
how about https everywhere, it's another addon from EFF.

**Comment by TheJohnTalent** [comment]
https everwhere seems to work fine in both Nightly Compile and Binary Fedora.Initially I installed it from Binary Fedora too. The functionality like the icon and menu looks like it's therebut maybe you can tell me for sure to go to a site and see unprotected results or something?

 


     On Friday, November 6, 2015 2:59 PM, Cooper Quintin <notifications@github.com> wrote:
   

 how about https everywhere, it's another addon from EFF. —

**Comment by TheJohnTalent** [comment]
Trying a different linux distro and nightly firefox. works fine. I even copied the .mozilladirectory from the one I had trouble with. so it's probably the distro/libs, not firefox.
I'm also noticing traffic from google, cloudfront.net and facebook even though I'm notdoing anything or have anything open and have no duckduckgo.com as my defaultsearch engine in firefox.
 


    On Friday, November 6, 2015 5:36 PM, john Lutz <lutz.john@yahoo.com> wrote:
 

 https everwhere seems to work fine in both Nightly Compile and Binary Fedora.Initially I installed it from Binary Fedora too. The functionality like the icon and menu looks like it's therebut maybe you can tell me for sure to go to a site and see unprotected results or something?

 


     On Friday, November 6, 2015 2:59 PM, Cooper Quintin <notifications@github.com> wrote:
   

 how about https everywhere, it's another addon from EFF. —

**Comment by cooperq** [comment]
Sounds like it's some problem with the distro or libraries then and not with privacy badger. I'm sorry but I'm afraid this is out of my hands at this point. Good luck!
