### ISSUE TITLE
status screen becomes useless when URL is very long due to string shortening

### ISSUE THREAD

**Issue by cypherpunk** [EFForg/privacybadgerfirefox#675]
i was on gmail and saw the badger showing lots of elements blocked. 
i got curious and opened it.
i found many URLs shortened and - when moused-over - printed in full.
but not this one.
this is what the badger-popup displays:
   m....googleusercontent.com
and this is what you get when mousing over:
   mail-attachment.googleusercontent....
which could basically be mail-attachment.googleusercontent.fromTheMafiagooglecontent.com

you got my permission to make the badger bigger.
cheers!
chris :)

**Comment by cooperq** [comment]
most urls are a bit shorter than this, and the status screen is already about as wide as I am willing to make it. Sorry for the inconvenience though!
