### ISSUE TITLE
Privacy badger and Ad-Muncher.

### ISSUE THREAD

**Issue by mooota1514** [EFForg/privacybadgerfirefox#679]
Hi is it ok to run privacy badger with Ad-muncher because when i click top right of my screen and look at the trackers that have been blocked i get "intercept ..........admuncher.com

**Comment by cooperq** [comment]
It should be fine to run privacy badger with ad muncher. can you send a screenshot of the strange behavior you are seeing?

**Comment by mooota1514** [comment]
Hi here is the screen shot
http://i551.photobucket.com/albums/ii479/mattytun/20151208_143810_zpsn2rxovde.jpg

**Comment by cooperq** [comment]
It looks like ad muncher is (ironically) injecting third party content (in this case from admuncher.com) into the sites you visit for it's normal operation. Privacy Badger is working like it is supposed to and blocking any third party (in this case intercept.(something).admuncher.com) that appears like it could be tracking you. It is not clear why admuncher is doing this and it could be perfectly benign, or it might not be.

**Comment by mooota1514** [comment]
Think ill remove Ad-Muncher.
