### ISSUE TITLE
Privacy Badger Logo is missing

### ISSUE THREAD

**Issue by Draxler** [EFForg/privacybadgerfirefox#685]
Win OS / Latest FF 42 / Latest Privacy Badger 1.0.3

> FF Add-ons page: 

- Extensions page (Logo/icon is missing )  http://b.1339.cf/fwdyrwo.PNG

- Privacy Badger Detail page (Logo/icon is missing )  http://b.1339.cf/jxzldov.PNG

**Comment by anonsubmitter** [comment]
I am experiencing this as well in one of my three Privacy Badger 1.0.3 Firefox installations.

**Comment by cooperq** [comment]
already fixed, will be in the next release.
