### ISSUE TITLE
Filter Settings' block and allow icons' tooltip text is truncated: "Move the slider left to block a"

### ISSUE THREAD

**Issue by cpeterso** [EFForg/privacybadgerfirefox#686]
Mouse over the red :no_entry_sign: icon. The tooltip text is truncated to "Move the slider left to block a", missing the word "domain". Mouse over the green ✅ icon. The tooltip text is truncated to "Move the slider right to allow a", missing the word domain.

I am using Privacy Badger 1.0.3 in Firefox 42. Here is a screenshot:

![privacy_badger_screenshot](https://cloud.githubusercontent.com/assets/629193/11436857/86f918c6-949d-11e5-9388-f13c019bcc92.png)

**Comment by cooperq** [comment]
already fixed. Will be in the next release.
