### ISSUE TITLE
Privacy Badger hasn't been working since 43.0b7

### ISSUE THREAD

**Issue by livingsilver94** [EFForg/privacybadgerfirefox#690]
Like other addons (i.e. AdBlock Plus and NoSquint), PB is not working anymore. I assume Mozilla has changed a lot of code about addons, so they need to be updated.

**Comment by cooperq** [comment]
Can you please provide more details? What exactly is not working - Are the other extensions breaking in the same way? What are your settings, etc. etc. Please provide as much details as possible.

**Comment by livingsilver94** [comment]
Privacy Badger is blocking nothing, and if you click on its icon on the Firefox upper bar, the only item working in the menu is "Frequently Asked Questions" link. **Every** other button doesn't trigger the proper event. Furthermore, instead of tracking sites list I see a constant "Loading..." string. What's curious is that the cited menu will work flawlessly if I browse to a chrome:// page.

AdBlock Plus just doesn't... block, and NoSquint both breaks Firefox zooming feature and isn't working as it should, that is recording a per-site zoom level.

Here's a JSON I got from about:support page

{
  "application": {
    "name": "Firefox",
    "version": "43.0",
    "buildID": "20151208200940",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:43.0) Gecko/20100101 Firefox/43.0",
    "safeMode": false,
    "updateChannel": "beta",
    "supportURL": "https://support.mozilla.org/1/firefox/43.0/WINNT/en-US/",
    "numTotalWindows": 1,
    "numRemoteWindows": 1,
    "remoteAutoStart": true
  },
  "modifiedPreferences": {
    "accessibility.typeaheadfind.flashBar": 0,
    "browser.cache.disk.smart_size.first_run": false,
    "browser.cache.disk.hashstats_reported": 1,
    "browser.cache.frecency_experiment": 4,
    "browser.cache.disk.filesystem_reported": 1,
    "browser.cache.disk.capacity": 358400,
    "browser.cache.disk.smart_size.use_old_max": false,
    "browser.download.importedFromSqlite": true,
    "browser.download.manager.alertOnEXEOpen": true,
    "browser.fixup.domainwhitelist.3.600": true,
    "browser.places.smartBookmarksVersion": 7,
    "browser.search.suggest.enabled": false,
    "browser.search.useDBForOrder": true,
    "browser.sessionstore.upgradeBackup.latestBuildID": "20151208200940",
    "browser.startup.homepage_override.mstone": "43.0",
    "browser.startup.homepage": "https://www.google.it/",
    "browser.startup.homepage_override.buildID": "20151208200940",
    "browser.tabs.warnOnOpen": false,
    "browser.tabs.warnOnClose": false,
    "browser.tabs.warnOnCloseOtherTabs": false,
    "browser.tabs.remote.autostart": true,
    "browser.urlbar.suggest.searches": true,
    "browser.urlbar.maxRichResults": 15,
    "browser.urlbar.userMadeSearchSuggestionsChoice": true,
    "browser.zoom.siteSpecific": false,
    "dom.apps.reset-permissions": true,
    "dom.mozApps.used": true,
    "extensions.lastAppVersion": "43.0",
    "font.internaluseonly.changed": false,
    "gfx.crash-guard.glcontext.gfx.driver-init.webgl-angle-force-d3d11": false,
    "gfx.crash-guard.d3d11layers.appVersion": "43.0",
    "gfx.driver-init.appVersion": "42.0",
    "gfx.crash-guard.glcontext.gfx.driver-init.direct3d11-angle": true,
    "gfx.crash-guard.status.d3d9video": 2,
    "gfx.crash-guard.d3d11layers.driverVersion": "15.300.1025.1001",
    "gfx.crash-guard.d3d11layers.deviceID": "0x67b1",
    "gfx.driver-init.deviceID": "0x67b1",
    "gfx.driver-init.driverVersion": "15.201.1151.1005",
    "gfx.driver-init.status": 2,
    "gfx.crash-guard.glcontext.gfx.driver-init.webgl-angle-try-d3d11": true,
    "gfx.crash-guard.glcontext.gfx.driver-init.webgl-angle": true,
    "gfx.crash-guard.d3d11layers.feature-d3d11": true,
    "gfx.crash-guard.status.glcontext": 2,
    "gfx.crash-guard.d3d11layers.feature-d2d": true,
    "gfx.crash-guard.status.d3d11layers": 2,
    "gfx.driver-init.feature-d3d11": true,
    "gfx.crash-guard.glcontext.gfx.driver-init.webgl-angle-force-warp": false,
    "gfx.driver-init.feature-d2d": true,
    "gfx.direct3d.last_used_feature_level_idx": 0,
    "media.gmp-eme-adobe.lastUpdate": 1445895641,
    "media.webrtc.debug.aec_log_dir": "C:\\Users\\fabio\\AppData\\Local\\Temp/",
    "media.mediasource.webm.enabled": true,
    "media.webrtc.debug.log_file": "C:\\Users\\fabio\\AppData\\Local\\Temp/WebRTC.log",
    "media.gmp-gmpopenh264.lastUpdate": 1447770823,
    "media.gmp-eme-adobe.enabled": false,
    "media.gmp-eme-adobe.abi": "x86_64-msvc",
    "media.hardware-video-decoding.failed": false,
    "media.gmp-gmpopenh264.version": "1.5.1",
    "media.gmp-manager.lastCheck": 1449770314,
    "media.gmp-eme-adobe.version": "15",
    "media.gmp-gmpopenh264.abi": "x86_64-msvc",
    "media.gmp-manager.buildID": "20151208200940",
    "mousewheel.withcontrolkey.action": 3,
    "network.predictor.cleaned-up": true,
    "network.cookie.prefsMigrated": true,
    "network.cookie.cookieBehavior": 1,
    "places.history.expiration.transient_current_max_pages": 104858,
    "places.database.lastMaintenance": 1449574645,
    "plugin.importedState": true,
    "plugin.disable_full_page_plugin_for_types": "application/pdf",
    "plugin.state.flash": 0,
    "print.printer_Microsoft_Print_to_PDF.print_evenpages": true,
    "print.printer_Microsoft_Print_to_PDF.print_headercenter": "",
    "print.printer_Microsoft_Print_to_PDF.print_plex_name": "",
    "print.printer_Microsoft_Print_to_PDF.print_unwriteable_margin_bottom": 0,
    "print.printer_Microsoft_Print_to_PDF.print_margin_left": "0.5",
    "print.printer_Microsoft_Print_to_PDF.print_orientation": 0,
    "print.printer_Microsoft_Print_to_PDF.print_duplex": 1515870810,
    "print.printer_Microsoft_Print_to_PDF.print_headerright": "&U",
    "print.printer_Microsoft_Print_to_PDF.print_resolution_name": "",
    "print.printer_Microsoft_Print_to_PDF.print_unwriteable_margin_top": 0,
    "print.printer_Microsoft_Print_to_PDF.print_bgcolor": false,
    "print.printer_Microsoft_Print_to_PDF.print_scaling": "  1,00",
    "print.printer_Microsoft_Print_to_PDF.print_footerright": "&D",
    "print.printer_Microsoft_Print_to_PDF.print_edge_left": 0,
    "print.printer_Microsoft_Print_to_PDF.print_headerleft": "&T",
    "print.printer_Microsoft_Print_to_PDF.print_page_delay": 50,
    "print.printer_Microsoft_Print_to_PDF.print_command": "",
    "print.printer_Microsoft_Print_to_PDF.print_footerleft": "&PT",
    "print.printer_Microsoft_Print_to_PDF.print_footercenter": "",
    "print.printer_Microsoft_Print_to_PDF.print_downloadfonts": false,
    "print.printer_Microsoft_Print_to_PDF.print_paper_size_unit": 1,
    "print.printer_Microsoft_Print_to_PDF.print_reversed": false,
    "print.printer_Microsoft_Print_to_PDF.print_oddpages": true,
    "print.printer_Microsoft_Print_to_PDF.print_margin_bottom": "0.5",
    "print.printer_Microsoft_Print_to_PDF.print_paper_data": 9,
    "print.printer_Microsoft_Print_to_PDF.print_resolution": 1515870810,
    "print.printer_Microsoft_Print_to_PDF.print_paper_name": "",
    "print.printer_Microsoft_Print_to_PDF.print_unwriteable_margin_left": 0,
    "print.printer_Microsoft_Print_to_PDF.print_margin_top": "0.5",
    "print.printer_Microsoft_Print_to_PDF.print_margin_right": "0.5",
    "print.printer_Microsoft_Print_to_PDF.print_edge_bottom": 0,
    "print.printer_Microsoft_Print_to_PDF.print_edge_right": 0,
    "print.printer_Microsoft_Print_to_PDF.print_paper_size_type": 0,
    "print.printer_Microsoft_Print_to_PDF.print_shrink_to_fit": true,
    "print.printer_Microsoft_Print_to_PDF.print_edge_top": 0,
    "print.printer_Microsoft_Print_to_PDF.print_bgimages": false,
    "print.printer_Microsoft_Print_to_PDF.print_to_file": false,
    "print.printer_Microsoft_Print_to_PDF.print_colorspace": "",
    "print.printer_Microsoft_Print_to_PDF.print_paper_width": "  8,50",
    "print.printer_Microsoft_Print_to_PDF.print_unwriteable_margin_right": 0,
    "print.printer_Microsoft_Print_to_PDF.print_paper_height": " 11,00",
    "print.printer_Microsoft_Print_to_PDF.print_in_color": true,
    "privacy.donottrackheader.value": 1,
    "privacy.donottrackheader.enabled": true,
    "privacy.sanitize.migrateFx3Prefs": true,
    "security.default_personal_cert": "Select Automatically",
    "security.disable_button.openCertManager": false,
    "storage.vacuum.last.index": 1,
    "storage.vacuum.last.places.sqlite": 1447785938,
    "ui.osk.debug.keyboardDisplayReason": "IKPOS: Touch screen not found."
  },
  "lockedPreferences": {},
  "graphics": {
    "numTotalWindows": 1,
    "numAcceleratedWindows": 1,
    "windowLayerManagerType": "Direct3D 11",
    "windowLayerManagerRemote": true,
    "supportsHardwareH264": "Yes",
    "adapterDescription": "AMD Radeon R9 200 Series",
    "adapterVendorID": "0x1002",
    "adapterDeviceID": "0x67b1",
    "adapterSubsysID": "00000000",
    "adapterRAM": "4095",
    "adapterDrivers": "aticfx64 aticfx64 aticfx64 amdxc64 aticfx32 aticfx32 aticfx32 amdxc32 atiumd64 atidxx64 atidxx64 atiumdag atidxx32 atidxx32 atiumdva atiumd6a atitmm64",
    "driverVersion": "15.300.1025.1001",
    "driverDate": "11-29-2015",
    "adapterDescription2": "",
    "adapterVendorID2": "",
    "adapterDeviceID2": "",
    "adapterSubsysID2": "",
    "adapterRAM2": "",
    "adapterDrivers2": "",
    "driverVersion2": "",
    "driverDate2": "",
    "isGPU2Active": false,
    "direct2DEnabled": true,
    "directWriteEnabled": true,
    "directWriteVersion": "10.0.10586.0",
    "clearTypeParameters": "Gamma: 2200 Pixel Structure: R ClearType Level: 100 Enhanced Contrast: 50 ",
    "webglRenderer": "Google Inc. -- ANGLE (AMD Radeon R9 200 Series Direct3D11 vs_5_0 ps_5_0)",
    "info": {
      "AzureCanvasBackend": "direct2d 1.1",
      "AzureSkiaAccelerated": 0,
      "AzureFallbackCanvasBackend": "cairo",
      "AzureContentBackend": "direct2d 1.1"
    }
  },
  "javaScript": {
    "incrementalGCEnabled": true
  },
  "accessibility": {
    "isActive": false,
    "forceDisabled": 0
  },
  "libraryVersions": {
    "NSPR": {
      "minVersion": "4.10.10",
      "version": "4.10.10"
    },
    "NSS": {
      "minVersion": "3.20.1 Basic ECC",
      "version": "3.20.1 Basic ECC"
    },
    "NSSUTIL": {
      "minVersion": "3.20.1",
      "version": "3.20.1"
    },
    "NSSSSL": {
      "minVersion": "3.20.1 Basic ECC",
      "version": "3.20.1 Basic ECC"
    },
    "NSSSMIME": {
      "minVersion": "3.20.1 Basic ECC",
      "version": "3.20.1 Basic ECC"
    }
  },
  "userJS": {
    "exists": false
  },
  "crashes": {
    "submitted": [],
    "pending": 0
  },
  "extensions": [
    {
      "name": "DownThemAll!",
      "version": "2.0.18.1-signed.1-let-fixed",
      "isActive": true,
      "id": "{DDC359D1-844A-42a7-9AA1-88A850A938A8}"
    },
    {
      "name": "Gmail Notifier (restartless)",
      "version": "0.5.8",
      "isActive": true,
      "id": "jid0-GjwrPchS3Ugt7xydvqVK4DQk8Ls@jetpack"
    },
    {
      "name": "HTTPS-Everywhere",
      "version": "5.1.0",
      "isActive": true,
      "id": "https-everywhere@eff.org"
    },
    {
      "name": "I don't care about cookies",
      "version": "2.5.0",
      "isActive": true,
      "id": "jid1-KKzOGWgsW3Ao4Q@jetpack"
    },
    {
      "name": "Privacy Badger",
      "version": "1.0.5",
      "isActive": true,
      "id": "jid1-MnnxcxisBPnSXQ@jetpack"
    },
    {
      "name": "Private Tab",
      "version": "0.1.8.1",
      "isActive": true,
      "id": "privateTab@infocatcher"
    },
    {
      "name": "Speed Dial",
      "version": "0.9.6.18",
      "isActive": true,
      "id": "{64161300-e22b-11db-8314-0800200c9a66}"
    },
    {
      "name": "NoSquint",
      "version": "2.1.9.1-signed",
      "isActive": false,
      "id": "nosquint@urandom.ca"
    }
  ],
  "experiments": []
}

**Comment by livingsilver94** [comment]
Any news?

**Comment by tanriol** [comment]
@livingsilver94, I've seen a similar problem with Privacy Badger when multi-process mode (aka e10s) is enabled in preferences. If this is the case (please check in Preferences - General - Startup), this bug is already known as #208 (with seemingly no one working on it).

**Comment by livingsilver94** [comment]
Hell, you're right! I've set browser.tabs.remote.autostart to false and now everthing's fine! Thank you!
