### ISSUE TITLE
remove redundant tooltip

### ISSUE THREAD

**Issue by katrinleinweber** [EFForg/privacybadgerfirefox#693]
[Continuing an older post](https://github.com/EFForg/privacybadgerfirefox/issues/528#issuecomment-136058579), I agree and would like to suggest to remove the dark-grey `allowed/blocked…` tooltip for each domain. It covers the entry below it & is redundant, because the domain is already the main part of the entry and the red/yellow/green slider shows its status clearly.

**Comment by cooperq** [comment]
So the one nice thing about the tooltip is that it allows users to see the whole domain name in cases where it gets cut off.  This is something that people seem to really like, so I wouldn't be comfortable with removing the tooltip until we have a way for people to see the whole domain.

**Comment by katrinleinweber** [comment]
True, seeing the full domain is important. Could it also be achieved by decreasing the font size to the same level as the tool tip? Or by expanding the pop-up on mouse-over (horizontally to the left, with domains right-aligned & control buttons remaining stationary)?

**Comment by cooperq** [comment]
I'm having a hard time visualizing what you are suggesting here. I'm reluctant to make the font smaller though because I think it would be too hard to read at that point.

**Comment by katrinleinweber** [comment]
In the meantime, the padding/margin below each domain entry has been increased so the tooltip doesn't cover the next entry anymore. Problem solved :-)
