### ISSUE TITLE
PB+ Cyberfox + Sandboxie

### ISSUE THREAD

**Issue by marzametal** [EFForg/privacybadgerfirefox#697]
On WIndows 7 Home Premium 64bit, 
I am running Cyberfox 42.0.1... PB 1.05... Sandboxie 5.06...

When I run Cyberfox normally with no restrictions or virtualization, PB works great!

As soon as I run Cyberfox inside a sandbox, it does not load. Well, as far as I can tell...
1) PB icon is missing from GUI
2) PB is still present in addon section of menu

Is there a way I can see if PB is actually running? I navigate to pages that PB has set tracker rules for, and I do not know if things are working or not...

**Comment by cooperq** [comment]
I'm pretty sure that privacy badger is incompatible with sandboxes since we determine what is a tracker by observing behavior over time instead of using a blacklist.  For sandbox use you probably will want to try one of the blacklist based tracker blockers such as disconnect or ublock.
