### ISSUE TITLE
Setting to disable the first run page

### ISSUE THREAD

**Issue by allo-** [EFForg/privacybadgerfirefox#698]
I am creating a profile generator for firefox, which preconfigures the profile for privacy https://github.com/allo-/firefox-profilemaker and would like to include privacy badger.
To avoid having a dozen of first-run pages in the generated profile, i would like to have the possiblity to disable the page on privacy badger. I currently tried to copy this setting into the profile:

    user_pref("extensions.jid1-MnnxcxisBPnSXQ@jetpack.sdk.load.reason", "startup");

But the installation seems to set it automatically to "install" and then show the privacy badger first run page.

By the way, the settings and id in the manifest seem to differ in the source and in the AMO version, the AMO version sets the @jetpack settings, while the defaults in the source have privacybadger there.

**Comment by cooperq** [comment]
I would happily accept a patch for this but it is not something that I have time to work on, sorry.

**Comment by allo-** [comment]
As far as i see, the loadReason is set by the SDK.
Would you mind having another setting "firststartPageShown" or something similiar in addtion?

I can try to look into accessing a setting which does not need to be present for normal usage, but i am not sure if you can do so with the new extension SDK. My last firefox extension is some time ago ;-).

**Comment by cooperq** [comment]
having such a setting would be fine (though you should note that soon this codebase will be deprecated and we will be using the web extensions API).

**Comment by allo-** [comment]
This pullrequest should do. I am not sure about the settingname and how/why the build.sh script replaces "privacybadger" with an cryptic ID. Maybe the name of the setting needs to be adapted to this.

**Comment by allo-** [comment]
Any comment? Is there a reason, you're not merging it?

**Comment by cooperq** [comment]
Sorry, I haven't had time to merge pull requests for a while. It is now merged. Thanks for the commit!
