### ISSUE TITLE
Invalid `<img>` for replaced social buttons

### ISSUE THREAD

**Issue by Ryuno-Ki** [EFForg/privacybadgerfirefox#701]
When assigning the text here:

https://github.com/EFForg/privacybadgerfirefox/blob/438b079a03a60cc1edb81d1e3458231b7474c986/data/socialwidgets.js#L105

to an `alt`-attribute instead of `title`, [AT](https://en.wikipedia.org/wiki/Assistive_technology) can deal with the `<img>` better. According to the spec, every `<img>` needs to have an `alt`-attribute (can be empty).

**Comment by cooperq** [comment]
Thanks for letting us know about this! I definitely want to ensure that privacy badger is accessible for everyone. Is there any chance you would be interested in submitting a patch to fix this? It would be extremely helpful, and you would be a hero!

**Comment by Ryuno-Ki** [comment]
@cooperq Sorry, I was on vacation. Thanks, @C0rby for submitting a PR!

You could paste HTML snippets into https://tenon.io/ to get a sense of how accessible the results are. Tenon is made by Web Accessibility Gurus (TM) ;-)

Another tool in your chain may be [ally.js](http://allyjs.io/).

**Comment by cooperq** [comment]
Fixed in #707, thanks @C0rby !
