### ISSUE TITLE
The Intercept does not load correctly with Privacy Badger

### ISSUE THREAD

**Issue by andreicristianpetcu** [EFForg/privacybadgerfirefox#704]
Check this URL https://theintercept.com/2015/12/23/juniper-firewalls-successfully-targeted-by-nsa-and-gchq/
![screen shot 2015-12-24 at 16 28 23](https://cloud.githubusercontent.com/assets/922368/11995559/96037270-aa5b-11e5-80b9-c4a601938ff0.png)

**Comment by cooperq** [comment]
unblocking firstlook.org fixes this issue. I have added it to cookie block list.

**Comment by andreicristianpetcu** [comment]
How can I test? Does the latest version have this fix?

**Comment by cooperq** [comment]
You can test by moving firstlook.org to green or yellow. Otherwise it should happen automatically in a few days. (but for now just move it yourself.)

**Comment by andreicristianpetcu** [comment]
It works now even if I have privacy badger on both web sites :) Thank you!
