### ISSUE TITLE
Google Play search breaks in conjunction with NoScript

### ISSUE THREAD

**Issue by rugk** [EFForg/privacybadgerfirefox#706]
*Note:* The gif is this issue are be very large. They may take some time to load.

We have the following situation:
* Firefox 43.0.2 installed
* NoScript 2.7 installed
* Privacy Badger 1.0.5 installed

Additionally the configuration for NoScript is:
* the default whitelist was deleted completely
* a new entry was added to the whitelist: `https://`
 * this means JS is automatically allowed on all HTTPS sites

Now we visit play.google.com and try to search for something. It does not work and the UI does not react on a click.

Here you can see it really only happens in this situation and that these two extensions are the culprit:
![extensionshow](https://cloud.githubusercontent.com/assets/11966684/12021100/57838b40-ad83-11e5-8171-ef5bc215362a.gif)

https://cloud.githubusercontent.com/assets/11966684/12021100/57838b40-ad83-11e5-8171-ef5bc215362a.gif

I've narrowed this issue down a bit more and the issue only happens when Privacy Badger blocks `www.google-analytics.com` completely (not only cookie-blocking).
![issuebreakdown](https://cloud.githubusercontent.com/assets/11966684/12021161/183c845e-ad84-11e5-8b56-989d735651c1.gif)

https://cloud.githubusercontent.com/assets/11966684/12021161/183c845e-ad84-11e5-8b56-989d735651c1.gif

More details here (another GIF):
http://www.file-upload.net/download-11160283/IssueBreakdown2_Again.gif.html

This issue was also reported to NoScript: https://forums.informaction.com/viewtopic.php?f=10&t=21517

**Comment by cooperq** [comment]
this sounds like another argument for script surrogates as in efforg/privacybadgerchrome#400

**Comment by rugk** [comment]
In the NoScript forum it was said this issue is a noscript issue. Therefore I am closing the issue here.
