### ISSUE TITLE
Alternatives to SoundCloud popup

### ISSUE THREAD

**Issue by franzwr** [EFForg/privacybadgerfirefox#712]
When visiting a page with embedded SoundCloud, I am greeted by this popup:

<img width="437" alt="screen shot 2016-01-06 at 16 51 31" src="https://cloud.githubusercontent.com/assets/4754508/12146841/41e1988a-b496-11e5-8059-76d8dd279be8.png">

Is there an alternative to either allowing permanently or blocking the widget permanently?, i.e. temporarily. Maybe another alternative would be to do the same as with the "like" buttons, replacing them with a static equivalent.

Privacy Badger 1.0.3.

Thanks!

**Comment by chepec** [comment]
[Closely related issue](https://github.com/EFForg/privacybadgerchrome/issues/708) in the Privacy Badger Chrome issue queue.

**Comment by cooperq** [comment]
I agree that replacing it with a static button e.g. what we do with social widgets is a good way to go.

**Comment by cooperq** [comment]
fore more info see efforg/privacybadgerchrome#400
