### ISSUE TITLE
each time I whitelist a domain in PB preferences, Filter Settings tab is activated instead of current Whitelisted Domains tab

### ISSUE THREAD

**Issue by antistress** [EFForg/privacybadgerfirefox#714]
Each time I whitelist a domain in PB preferences, Filter Settings tab is activated instead of current Whitelisted Domains tab (note that the change is taking into account and THEN the tab is de-activated) which means that if I want to whitelist several domains I have to re-activate again and again the Whitelisted Domains tab... 
Thanks
Firefox 45.0a2 on Debian GNU/Linux and PB 1.0.5

**Comment by cooperq** [comment]
This should be easy to use by including an anchor in the url for which tab you are on. E.g. resource://jid1-mnnxcxisbpnsxq-eff-at-jetpack/data/options.html#whitelisted-domains

**Comment by cooperq** [comment]
Closed via #742
