### ISSUE TITLE
High CPU load iwth PB 1.0.5 on iceweasel 43.0.2

### ISSUE THREAD

**Issue by jniggemann** [EFForg/privacybadgerfirefox#717]
### Environment

* Lenovo T400
* Debian wheezy 32 bit
* PB 1.0.5
* Iceweasel 43.0.2 
    * Greasemonkey
    * Linkificator
    * NoScript
    * Stylish
    * UAControl
    * uBlock Origin

### Issue (reproducible)
4 Tabs open, iceweasel in background and idle, PB enabled => 'top' shows constant CPU load between 10 and 15%. I verified that the network is idle, too while iceweasel creates this CPU load.

I deactivate PB and restart iceweasel with the same profile on no other changes, i.e. the same tabs open. 'top' shows 0.0 to 0.7% CPU load under the very same conditions.

Re-enabling PB and restarting iceweasel leads to the same 10-15% CPU load as initially observed.

To verify a cross-add-on issue, I deactivated all add ons but PB and restarted iceweasel, but that didn't lower the CPU load of 10-15%.

I also tried all of this with a new and empty profile, but no changes.

Any advice how to debug (please be technical)?

**Comment by cooperq** [comment]
hmmm, very interesting. I will have to set up a debian machine to debug this issue. My first guess is that it is a bug in iceweasel or some weirdness with 32 bit machines. You could run the firefox dev tools profiler on a tab and see if anything related to the extension shows up. I wonder if there is a way we could run a profiler directly on privacy badger...

**Comment by Konfekt** [comment]
Similar over here. about:performance always list privacy badger on top and gives a constant > 8 % CPU load.

**Comment by cooperq** [comment]
This should be fixed by the move to web extensions. Won't fix in the legacy branch, but do try updating to the latest version! 1.8.1 as of today.
