### ISSUE TITLE
PB broken on Firefox v46 (Developer Edition)

### ISSUE THREAD

**Issue by VNovotna** [EFForg/privacybadgerfirefox#733]
PB is broken in FIrefox 46.0a2 (2016-02-12) on Ubuntu Linux. 
![snimek obrazovky porizeny 2016-02-16 10-44-47](https://cloud.githubusercontent.com/assets/3995985/13197950/5e3ce244-d7fc-11e5-9282-c1f266cc7ba1.png)
I'm willing to debug it but don't know where to begin. Could it be because of e10s?

**Comment by CromFr** [comment]
Same issue for me using Firefox Nightly 47.0a1 (2016-01-29)

I tried with non-e10s window on a blank profile, on both Windows and Linux

**Comment by cooperq** [comment]
This is fixed by a patch someone submitted earlier. The next release should work as expected (I will get it out tomorrow or monday)

**Comment by finalfantasia** [comment]
@cooperq would you please release a version with this fix.
Thank you.

**Comment by cooperq** [comment]
Fixed version is out now.

**Comment by VNovotna** [comment]
It works only for non-e10s window for me. Although the PB window looks different.
![non-e10s](https://cloud.githubusercontent.com/assets/3995985/13632556/823c84fa-e5ea-11e5-9344-d6b5f1b8cfd6.png)
![e10s](https://cloud.githubusercontent.com/assets/3995985/13632558/82637ace-e5ea-11e5-8f9d-4fdf01b4169a.png)
