### ISSUE TITLE
Suggestion: have logo in add-on panel redirect to main site

### ISSUE THREAD

**Issue by onebree** [EFForg/privacybadgerfirefox#739]
**Action**: clicking the large badger logo in add-on panel (see below)

![sample-pb-panel](https://cloud.githubusercontent.com/assets/9038433/13402862/3933f72c-dee0-11e5-926f-3830e7fe747a.png)

**Expectation**: Opens new window/tab to [PB homepage][1]

**Result**: Toggles site activation

[1]: https://www.eff.org/privacybadger

**Comment by cooperq** [comment]
Seems like a good idea to me!
