### ISSUE TITLE
PB blocks X-notifier add-on for gmail accounts

### ISSUE THREAD

**Issue by GAJansen** [EFForg/privacybadgerfirefox#743]
PB blocks X-notifier add-on for gmail accounts, while for other mail accounts X-notifier works fine.
Does anyone know what to unblock in PB to get gmail notifications working again in X-notifier?

**Comment by cooperq** [comment]
can you tell me which domains are being blocked by privacy badger on gmail?

**Comment by GAJansen** [comment]
Hi Cooperq,
The following domains are being blocked (yelllow slider in PB for all):
- accounts.google.com
- apis.google.com
- www.google.com
- plus.google.com

**Comment by GAJansen** [comment]
Hi Cooperq,
The following domains are being blocked (yelllow slider in PB for all):

   - accounts.google.com
   - apis.google.com
   - www.google.com
   - plus.google.com

**Comment by cooperq** [comment]
if you disable privacy badger on gmail.com does it fix the issue?

**Comment by vin100vin** [comment]
This is quiet a problem. I also have to disable PB. 
Any idea to fix the problem

**Comment by lusteri** [comment]
Found this thread when trying to figure out why X-Notifier wasn't checking my gmail accounts.
I believe it is the cookies being blocked for accounts.google.com
I just enabled accounts.google.com fully (previously only cookies were blocked) and now when I attempt to check mail via X-notifier, gmail checks fine.

**Comment by cooperq** [comment]
@GAJansen @vin100vin does moving accounts.google.com to green fix the issue for you?

**Comment by GAJansen** [comment]
@1s3v3n : giving "accounts.google.com" the green light in PB solved the issue for me too, X-notifier works fine for all my gmail accounts. Also, I have a long list of "*.google.com" references for which cookies are blocked in PB (yellow slider), and for me too, "google.com" is red and 
"accounts.google.com" is green. No need to share your list of related entries.
Thanks for this solution!

@cooperq : As described above, the issue has been fixed for me too.
