### ISSUE TITLE
Privacy Badger decided to block my own personal site

### ISSUE THREAD

**Issue by spinda** [EFForg/privacybadgerfirefox#748]
I realized today that none of the images on [my blog](https://spindas.dreamwidth.org/2765.html) were loading in Firefox. They're all hosted on my personal site, www.spinda.net. I narrowed the problem down to Privacy Badger, which had somehow identified my domain as a tracker and switched it to "full block" mode.

Is there any way I can find out why Privacy Badger classified my site this way? I've whitelisted it on my install, but I'd like to make sure my site isn't getting blocked for other users of the extension.

**Comment by spinda** [comment]
I *am* using CloudFlare on this domain, so perhaps #472 has something to do with it?

**Comment by cooperq** [comment]
spinda.net will only get blocked if the user visits three sites that include resources from it.  It seems like most people are unlikely to visit three different sites that include content from spinda.com so I don't think that this is something you should need to worry about.
