### ISSUE TITLE
All sliders default to green

### ISSUE THREAD

**Issue by synthtel** [EFForg/privacybadgerfirefox#749]
Privacy Badger is working when I manually set sliders to something other than green, but everything is green unless I tell it otherwise. ~~It looks pretty similar to issue 353 in the Chrome version of PB, but I didn't find any similar reports for the FF version.~~ EDIT: It is learning, it's just doing so vastly slower than I recalled.

I've tried reinstalling PB, but nothing changed. I'm on fully up-to-date Arch Linux and Firefox 45.0.1. My only other extension is HTTPS Everywhere. The problem started at a recent OS reload (an SSD died), but the configuration of the system and FF is almost exactly the same as when it was working (to the best of my knowledge, FF config is exactly the same).

**Comment by riking** [comment]
PrivacyBadger uses herustics to determine if a domain is tracking you. One red flag is that a third-party domain shows up on several other domains, and sets cookies. Keep browsing around, and the sliders should automatically adjust.

**Comment by synthtel** [comment]
How long does it usually take to adjust? Looking again after the better part of a week, there are a handful of domains it's decided to do something about, but in my experience with it before (similar browsing patterns), I seem to recall it pretty much having things sorted out within a couple of days (for the sites I visit most often, at least).

**Comment by cooperq** [comment]
So privacy badger should usually start blocking things after the third time it sees them, if they look like they are tracking you. 

HOWEVER if you are doing something like always running in private browsing mode, privacy badger will forget its heuristics each time you restart the browser. Or if you are blocking third party cookies and javascripts by default, privacy badger wont see many things as tracking. Is it possible that you are doing one of these things?

**Comment by synthtel** [comment]
Ah, I do have third-party cookies disabled. That makes sense. On further investigation, it also looks like the ads on my most visited sites are pulled from quite a variety of sources (I think the worst offender might have changed this a year or two ago), and I guess it wouldn't be too surprising if it just is taking that long to see certain trackers three times. It's still doing better, up to probably 50% now, and I imagine the third-party cookie thing accounts for a big chunk of the rest. Thanks!
