### ISSUE TITLE
Multi-site CDN blocked due to CloudFlare cookie - lock to yellow?

### ISSUE THREAD

**Issue by riking** [EFForg/privacybadgerfirefox#752]
Original report: https://meta.discourse.org/t/blank-page-unless-i-start-a-new-session/17127/
specifically: https://meta.discourse.org/t/blank-page-unless-i-start-a-new-session/17127/26?u=riking

The `cdn-business.discourse.org` gets flagged by Privacy Badger because CloudFlare is setting the `__cfduid` cookie. 

Could we get this domain locked to yellow in Privacy Badger, or something? Blocking cookies is fine, it's a CDN so it doesn't need them.

`avatars.discourse.org` was also pointed to as being blocked, ~~but that may be because it sets suspicious E-Tags: https://github.com/discourse/letter-avatars/blob/master/lib/letter_avatar_app.rb#L51~~ nope it's also on CloudFlare

**Comment by riking** [comment]
Actually, idea - would setting `crossorigin=anonymous` on the script tag fix this?

**Comment by riking** [comment]
> Actually, idea - would setting crossorigin=anonymous on the script tag fix this?

Looks like the answer *might* be yes: https://github.com/EFForg/privacybadgerchrome/blob/3b32d0a61d6a45500b53e428d913b32fcbe0cb65/src/heuristicblocking.js#L441-L469

I'll get some experiments run..

**Comment by riking** [comment]
So this is a code change request to add a mechanism so that certain domains always return "cookieblock" from checkAction.

**Comment by riking** [comment]
Okay, just discovered https://github.com/EFForg/privacybadgerchrome/blob/master/yellowlist-criteria.md 

>  - Was this in Bau and Mayer's manually curated non-tracker list?

I don't even really need to look, the answer is no, of course not..

> - Is this domain necessary for functionality the user expects from 1st party pages?

Yes, this is the CDN hosting the scripts that are (by default on opensource installs) hosting the scripts that make the page work. It also hosts user-uploaded images.

> - Is the domain's privacy policy clear that it does not perform non-consensual tracking?

Mixed: the standard DNT policy is posted and adhered to by @discourse, but the cookies are being set by Cloudflare which does perform the tracking.

> - Is there a reasonable self-hosted surrogate available that could replace the functionality of this domain (e.g. https://github.com/EFForg/privacybadgerchrome/issues/400).

No, because the domain is serving the user-uploaded image files as well as the necessary scripts. This is not easily replaceable with local functionality.

**Comment by riking** [comment]
> Mixed: the standard DNT policy is posted and adhered to by @discourse, but the cookies are being set by Cloudflare which does perform the tracking.

Here's an idea - use `cookieblock` for any 3rd party cookie named `__cfduid` UNLESS the ResourceType  (`details.type`) is "main_frame" or "sub_frame", in which case use normal processing rules.

**Comment by riking** [comment]
The issue has been corrected on our side.

> @mpalmer
> Speaking entirely for myself, I find Cloudflare's addition of a top-of-zone tracking cookie to be appalling behaviour. I thought they were one of the good guys, but this... not so much.

> I've made the necessary changes to have avatars.discourse.org served via an alternate CDN (MaxCDN). I've verified that the responses now come back with no cookies whatsoever. If anyone sees any issues, or even if the Privacy Badger problems don't abate, please respond in this topic.

**Comment by cooperq** [comment]
:+1: Glad you were able to resolve this. I am indeed very concerned about what do about cloudflare's cookies.
