### ISSUE TITLE
Google Inbox (Gmail) endlessly reloading

### ISSUE THREAD

**Issue by PacoBell** [EFForg/privacybadgerfirefox#753]
Something related to Privacy Badger is causing to Inbox to be stuck in and reload loop, even if I disable it for that site. Removing the Privacy Badger extension stops this behavior.

**Comment by frasc** [comment]
I have more or less the same problem. I didn't have to remove the extension though, just unblocking the domains made it work.

same infinite loop issue also for calendar and contacts.

**Comment by cooperq** [comment]
Please send me a screenshot of the privacy badger popup in gmail.com

**Comment by frasc** [comment]
sure, will do, as soon I've figured a way to take a snapshot so that
clicking on the snapshot tool doesn't make the badger info disappear

thanks for your work on 'badger'

--frr

**Comment by PacoBell** [comment]
I think I've narrowed it down to blocking cookies for the googleusercontent.com domain. By default, it's fully enabled. See if you can repro by blocking it, too.

**Comment by frasc** [comment]
> I think I've narrowed it down to blocking cookies for the
> googleusercontent.com domain. By default, it's fully enabled. See if
> you can repro by blocking it, too.
>
doesn't do the trick for me.

the only way I could so far reproduce is by sliding the badger bars to
"yellow" for:
apis.google.com
calendar.google.com
plus.google.com
www.google.com

leave on "green"
accounts.com
and the 7 domains mentioned as "don't appear to be tracking you",
googleusercontent.com being one of them

Ha. Google is working reeal hard to know everything about us ;-)

thanks again,

--Frederic

**Comment by cooperq** [comment]
I am still completely unable to repro this. I have every domain yellowlisted and gmail works just fine for me.

**Comment by frasc** [comment]
> I am still completely unable to repro this. I have every domain
> yellowlisted and gmail works just fine for me.
>
Actually I've noticed this morning that it was working at startup.
Reloding gmai or calendar or contacts makes the tab spinning wheel go
for a bit but then it stops spinning by itself.

so at that point, you're right, it is not reproducible.

thanks for the terrific job you guys are doing! :-)

--Frederic

**Comment by cooperq** [comment]
Closing this for now. Please re-open if it happens again.
