### ISSUE TITLE
Not working at all in Firefox 45.0.2

### ISSUE THREAD

**Issue by fstirlitz** [EFForg/privacybadgerfirefox#762]
Some time after upgrading to Firefox 45.0.2 (which I believe was the cause), I noticed that Privacy Badger doesn't seem to do anything, despite being enabled. It doesn't detect any trackers on any site or block anything.

**Comment by cooperq** [comment]
Hmm, I am not able to reproduce this problem.  If you open up menu -> developer -> browser console do you see any messages from privacy badger? Have you changed any of the default firefox settings? Does privacy badger work in a fresh firefox profile? Do you have any other extensions installed?

**Comment by fstirlitz** [comment]
That might have actually been a false alarm. I cleared my settings, purged the extension's data, and PB started blocking some things again. On the other hand, there _subjectively_ seem to be so many fewer items on the list of potential trackers. Most notably, Facebook widgets (iframes with src `facebook.com/plugins/like.php`) stopped being recognised as trackers. While `document.cookie` may be empty, I'd still rather have them blocked.

But since I can no longer point to an objective, reproducible behaviour, I should probably close this. Oh well, apparently I need a separate extension.
