### ISSUE TITLE
MTG sites not working with Privacy Badger

### ISSUE THREAD

**Issue by flyingzebras** [EFForg/privacybadgerfirefox#774]
Modern Times Group (MTG) is a Swedish digital entertainment company. They stream Swedish channel programs on these domains that are also broadcasted on the Swedish terrestrial network (https://en.wikipedia.org/wiki/Template:Television_in_Sweden):
* TV3, [TV3 Play](http://tv3play.se)
* TV6, [TV6 Play](http://tv6play.se)
* TV8, [TV8 Play](http://tv8play.se)
* TV10, [TV10 Play](http://tv10play.se)

I cannot use these sites with Privacy Bagder.

Please see https://github.com/reek/anti-adblock-killer/issues/1465

**Comment by cooperq** [comment]
it seems like moving analytics.google.com to cookieblock fixes the issue on this site. This is probably another vote for script surrogates.

**Comment by flyingzebras** [comment]
@cooperq Thank you.

**Comment by flyingzebras** [comment]
@cooperq Did you fix the code for this in Privacy Badger?

Also, you should check this out: https://github.com/reek/anti-adblock-killer/issues/1463

**Comment by flyingzebras** [comment]
https://github.com/EFForg/privacybadgerfirefox/issues/776

**Comment by davidhedlund** [comment]
https://github.com/reek/anti-adblock-killer/issues/1940

**Comment by flyingzebras** [comment]
This problem do not occur on [viafree.se](http://viafree.se/).
