### ISSUE TITLE
Dplay sites not working with Privacy Badger

### ISSUE THREAD

**Issue by flyingzebras** [EFForg/privacybadgerfirefox#776]
[dplay.com](http://dplay.com) (owned by Discovery) lists these domains which all detect blockers:
* [it.dplay.com](http://it.dplay.com)
* [dplay.se](http://dplay.se)
* [dplay.dk](http://dplay.dk)

The above domains offer the following channels (also broadcasted on the Swedish terrestrial network):
* Kanal 5
* Kanal 9
* Kanal 11
* Eurosport 1
* Discovery

Incompatible blockers
* Privacy Badger

**Comment by flyingzebras** [comment]
https://github.com/EFForg/privacybadgerfirefox/issues/774

**Comment by flyingzebras** [comment]
Appear to me that dplay.se can be streamed with Privacy Badger enabled now. Great.

**Comment by flyingzebras** [comment]
Privacy Badger 1.8.1 doesn't work with dplay.se.

**Comment by flyingzebras** [comment]
The links will not work with scorecardresearch.com blocked.

**Comment by cooperq** [comment]
I am absolutely not going to unblock scorecard research. But for now you can work around it by disabling privayc badger on the effected sites or moving the trackers to cookieblocked status.

**Comment by flyingzebras** [comment]
@cooperq Thanks.
