### ISSUE TITLE
Block all trackers by default option

### ISSUE THREAD

**Issue by juhiyu** [EFForg/privacybadgerfirefox#778]
I cannot see any Block all trackers by default option

Can this be added?

**Comment by cooperq** [comment]
No, this would break waaay to many things, and I won't give users a gun to shoot their own feet with.

**Comment by juhiyu** [comment]
Works pretty well with Ghostery, why would it not work with Privacy Badger?

**Comment by cooperq** [comment]
We block more stuff than ghostery does, also we use a heuristic not a black list so we have to determine dynamically what is a tracker. When we decide something is a tracker we already do block it by default. The closest analog here would be to block all third party resources by default which would break way too many things.
