### ISSUE TITLE
Can't install Privacy Badger on Firefox 47.0 for Android

### ISSUE THREAD

**Issue by srjacob999** [EFForg/privacybadgerfirefox#779]
When I try to install Privacy Badger on Firefox 47.0 for Android, I am told by Firefox that this is a blocked add-on, and asked if I want to allow it.  I press allow, and get the message downloading add-on, but nothing installs on Firefox.

How do I install Privacy Badger on Firefox for Android?

Thank you.

**Comment by cooperq** [comment]
Privacy Badger is not currently compatible with firefox for android. See #194
