### ISSUE TITLE
PB Seems To Prevent An Icon From Displaying

### ISSUE THREAD

**Issue by sudleyplace** [EFForg/privacybadgerfirefox#780]
While this doesn't constitute hard evidence, when I display my own website home page at http://www.nars2000.org and scroll down to the bottom (or click on Donations on the left which gets you there more quickly) if PB is enabled, I don't see the two icons about W3C XHTML and CSS Validation.  Instead I see the alt text of "Valid XHTML 1.0!" and "Valid CSS!".  When PB is disabled, those two icons display correctly.

I disabled all of my extensions (maybe 30).  When I enabled PB as the only extension, the icons disappeared.  When I disabled PB, the icons appear.

Both of these icons are served from http://www.sudleyplace.com/icons/ as in
<a href="http://validator.w3.org/check?uri=referer"><img
   style="border:0; width:88px; height:31px;"
   src="http://www.sudleyplace.com/icons/valid-xhtml10.png"
   alt="Valid XHTML 1.0!"
   title="XHTML Validator" /></a>
The icons display correctly alone on a page if you copy the src= value to the address bar.  These same two icons display correctly at the bottom of the home page of http://www.sudleyplace.com via the same HTML code as above even if PB is enabled.  Go figure.

I'm running FF 47.0 and PB 1.0.6 from Mar 4, 2016.

**Comment by cooperq** [comment]
This will only happen for people who have a cookie from sudleyplace.com and see it as a third party domain on three or more first parties which causes privacy badger to think it's a tracker. I'm sorry that this happened for you but I think it's unlikely to happen to anyone else visiting your website. When I visit your website privacy badger says that sudleyplace.com is not tracking me and so it doesn't get blocked. 
For yourself you can move the slider to yellow or green for sudleyplace.com to fix the problem.
