### ISSUE TITLE
jid1-mnnxcxisbpnsxq-at-jetpack (jid1-MnnxcxisBPnSXQ@jetpack.xpi) blocked by RequestPolicyContinued

### ISSUE THREAD

**Issue by QuantumLeapYourThinkingMeat** [EFForg/privacybadgerfirefox#782]
jid1-mnnxcxisbpnsxq-at-jetpack (jid1-MnnxcxisBPnSXQ@jetpack.xpi) is blocked by RequestPolicyContinued.  When PrivacyBadger is disabled, the listing and blocking of the file disappears from RequestPolicyContinued.  What is the relationship of the jetpack file to privacy badger?  It seems to point to resource://jid1-mnnxcxisbpnsxq-at-jetpack/data/firstRun.html.  Why is the file always running?  Seems to be located at /home/xxxx/.mozilla/firefox/8cgml8gs.default-1466598362164/extensions

Firefox 47.0 on Ubuntu 14.04.3

**Comment by cooperq** [comment]
firstRun is the page which gets loaded on the first run of privacy badger which explains how to use privacy badger. Not sure if I can do anything about this.
