### ISSUE TITLE
Domain list missing

### ISSUE THREAD

**Issue by zticky** [EFForg/privacybadgerfirefox#784]
When I press  Privacybadger icon i Firefox 64-bit 47.0 and 64-bit 48.0 the domain list with buttons is missing. In Firefox 32-bit 47.0 domain list shows.

**Comment by cooperq** [comment]
Do you happen to have multiprocess firefox enabled?

**Comment by zticky** [comment]
Yes. It seems the domain list disappears when browser.tabs.remote.autostart is set to true in about:config

**Comment by neonriots** [comment]
Also experiencing this issue since upgrading to Firefox 48 earlier today.  Previous version was fine.  Do not have multiprocess enabled.  List of domains is missing, Privacy Badger says 0 potential trackers but the number of trackers shown in the red badge over the PB icon still increments.

**Comment by cooperq** [comment]
This should be fixed as of privacy badger 1.8.1 , please update your addons
