### ISSUE TITLE
Broken with Firefox Developer Edition

### ISSUE THREAD

**Issue by binaryanomaly** [EFForg/privacybadgerfirefox#787]
Hi,

Just to let you know, v 1.7.0 does not work at all with Firefox Developer Edition.

Looking forward to when it does...

**Comment by focmb** [comment]
Same here with Firefox Nightly. I disabled the multi processing in the preferences and now Privacy Badger works again.

**Comment by focmb** [comment]
Worked only once :(

`journalctl -b | grep "firefox-nightly.desktop` gives me the following information:

`
Jul 20 10:54:11 station2 firefox-nightly.desktop[1000]: (firefox:1000): Gtk-WARNING **: Theme parsing error: gtk.css:3213:17: The 'icon-shadow' property has been renamed to '-gtk-icon-shadow'
Jul 20 10:54:11 station2 firefox-nightly.desktop[1000]: (firefox:1000): Gtk-WARNING **: Theme parsing error: gtk.css:6279:23: The '-gtk-image-effect' property has been renamed to '-gtk-icon-effect'
Jul 20 10:54:11 station2 firefox-nightly.desktop[1000]: (firefox:1000): Gtk-WARNING **: Theme parsing error: gtk.css:6473:16: The 'outline-radius' property has been renamed to '-gtk-outline-radius'
Jul 20 10:54:11 station2 firefox-nightly.desktop[1000]: (firefox:1000): Gtk-WARNING **: Theme parsing error: gtk.css:6496:52: The :prelight pseudo-class is deprecated. Use :hover instead.
Jul 20 10:54:41 station2 firefox-nightly.desktop[1000]: Vector smash protection is enabled.
Jul 20 10:54:53 station2 firefox-nightly.desktop[1000]: console.error: privacybadger:
Jul 20 10:54:53 station2 firefox-nightly.desktop[1000]:   Message: TypeError: action.contains is not a function
Jul 20 10:54:53 station2 firefox-nightly.desktop[1000]:   Stack:
Jul 20 10:54:53 station2 firefox-nightly.desktop[1000]:     refreshPopup@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/loader/sandbox.js -> resource://jid1-mnnxcxisbpnsxq-at-jetpack/data/popup.js:232:11
Jul 20 10:54:53 station2 firefox-nightly.desktop[1000]: @resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/loader/sandbox.js -> resource://jid1-mnnxcxisbpnsxq-at-jetpack/data/popup.js:472:3
Jul 20 10:54:53 station2 firefox-nightly.desktop[1000]: onEvent@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/loader/sandbox.js -> resource://gre/modules/commonjs/sdk/content/content-worker.js:45:22
Jul 20 10:54:53 station2 firefox-nightly.desktop[1000]: onEvent@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/loader/sandbox.js -> resource://gre/modules/commonjs/sdk/content/content-worker.js:45:22
Jul 20 10:54:53 station2 firefox-nightly.desktop[1000]: onChromeEvent@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/loader/sandbox.js -> resource://gre/modules/commonjs/sdk/content/content-worker.js:91:16
`

I don't know if this is a problem with Firefix-Nightly or Privacy Badger

**Comment by cooperq** [comment]
This should now be fixed :)
