### ISSUE TITLE
TypeError: Window is Null

### ISSUE THREAD

**Issue by Drixer** [EFForg/privacybadgerfirefox#791]
I receive the following error constantly, active or not. "TypeError: window is null Source File: resource://gre/modules/commonjs/toolkit/loader.js -> resource://jid1-mnnxcxisbpnsxq-at-jetpack/lib/contentPolicy.js Line: 204" the actual code is as follows:

    let topWin = window.top;
    if (!topWin || !topWin.location || !topWin.location.href) {
      console.log("Couldn't get window.top for request:", location.spec);
      return false;
    }

I would imagine checking "window" for null prior to setting topWin would resolve it, but this is only a guess since i am not all that familiar with javascript.

**Comment by cooperq** [comment]
I am halting all development on this version of privacy badger in favor of getting a web extension compatible version of privacy badger for firefox released. This will share the same codebase with https://github.com/efforg/privacybadgerchrome. I imagine that this will not be an issue once that happens.
