### ISSUE TITLE
No longer see what cookies are blocked, corrupt graphics

### ISSUE THREAD

**Issue by Learn-Digital-Audio** [EFForg/privacybadgerfirefox#795]
recently you click the bader icon in firefox and there is a big empty space where the info on the cookies used to be, and also the donate button is cut off. not sure when this began, but today i am running:

windows 7
firefox 48
privacy bader 1.8.1

![badgerbug](https://cloud.githubusercontent.com/assets/12832280/17549597/e0c9916c-5ee8-11e6-9a5d-124f77bdfe06.png)

**Comment by cooperq** [comment]
Can you open the browser console and tell me if there are any errors there? Also please try disabling and re-enabling privacy badger in about:addons

**Comment by Learn-Digital-Audio** [comment]
disabling and re-enabling fixed it :) thanks.
