### ISSUE TITLE
Incompatible with Google Play/Books

### ISSUE THREAD

**Issue by npsimons** [EFForg/privacybadgerfirefox#799]
This didn't start happening until very recently (the last few days), so it could be a change on either end (Google or Privacy Badger). I suspect a rule somewhere has become overzealous so that even if I want to read books I have purchased in Google Play within my web browser, Privacy Badger effectively breaks Google Books.

**Comment by cooperq** [comment]
Can you tell me what domains are listed on google books and what their status is?

**Comment by cooperq** [comment]
It looks like unblocking books.googleusercontent.com in your privacy badger settings should fix this issue.

**Comment by juliet1797** [comment]
Ok

**Comment by juliet1797** [comment]
Ok whats all this as i see alot downloaded in my files ..im not a computer wiz as i do know all apps n data system is alternated as i see from africa n through. Ubs

**Comment by juliet1797** [comment]
Ok whats all this as i see alot downloaded in my files ..im not a computer wiz as i do know all apps n data system is alternated as i see from africa n through. Ubs

**Comment by juliet1797** [comment]
Ok whats all this as i see alot downloaded in my files ..im not a computer wiz as i do know all apps n data system is alternated as i see from africa n through. Ubs

**Comment by juliet1797** [comment]
Ok whats all this as i see alot downloaded in my files ..im not a computer wiz as i do know all apps n data system is alternated as i see from africa n through. Ubs

**Comment by juliet1797** [comment]
Ok whats all this as i see alot downloaded in my files ..im not a computer wiz as i do know all apps n data system is alternated as i see from africa n through. Ubs

**Comment by juliet1797** [comment]
Ok whats all this as i see alot downloaded in my files ..im not a computer wiz as i do know all apps n data system is alternated as i see from africa n through. Ubs
