### ISSUE TITLE
Credits question for fork

### ISSUE THREAD

**Issue by Fred-Barclay** [EFForg/privacybadgerfirefox#808]
G'day mates! Thanks for all your work with Privacy Badger. It's been one of my "must-have" addons for some time. :smile:

I've been working on forking Privacy Badger to the Pale Moon browser. To avoid confusion with you guys' product and to ensure that no one confuses my work with an official EFF product, I've renamed it "Amnesiac Aardvark" (unless I get a better name soon!). https://github.com/Fred-Barclay/Amnesiac_Aardvark (currently semi-working).

A few questions:
Since this is not an EFF project, who should I list as creator in src/install.rdf? Currently I have myself listed as creator and the EFF as one of the contributors, since I don't want to accidentally mislead anyone to thinking that this is an EFF product.
But since I have only forked PB and didn't actually write it, I'm unsure if this would be correct or if I should list the EFF as the creator after all?

A similar question for src/package.json. In this case, I've listed the authors as the "Electronic Frontier Foundation and Fred Barclay". What would be correct in this case, as I don't have any affiliation with or approval from the EFF?

Thanks!
Fred

**Comment by cooperq** [comment]
You have our approval for the fork! (I like ammnesiac aardvark, let me also suggest privacy raccoon, or security stoat) 

Credit to us would be great, maybe just mention in your readme or whatever that it is a fork of privacy badger by EFF. Feel free to list us as one of the authors. 

:smile: good luck with the project! I'm glad you are bringing privacy badger to pale moon!

**Comment by Fred-Barclay** [comment]
Cool! I'll definitely be considering any name suggestions.

Pale Moon 27 (still in beta stage) doesn't allow Jetpack/SDK extensions so my attempts to get a fork working are going to be interesting, to say the least. :stuck_out_tongue_winking_eye:

**Comment by cooperq** [comment]
lol yea good luck with that! I do not envy the task ahead of you!
