### ISSUE TITLE
Firefox: Cookies not deleting on exit

### ISSUE THREAD

**Issue by thrnz** [EFForg/privacybadgerfirefox#85]
PrivacyBadger seems to be adding sites to the cookie exception list, causing them to no longer be deleted on browser close. Eg, accounts.youtube.com has been added to cookie exceptions as 'first party only' by PrivacyBadger and is not being cleared on browser shutdown anymore when 'keep cookies until I close FIreFox' is set.

**Comment by rugk** [comment]
Oh now I just saw this...
v 1.0.1

It were a lot of websites, but I'm not really sure whether these were added in a previous buggy version or in a recent version.
So I will have a look.
