### ISSUE TITLE
Icon needs some love.

### ISSUE THREAD

**Issue by rmenessec** [EFForg/privacybadgerfirefox#95]
Firefox, using small icons in the menubar:
![indian1](https://cloud.githubusercontent.com/assets/425616/2929116/9c009f36-d785-11e3-9e47-9cbce6ec82ab.png)
Also, could really use a snazzier icon at some point, or just one that blends well with the new Australis theme.

**Comment by cooperq** [comment]
The icon has been redesigned as of 1.0
