### ISSUE TITLE
Create interactive onboarding

### ISSUE THREAD

**Issue by diracdeltas** [EFForg/privacybadgerfirefox#96]
The firstRun.html text is too long, and at least one person told me they didn't read it. I almost never read the firstRun text for addons either.

This wastes time for us and for users in the long run. I've noticed that:
* Users don't understand what Privacy Badger does even at a high level (lots of emails about this).
* The functionality of the unblock-sites buttons is unclear to them.
* They may not realize you can click on the sliders to unblock things, or click on the arrow to undo settings. (Ex: #93)
* They don't realize you can disable PBadger on a single page instead of entirely to unbreak something on a page.

All of this should be covered in an interactive demo on install that walks them through all the buttons in Privacy Badger and what they do.

**Comment by chrish42** [comment]
It would be nice if it was also explained to new users upon onboarding which other addons Privacy Badger replaces. I had both Privacy Badger and ShareMeNot enabled, because I did not realize that Privacy Badger also had the equivalent functionality from ShareMeNot.

**Comment by cypherpunk** [comment]
Why do I have to waste my time always with videos. I want a clear text file with the details.

**Comment by cooperq** [comment]
fixed in #423
